/* tslint:disable */
/* eslint-disable */
/**
 * Arke IAM API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ArketAttr
 */
export interface ArketAttr {
    /**
     * 
     * @type {string}
     * @memberof ArketAttr
     */
    id: string;
}

/**
 * Check if a given object implements the ArketAttr interface.
 */
export function instanceOfArketAttr(value: object): value is ArketAttr {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function ArketAttrFromJSON(json: any): ArketAttr {
    return ArketAttrFromJSONTyped(json, false);
}

export function ArketAttrFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArketAttr {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function ArketAttrToJSON(json: any): ArketAttr {
    return ArketAttrToJSONTyped(json, false);
}

export function ArketAttrToJSONTyped(value?: ArketAttr | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

