/* tslint:disable */
/* eslint-disable */
/**
 * Arke IAM API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DateAttr } from './DateAttr';
import {
    DateAttrFromJSON,
    DateAttrFromJSONTyped,
    DateAttrToJSON,
    DateAttrToJSONTyped,
} from './DateAttr';

/**
 * 
 * @export
 * @interface NotificationSummary
 */
export interface NotificationSummary {
    /**
     * 
     * @type {string}
     * @memberof NotificationSummary
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof NotificationSummary
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof NotificationSummary
     */
    category?: string;
    /**
     * 
     * @type {number}
     * @memberof NotificationSummary
     */
    createdTs?: number;
    /**
     * 
     * @type {object}
     * @memberof NotificationSummary
     */
    metadata?: object;
    /**
     * 
     * @type {DateAttr}
     * @memberof NotificationSummary
     */
    acknowledged?: DateAttr;
}

/**
 * Check if a given object implements the NotificationSummary interface.
 */
export function instanceOfNotificationSummary(value: object): value is NotificationSummary {
    return true;
}

export function NotificationSummaryFromJSON(json: any): NotificationSummary {
    return NotificationSummaryFromJSONTyped(json, false);
}

export function NotificationSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotificationSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'type': json['type'] == null ? undefined : json['type'],
        'category': json['category'] == null ? undefined : json['category'],
        'createdTs': json['created_ts'] == null ? undefined : json['created_ts'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'acknowledged': json['acknowledged'] == null ? undefined : DateAttrFromJSON(json['acknowledged']),
    };
}

export function NotificationSummaryToJSON(json: any): NotificationSummary {
    return NotificationSummaryToJSONTyped(json, false);
}

export function NotificationSummaryToJSONTyped(value?: NotificationSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'category': value['category'],
        'created_ts': value['createdTs'],
        'metadata': value['metadata'],
        'acknowledged': DateAttrToJSON(value['acknowledged']),
    };
}

