/* tslint:disable */
/* eslint-disable */
/**
 * Arke IAM API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SettingsUpdate
 */
export interface SettingsUpdate {
    /**
     * 
     * @type {any}
     * @memberof SettingsUpdate
     */
    value: any | null;
}

/**
 * Check if a given object implements the SettingsUpdate interface.
 */
export function instanceOfSettingsUpdate(value: object): value is SettingsUpdate {
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function SettingsUpdateFromJSON(json: any): SettingsUpdate {
    return SettingsUpdateFromJSONTyped(json, false);
}

export function SettingsUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): SettingsUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'value': json['value'],
    };
}

export function SettingsUpdateToJSON(json: any): SettingsUpdate {
    return SettingsUpdateToJSONTyped(json, false);
}

export function SettingsUpdateToJSONTyped(value?: SettingsUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'value': value['value'],
    };
}

