/* tslint:disable */
/* eslint-disable */
/**
 * Arke IAM API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EmailAttr } from './EmailAttr';
import {
    EmailAttrFromJSON,
    EmailAttrFromJSONTyped,
    EmailAttrToJSON,
    EmailAttrToJSONTyped,
} from './EmailAttr';
import type { PhoneAttr } from './PhoneAttr';
import {
    PhoneAttrFromJSON,
    PhoneAttrFromJSONTyped,
    PhoneAttrToJSON,
    PhoneAttrToJSONTyped,
} from './PhoneAttr';
import type { AddressAttr } from './AddressAttr';
import {
    AddressAttrFromJSON,
    AddressAttrFromJSONTyped,
    AddressAttrToJSON,
    AddressAttrToJSONTyped,
} from './AddressAttr';

/**
 * 
 * @export
 * @interface TenantSettings
 */
export interface TenantSettings {
    /**
     * 
     * @type {Array<string>}
     * @memberof TenantSettings
     */
    uom: Array<string>;
    /**
     * 
     * @type {Array<AddressAttr>}
     * @memberof TenantSettings
     */
    addresses: Array<AddressAttr>;
    /**
     * 
     * @type {Array<EmailAttr>}
     * @memberof TenantSettings
     */
    emails: Array<EmailAttr>;
    /**
     * 
     * @type {Array<PhoneAttr>}
     * @memberof TenantSettings
     */
    phones?: Array<PhoneAttr>;
    /**
     * 
     * @type {string}
     * @memberof TenantSettings
     */
    website?: string;
    /**
     * 
     * @type {string}
     * @memberof TenantSettings
     */
    registeredCapital?: string;
    /**
     * 
     * @type {string}
     * @memberof TenantSettings
     */
    rea?: string;
    /**
     * 
     * @type {string}
     * @memberof TenantSettings
     */
    tradeRegister?: string;
    /**
     * 
     * @type {string}
     * @memberof TenantSettings
     */
    sdi?: string;
    /**
     * 
     * @type {string}
     * @memberof TenantSettings
     */
    pec?: string;
    /**
     * 
     * @type {string}
     * @memberof TenantSettings
     */
    vat: string;
    /**
     * 
     * @type {string}
     * @memberof TenantSettings
     */
    preferredPaymentMethod?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TenantSettings
     */
    isManufacturer?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof TenantSettings
     */
    isReseller?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof TenantSettings
     */
    isDirectToConsumer?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof TenantSettings
     */
    hasSalesAgents?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof TenantSettings
     */
    hasEcommerceSales?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof TenantSettings
     */
    hasDocumentSalesQuote?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof TenantSettings
     */
    hasDocumentSalesOffer?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof TenantSettings
     */
    hasDocumentSalesOrder?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof TenantSettings
     */
    hasDocumentPurchaseQuote?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof TenantSettings
     */
    hasDocumentPurchaseOrder?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof TenantSettings
     */
    hasSemi?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof TenantSettings
     */
    hasBundle?: boolean;
    /**
     * monthly availability in hours
     * @type {number}
     * @memberof TenantSettings
     */
    monthlyAvailability?: number;
    /**
     * track third-party warehouse
     * @type {boolean}
     * @memberof TenantSettings
     */
    trackSupplierWarehouses?: boolean;
}

/**
 * Check if a given object implements the TenantSettings interface.
 */
export function instanceOfTenantSettings(value: object): value is TenantSettings {
    if (!('uom' in value) || value['uom'] === undefined) return false;
    if (!('addresses' in value) || value['addresses'] === undefined) return false;
    if (!('emails' in value) || value['emails'] === undefined) return false;
    if (!('vat' in value) || value['vat'] === undefined) return false;
    return true;
}

export function TenantSettingsFromJSON(json: any): TenantSettings {
    return TenantSettingsFromJSONTyped(json, false);
}

export function TenantSettingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): TenantSettings {
    if (json == null) {
        return json;
    }
    return {
        
        'uom': json['uom'],
        'addresses': ((json['addresses'] as Array<any>).map(AddressAttrFromJSON)),
        'emails': ((json['emails'] as Array<any>).map(EmailAttrFromJSON)),
        'phones': json['phones'] == null ? undefined : ((json['phones'] as Array<any>).map(PhoneAttrFromJSON)),
        'website': json['website'] == null ? undefined : json['website'],
        'registeredCapital': json['registered_capital'] == null ? undefined : json['registered_capital'],
        'rea': json['rea'] == null ? undefined : json['rea'],
        'tradeRegister': json['trade_register'] == null ? undefined : json['trade_register'],
        'sdi': json['sdi'] == null ? undefined : json['sdi'],
        'pec': json['pec'] == null ? undefined : json['pec'],
        'vat': json['vat'],
        'preferredPaymentMethod': json['preferred_payment_method'] == null ? undefined : json['preferred_payment_method'],
        'isManufacturer': json['is_manufacturer'] == null ? undefined : json['is_manufacturer'],
        'isReseller': json['is_reseller'] == null ? undefined : json['is_reseller'],
        'isDirectToConsumer': json['is_direct_to_consumer'] == null ? undefined : json['is_direct_to_consumer'],
        'hasSalesAgents': json['has_sales_agents'] == null ? undefined : json['has_sales_agents'],
        'hasEcommerceSales': json['has_ecommerce_sales'] == null ? undefined : json['has_ecommerce_sales'],
        'hasDocumentSalesQuote': json['has_document_sales_quote'] == null ? undefined : json['has_document_sales_quote'],
        'hasDocumentSalesOffer': json['has_document_sales_offer'] == null ? undefined : json['has_document_sales_offer'],
        'hasDocumentSalesOrder': json['has_document_sales_order'] == null ? undefined : json['has_document_sales_order'],
        'hasDocumentPurchaseQuote': json['has_document_purchase_quote'] == null ? undefined : json['has_document_purchase_quote'],
        'hasDocumentPurchaseOrder': json['has_document_purchase_order'] == null ? undefined : json['has_document_purchase_order'],
        'hasSemi': json['has_semi'] == null ? undefined : json['has_semi'],
        'hasBundle': json['has_bundle'] == null ? undefined : json['has_bundle'],
        'monthlyAvailability': json['monthly_availability'] == null ? undefined : json['monthly_availability'],
        'trackSupplierWarehouses': json['track_supplier_warehouses'] == null ? undefined : json['track_supplier_warehouses'],
    };
}

export function TenantSettingsToJSON(json: any): TenantSettings {
    return TenantSettingsToJSONTyped(json, false);
}

export function TenantSettingsToJSONTyped(value?: TenantSettings | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'uom': value['uom'],
        'addresses': ((value['addresses'] as Array<any>).map(AddressAttrToJSON)),
        'emails': ((value['emails'] as Array<any>).map(EmailAttrToJSON)),
        'phones': value['phones'] == null ? undefined : ((value['phones'] as Array<any>).map(PhoneAttrToJSON)),
        'website': value['website'],
        'registered_capital': value['registeredCapital'],
        'rea': value['rea'],
        'trade_register': value['tradeRegister'],
        'sdi': value['sdi'],
        'pec': value['pec'],
        'vat': value['vat'],
        'preferred_payment_method': value['preferredPaymentMethod'],
        'is_manufacturer': value['isManufacturer'],
        'is_reseller': value['isReseller'],
        'is_direct_to_consumer': value['isDirectToConsumer'],
        'has_sales_agents': value['hasSalesAgents'],
        'has_ecommerce_sales': value['hasEcommerceSales'],
        'has_document_sales_quote': value['hasDocumentSalesQuote'],
        'has_document_sales_offer': value['hasDocumentSalesOffer'],
        'has_document_sales_order': value['hasDocumentSalesOrder'],
        'has_document_purchase_quote': value['hasDocumentPurchaseQuote'],
        'has_document_purchase_order': value['hasDocumentPurchaseOrder'],
        'has_semi': value['hasSemi'],
        'has_bundle': value['hasBundle'],
        'monthly_availability': value['monthlyAvailability'],
        'track_supplier_warehouses': value['trackSupplierWarehouses'],
    };
}

