/* tslint:disable */
/* eslint-disable */
/**
 * Arke IAM API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UpdateSettingsValueRequestValue } from './UpdateSettingsValueRequestValue';
import {
    UpdateSettingsValueRequestValueFromJSON,
    UpdateSettingsValueRequestValueFromJSONTyped,
    UpdateSettingsValueRequestValueToJSON,
    UpdateSettingsValueRequestValueToJSONTyped,
} from './UpdateSettingsValueRequestValue';

/**
 * 
 * @export
 * @interface UpdateSettingsValueRequest
 */
export interface UpdateSettingsValueRequest {
    /**
     * 
     * @type {UpdateSettingsValueRequestValue}
     * @memberof UpdateSettingsValueRequest
     */
    value: UpdateSettingsValueRequestValue;
}

/**
 * Check if a given object implements the UpdateSettingsValueRequest interface.
 */
export function instanceOfUpdateSettingsValueRequest(value: object): value is UpdateSettingsValueRequest {
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function UpdateSettingsValueRequestFromJSON(json: any): UpdateSettingsValueRequest {
    return UpdateSettingsValueRequestFromJSONTyped(json, false);
}

export function UpdateSettingsValueRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateSettingsValueRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'value': UpdateSettingsValueRequestValueFromJSON(json['value']),
    };
}

export function UpdateSettingsValueRequestToJSON(json: any): UpdateSettingsValueRequest {
    return UpdateSettingsValueRequestToJSONTyped(json, false);
}

export function UpdateSettingsValueRequestToJSONTyped(value?: UpdateSettingsValueRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'value': UpdateSettingsValueRequestValueToJSON(value['value']),
    };
}

