/* tslint:disable */
/* eslint-disable */
/**
 * Arke IAM API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AccessToken,
  ApiKeyDetails,
  CreateApiKeyRequest,
  ValidateApiKeyRequest,
} from '../models/index';
import {
    AccessTokenFromJSON,
    AccessTokenToJSON,
    ApiKeyDetailsFromJSON,
    ApiKeyDetailsToJSON,
    CreateApiKeyRequestFromJSON,
    CreateApiKeyRequestToJSON,
    ValidateApiKeyRequestFromJSON,
    ValidateApiKeyRequestToJSON,
} from '../models/index';

export interface CreateApiKeyOperationRequest {
    createApiKeyRequest: CreateApiKeyRequest;
}

export interface DeleteApiKeyRequest {
    apiKeyId: string;
}

export interface ShowApiKeyRequest {
    apiKeyId: string;
}

export interface UpdateApiKeyRequest {
    apiKeyId: string;
    apiKeyDetails?: ApiKeyDetails;
}

export interface ValidateApiKeyOperationRequest {
    validateApiKeyRequest: ValidateApiKeyRequest;
}

/**
 * 
 */
export class ApiKeysApi extends runtime.BaseAPI {

    /**
     */
    async createApiKeyRaw(requestParameters: CreateApiKeyOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiKeyDetails>> {
        if (requestParameters['createApiKeyRequest'] == null) {
            throw new runtime.RequiredError(
                'createApiKeyRequest',
                'Required parameter "createApiKeyRequest" was null or undefined when calling createApiKey().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api-key`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: CreateApiKeyRequestToJSON(requestParameters['createApiKeyRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiKeyDetailsFromJSON(jsonValue));
    }

    /**
     */
    async createApiKey(requestParameters: CreateApiKeyOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiKeyDetails> {
        const response = await this.createApiKeyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async deleteApiKeyRaw(requestParameters: DeleteApiKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['apiKeyId'] == null) {
            throw new runtime.RequiredError(
                'apiKeyId',
                'Required parameter "apiKeyId" was null or undefined when calling deleteApiKey().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api-key/{apiKeyId}`.replace(`{${"apiKeyId"}}`, encodeURIComponent(String(requestParameters['apiKeyId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async deleteApiKey(requestParameters: DeleteApiKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteApiKeyRaw(requestParameters, initOverrides);
    }

    /**
     */
    async listApiKeysRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ApiKeyDetails>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api-key`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ApiKeyDetailsFromJSON));
    }

    /**
     */
    async listApiKeys(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ApiKeyDetails>> {
        const response = await this.listApiKeysRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async showApiKeyRaw(requestParameters: ShowApiKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiKeyDetails>> {
        if (requestParameters['apiKeyId'] == null) {
            throw new runtime.RequiredError(
                'apiKeyId',
                'Required parameter "apiKeyId" was null or undefined when calling showApiKey().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api-key/{apiKeyId}`.replace(`{${"apiKeyId"}}`, encodeURIComponent(String(requestParameters['apiKeyId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiKeyDetailsFromJSON(jsonValue));
    }

    /**
     */
    async showApiKey(requestParameters: ShowApiKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiKeyDetails> {
        const response = await this.showApiKeyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async updateApiKeyRaw(requestParameters: UpdateApiKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiKeyDetails>> {
        if (requestParameters['apiKeyId'] == null) {
            throw new runtime.RequiredError(
                'apiKeyId',
                'Required parameter "apiKeyId" was null or undefined when calling updateApiKey().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api-key/{apiKeyId}`.replace(`{${"apiKeyId"}}`, encodeURIComponent(String(requestParameters['apiKeyId']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ApiKeyDetailsToJSON(requestParameters['apiKeyDetails']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiKeyDetailsFromJSON(jsonValue));
    }

    /**
     */
    async updateApiKey(requestParameters: UpdateApiKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiKeyDetails> {
        const response = await this.updateApiKeyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async validateApiKeyRaw(requestParameters: ValidateApiKeyOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccessToken>> {
        if (requestParameters['validateApiKeyRequest'] == null) {
            throw new runtime.RequiredError(
                'validateApiKeyRequest',
                'Required parameter "validateApiKeyRequest" was null or undefined when calling validateApiKey().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api-key/_validate`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ValidateApiKeyRequestToJSON(requestParameters['validateApiKeyRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccessTokenFromJSON(jsonValue));
    }

    /**
     */
    async validateApiKey(requestParameters: ValidateApiKeyOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccessToken> {
        const response = await this.validateApiKeyRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
