/* tslint:disable */
/* eslint-disable */
/**
 * Arke IAM API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { wait } from '$utils/wait';
import type {
    NotificationSummary,
} from '../models/index';
import * as runtime from '../runtime';

export interface AcknowledgeNotificationRequest {
    notificationId: string;
}

export interface ListNotificationsRequest {
    limit?: number;
    offset?: number;
    from?: number;
}

/**
 * 
 */
export class NotificationsApi extends runtime.BaseAPI {

    /**
     * marks a notification as acknowledged
     */
    async acknowledgeNotificationRaw(requestParameters: AcknowledgeNotificationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['notificationId'] == null) {
            throw new runtime.RequiredError(
                'notificationId',
                'Required parameter "notificationId" was null or undefined when calling acknowledgeNotification().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/notification/{notificationId}/_acknowledge`.replace(`{${"notificationId"}}`, encodeURIComponent(String(requestParameters['notificationId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * marks a notification as acknowledged
     */
    async acknowledgeNotification(requestParameters: AcknowledgeNotificationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.acknowledgeNotificationRaw(requestParameters, initOverrides);
    }

    /**
     * notifications for a user or role
     */
    async listNotifications(requestParameters: ListNotificationsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<NotificationSummary>> {
        await wait(Math.random() * 500)

        return [
            {
                "id": "0543b78e-6f47-436c-9431-8186ee39cf91",
                "type": "SUPPLY_TRANSPORT_DOCUMENT_ACCEPTED",
                "category": "purchase_orders_updates",
                "createdTs": 1764170726984,
                "metadata": {
                "id": "5953ea02-fdd2-447c-9760-e78a576ee4c7",
                "order_id": "3f883002-8711-49c9-bf3b-d57b2356f566"
                }
            },
            {
                "id": "86949bd9-5adf-45d9-b430-afc80d8564e1",
                "type": "PRODUCTION_STARTED",
                "category": "production_updates",
                "createdTs": 1763995464462,
                "metadata": {
                "id": "5078bb2c-c4b4-4a76-92be-54dd476b2e0a",
                "product_id": "a3a33a14-1501-45bb-a3f8-d628ecf783fb",
                "product_internal_id": "PROD-005",
                "product_name": "Rocket launcher",
                "quantity": 1,
                "uom": "unit"
                }
            },
            {
                "id": "6d236e77-d505-4b8d-b2be-016ee94bedc5",
                "type": "PRODUCTION_FINALIZED",
                "category": "production_updates",
                "createdTs": 1763993824130,
                "metadata": {
                "count": 1
                }
            },
            {
                "id": "2be7d885-e66a-4448-9a31-d25a05c5aeac",
                "type": "PRODUCTION_FINALIZED",
                "category": "production_updates",
                "createdTs": 1763993743063,
                "metadata": {
                "count": 1
                }
            },
            {
                "id": "f07c36c0-5911-4e65-822d-a139faf0ebf5",
                "type": "PRODUCTION_FINALIZED",
                "category": "production_updates",
                "createdTs": 1763986646329,
                "metadata": {
                "count": 1
                }
            },
            {
                "id": "c86aab9a-eca5-4702-806b-bcc33eaeb838",
                "type": "SALES_ORDER_ACCEPTED",
                "category": "sales_orders_updates",
                "createdTs": 1763393823145,
                "metadata": {
                "external_id": "SO-12398172",
                "id": "cdbde0e9-3680-4821-9797-1f9ab4a83132"
                }
            },
            {
                "id": "fb930a1e-c309-40b4-85fc-a1e899d8186e",
                "type": "SALES_ORDER_CREATED",
                "category": "sales_orders_updates",
                "createdTs": 1763393823145,
                "metadata": {
                "external_id": "SO-12398172",
                "id": "cdbde0e9-3680-4821-9797-1f9ab4a83132"
                }
            },
            {
                "id": "766d1620-174a-4a40-acff-ca24e49cd344",
                "type": "PRODUCTION_STARTED",
                "category": "production_updates",
                "createdTs": 1763339432157,
                "metadata": {
                "id": "33b8cc39-6751-4538-8275-b47d3fa644c3",
                "product_id": "5772f2f7-6851-4c83-bda0-07c04fff3752",
                "product_internal_id": "PROD-047",
                "product_name": "Astonishing kit",
                "quantity": 3,
                "uom": "unit"
                }
            },
            {
                "id": "9c02a07a-2393-4a93-9ff3-7c34c09d1119",
                "type": "PRODUCTION_FINALIZED",
                "category": "production_updates",
                "createdTs": 1763338046032,
                "metadata": {
                "count": 1
                }
            },
            {
                "id": "70357d37-9f52-4546-a2b2-0d2a38782750",
                "type": "PRODUCTION_STARTED",
                "category": "production_updates",
                "createdTs": 1763136961326,
                "metadata": {
                "id": "3af117e0-c341-42c3-9001-2265898fa5dd",
                "product_id": "0c580c07-6ed9-49d1-8513-2261dd1e50dc",
                "product_internal_id": "PROD-046",
                "product_name": "Amazing fluid",
                "quantity": 15,
                "uom": "liter"
                }
            },
            {
                "id": "efcfcb8e-6537-4642-a359-a7f5ff89b3bd",
                "type": "PRODUCTION_FINALIZED",
                "category": "production_updates",
                "createdTs": 1763135769424,
                "metadata": {
                "count": 1
                }
            },
            {
                "id": "6db107f2-2789-4809-bf5d-a84087c852dd",
                "type": "PRODUCTION_STARTED",
                "category": "production_updates",
                "createdTs": 1763135726956,
                "metadata": {
                "id": "79190dff-75fa-431b-aec9-c0c0d4b9f55c",
                "product_id": "5772f2f7-6851-4c83-bda0-07c04fff3752",
                "product_internal_id": "PROD-047",
                "product_name": "Astonishing kit",
                "quantity": 10,
                "uom": "unit"
                }
            },
            {
                "id": "4eed99a9-5667-4b74-bdd2-bb84d16b3c94",
                "type": "PRODUCTION_FINALIZED",
                "category": "production_updates",
                "createdTs": 1763135719653,
                "metadata": {
                "count": 1
                }
            },
            {
                "id": "c7a15ccc-3a3f-46f9-9b7c-8179b4ee7d95",
                "type": "PRODUCTION_STARTED",
                "category": "production_updates",
                "createdTs": 1763135237502,
                "metadata": {
                "id": "d847b1e4-6674-4ecd-a14f-4a546a56390e",
                "product_id": "3d055631-313a-4f5e-814d-3e70827116c0",
                "product_internal_id": "PROD-001",
                "product_name": "Scaffale in alluminio",
                "quantity": 1,
                "uom": "unit"
                },
            },
            {
                "id": "ec45cfcd-e854-4162-a373-212a703e749c",
                "type": "PRODUCTION_FINALIZED",
                "category": "production_updates",
                "createdTs": 1763135233881,
                "metadata": {
                "count": 1
                }
            },
            {
                "id": "2252d372-b94c-44f2-889e-f289300b7447",
                "type": "PRODUCTION_STARTED",
                "category": "production_updates",
                "createdTs": 1763112227251,
                "metadata": {
                "id": "b8797c6f-bf39-4b79-978e-c9fa59084f2a",
                "product_id": "3d055631-313a-4f5e-814d-3e70827116c0",
                "product_internal_id": "PROD-001",
                "product_name": "Scaffale in alluminio",
                "quantity": 5,
                "uom": "unit"
                }
            },
            {
                "id": "97a7d9ff-62fe-4a5c-ab63-290e04497f86",
                "type": "PRODUCTION_FINALIZED",
                "category": "production_updates",
                "createdTs": 1763112220770,
                "metadata": {
                "count": 1
                }
            },
            {
                "id": "65f6d6a1-e715-456d-bf97-828448698402",
                "type": "PRODUCTION_UPDATED",
                "category": "production_updates",
                "createdTs": 1763073002739,
                "metadata": {
                "id": "9be023fb-353a-4c70-a93d-08d867691e83",
                "produced_quantity": 5,
                "product_id": "3d055631-313a-4f5e-814d-3e70827116c0",
                "product_internal_id": "PROD-001",
                "product_name": "Scaffale in alluminio",
                "quantity": 5,
                "uom": "unit"
                }
            },
            {
                "id": "7b78a2e9-229b-4c94-8ccb-cd11f86eadbc",
                "type": "PRODUCTION_STARTED",
                "category": "production_updates",
                "createdTs": 1763072714348,
                "metadata": {
                "id": "f76335f2-2687-4512-b7c0-4cb57c55c37a",
                "product_id": "5772f2f7-6851-4c83-bda0-07c04fff3752",
                "product_internal_id": "PROD-047",
                "product_name": "Astonishing kit",
                "quantity": 5,
                "uom": "unit"
                }
            },
            {
                "id": "361af92d-e029-4ace-9cfa-91094c8e4d71",
                "type": "PRODUCTION_FINALIZED",
                "category": "production_updates",
                "createdTs": 1763072707965,
                "metadata": {
                "count": 1
                }
            },
            {
                "id": "47a41030-8056-4dfe-84d9-b708b52f3761",
                "type": "PRODUCTION_STARTED",
                "category": "production_updates",
                "createdTs": 1763072420720,
                "metadata": {
                "id": "9be023fb-353a-4c70-a93d-08d867691e83",
                "product_id": "3d055631-313a-4f5e-814d-3e70827116c0",
                "product_internal_id": "PROD-001",
                "product_name": "Scaffale in alluminio",
                "quantity": 5,
                "uom": "unit"
                },
            },
            {
                "id": "b8850d5e-26b8-47f7-8144-639417647b19",
                "type": "PRODUCTION_FINALIZED",
                "category": "production_updates",
                "createdTs": 1763072408677,
                "metadata": {
                "count": 1
                }
            },
            {
                "id": "db5b4c7a-e4b5-4b85-b4aa-99723532e2f0",
                "type": "PRODUCTION_STARTED",
                "category": "production_updates",
                "createdTs": 1763071867796,
                "metadata": {
                "id": "31097f3d-85f8-4dea-9b48-9e49b8e075b2",
                "product_id": "5772f2f7-6851-4c83-bda0-07c04fff3752",
                "product_internal_id": "PROD-047",
                "product_name": "Astonishing kit",
                "quantity": 10,
                "uom": "unit"
                }
            },
            {
                "id": "1caf452d-63c9-4420-9e84-bfb93eb32516",
                "type": "PRODUCTION_STARTED",
                "category": "production_updates",
                "createdTs": 1763050002069,
                "metadata": {
                "id": "450c0e9d-af54-4ac5-adb8-d7b4a7d9aa49",
                "product_id": "0c580c07-6ed9-49d1-8513-2261dd1e50dc",
                "product_internal_id": "PROD-046",
                "product_name": "Amazing fluid",
                "quantity": 5,
                "uom": "liter"
                }
            },
            {
                "id": "1882d17c-6421-4735-ae51-ab0ada9106b6",
                "type": "PRODUCTION_FINALIZED",
                "category": "production_updates",
                "createdTs": 1763049998143,
                "metadata": {
                "count": 1
                }
            },
            {
                "id": "a8ee819d-bbfd-4154-9e98-5dcbb528d4d0",
                "type": "PRODUCTION_UPDATED",
                "category": "production_updates",
                "createdTs": 1762969503829,
                "metadata": {
                "id": "693a2a28-2293-48bd-bb0d-e1f36577af14",
                "produced_quantity": 364,
                "product_id": "3d055631-313a-4f5e-814d-3e70827116c0",
                "product_internal_id": "PROD-001",
                "product_name": "Scaffale in alluminio",
                "quantity": 404,
                "uom": "unit"
                }
            },
            {
                "id": "6bc0c05b-789c-4637-831a-f03d9cd7d22d",
                "type": "PRODUCTION_FINALIZED",
                "category": "production_updates",
                "createdTs": 1762963638730,
                "metadata": {
                "count": 1
                }
            },
            {
                "id": "3d78555e-14bc-4f3f-af4a-cffda88061ac",
                "type": "PRODUCTION_STARTED",
                "category": "production_updates",
                "createdTs": 1762962255317,
                "metadata": {
                "id": "9bfae174-2a82-471a-9b9c-e05e1ba5204a",
                "product_id": "0c580c07-6ed9-49d1-8513-2261dd1e50dc",
                "product_internal_id": "PROD-046",
                "product_name": "Liquido fighissimo",
                "quantity": 3,
                "uom": "liter"
                }
            },
            {
                "id": "a3562b93-7823-4c1d-9342-db0d5b84a8d7",
                "type": "PRODUCTION_FINALIZED",
                "category": "production_updates",
                "createdTs": 1762962229933,
                "metadata": {
                "count": 1
                }
            },
            {
                "id": "33a25adc-d062-427e-a49d-1ecc972972d2",
                "type": "PRODUCTION_STARTED",
                "category": "production_updates",
                "createdTs": 1762961981703,
                "metadata": {
                "id": "95dee56c-6ccf-406d-943e-24c7eea6ed03",
                "product_id": "dafdbb69-de92-46c0-9a11-b65cd050046a",
                "product_internal_id": "PROD-041",
                "product_name": "Pane e salame",
                "quantity": 3,
                "uom": "unit"
                }
            },
            {
                "id": "6adc363a-bc39-4383-8163-5e9d2319cf64",
                "type": "PRODUCTION_FINALIZED",
                "category": "production_updates",
                "createdTs": 1762961921733,
                "metadata": {
                "count": 1
                }
            },
            {
                "id": "ab0276a1-9ef7-41e4-80ab-dee464b3d2fd",
                "type": "SALES_ORDER_SHIPPED",
                "category": "sales_orders_updates",
                "createdTs": 1762446768185,
                "metadata": {
                "id": "fe107e6d-24f6-4e08-a392-d2b4ea658dee",
                "order_id": "b23426ca-45e7-4b8c-9813-4c4862a82f46"
                }
            },
            {
                "id": "296538b1-4355-4b9e-a85d-50368146c52d",
                "type": "SALES_ORDER_ACCEPTED",
                "category": "sales_orders_updates",
                "createdTs": 1762446684455,
                "metadata": {
                "external_id": "",
                "id": "b23426ca-45e7-4b8c-9813-4c4862a82f46"
                }
            },
            {
                "id": "13dfc347-86b9-4933-bb85-659c84c7087f",
                "type": "SALES_ORDER_CREATED",
                "category": "sales_orders_updates",
                "createdTs": 1762446683115,
                "metadata": {
                "external_id": "",
                "id": "b23426ca-45e7-4b8c-9813-4c4862a82f46"
                }
            },
            {
                "id": "551d1c81-3274-44f7-933a-b1353805402d",
                "type": "SUPPLY_TRANSPORT_DOCUMENT_ACCEPTED",
                "category": "purchase_orders_updates",
                "createdTs": 1762446534002,
                "metadata": {
                "id": "f9f5bbb2-adaf-4544-ac13-f96a5908f20d",
                "order_id": "ea05a34a-0523-4617-903c-61cf84d0dcb7"
                }
            },
            {
                "id": "401b4704-dd44-4a3c-86a0-f1ceb785ba15",
                "type": "SUPPLY_TRANSPORT_DOCUMENT_CREATED",
                "category": "purchase_orders_updates",
                "createdTs": 1762446515414,
                "metadata": {
                "id": "f9f5bbb2-adaf-4544-ac13-f96a5908f20d",
                "order_id": "ea05a34a-0523-4617-903c-61cf84d0dcb7"
                }
            },
            {
                "id": "a59a7740-4df1-4fde-a6d9-ca3b18bad7e2",
                "type": "PURCHASE_ORDER_ACCEPTED",
                "category": "purchase_orders_updates",
                "createdTs": 1762446471569,
                "metadata": {
                "id": "ea05a34a-0523-4617-903c-61cf84d0dcb7"
                }
            },
            {
                "id": "7e42603c-caac-4fae-ba5b-e52377855d0e",
                "type": "PURCHASE_ORDER_SENT",
                "category": "purchase_orders_updates",
                "createdTs": 1762446467632,
                "metadata": {
                "id": "ea05a34a-0523-4617-903c-61cf84d0dcb7"
                }
            },
            {
                "id": "57967422-b1b9-4724-aef3-e47f5bde5358",
                "type": "PURCHASE_ORDER_CREATED",
                "category": "purchase_orders_updates",
                "createdTs": 1762446467199,
                "metadata": {
                "id": "ea05a34a-0523-4617-903c-61cf84d0dcb7"
                }
            },
            {
                "id": "8c4c86c0-7589-4371-ad8d-de1fc9f776dc",
                "type": "SUPPLY_TRANSPORT_DOCUMENT_ACCEPTED",
                "category": "purchase_orders_updates",
                "createdTs": 1762446353730,
                "metadata": {
                "id": "eb826481-08ee-4b86-ba89-d2a0e8d15187",
                "order_id": "580c60a1-3caa-4395-98d0-5b61cf0dbc6a"
                }
            },
            {
                "id": "32352f2d-a6a2-4b90-a82e-49e986b5e91d",
                "type": "SUPPLY_TRANSPORT_DOCUMENT_CREATED",
                "category": "purchase_orders_updates",
                "createdTs": 1762439744828,
                "metadata": {
                "id": "eb826481-08ee-4b86-ba89-d2a0e8d15187",
                "order_id": "580c60a1-3caa-4395-98d0-5b61cf0dbc6a"
                }
            },
            {
                "id": "6b1f6df9-ff91-47f3-a5c1-644c79a288ca",
                "type": "PURCHASE_ORDER_ACCEPTED",
                "category": "purchase_orders_updates",
                "createdTs": 1762439709592,
                "metadata": {
                "id": "580c60a1-3caa-4395-98d0-5b61cf0dbc6a"
                }
            },
            {
                "id": "f19bf274-05bd-4267-8ca2-076042d20eee",
                "type": "PURCHASE_ORDER_SENT",
                "category": "purchase_orders_updates",
                "createdTs": 1762439691319,
                "metadata": {
                "id": "580c60a1-3caa-4395-98d0-5b61cf0dbc6a"
                }
            },
            {
                "id": "8a6f4004-9577-473d-ac62-1ea29a46d1b3",
                "type": "PURCHASE_ORDER_CREATED",
                "category": "purchase_orders_updates",
                "createdTs": 1762439690953,
                "metadata": {
                "id": "580c60a1-3caa-4395-98d0-5b61cf0dbc6a"
                }
            },
            {
                "id": "662c45ea-f2b9-44d8-b9be-8839c6ebaeaa",
                "type": "SUPPLY_TRANSPORT_DOCUMENT_ACCEPTED",
                "category": "purchase_orders_updates",
                "createdTs": 1762439452776,
                "metadata": {
                "id": "fa60a048-1c01-4059-b4a6-f607af941ae1",
                "order_id": "340a45a1-54e2-411e-b22c-8ffebcaf1c75"
                }
            },
            {
                "id": "53abfea8-e3fe-4186-a796-79fd62d7f520",
                "type": "SUPPLY_TRANSPORT_DOCUMENT_CREATED",
                "category": "purchase_orders_updates",
                "createdTs": 1762439448997,
                "metadata": {
                "id": "fa60a048-1c01-4059-b4a6-f607af941ae1",
                "order_id": "340a45a1-54e2-411e-b22c-8ffebcaf1c75"
                }
            },
            {
                "id": "00d1a019-ffe7-4e3a-acaf-8f7b5e1f6087",
                "type": "PURCHASE_ORDER_ACCEPTED",
                "category": "purchase_orders_updates",
                "createdTs": 1762439385117,
                "metadata": {
                "id": "340a45a1-54e2-411e-b22c-8ffebcaf1c75"
                }
            },
            {
                "id": "3d0bbf84-2a3e-4b8d-99d5-b2363655d57b",
                "type": "PRODUCTION_UPDATED",
                "category": "production_updates",
                "createdTs": 1762439247331,
                "metadata": {
                "id": "693a2a28-2293-48bd-bb0d-e1f36577af14",
                "produced_quantity": 30,
                "product_id": "3d055631-313a-4f5e-814d-3e70827116c0",
                "product_internal_id": "PROD-001",
                "product_name": "Scaffale in alluminio",
                "quantity": 404,
                "uom": "unit"
                }
            },
            {
                "id": "eba9d260-1187-42c1-a562-a587c2918c77",
                "type": "PRODUCTION_UPDATED",
                "category": "production_updates",
                "createdTs": 1762439206184,
                "metadata": {
                "id": "693a2a28-2293-48bd-bb0d-e1f36577af14",
                "produced_quantity": 10,
                "product_id": "3d055631-313a-4f5e-814d-3e70827116c0",
                "product_internal_id": "PROD-001",
                "product_name": "Scaffale in alluminio",
                "quantity": 404,
                "uom": "unit"
                }
            },
            {
                "id": "23e985d3-4ab8-4daf-ae28-6f5351dd51cd",
                "type": "PURCHASE_ORDER_SENT",
                "category": "purchase_orders_updates",
                "createdTs": 1762426710035,
                "metadata": {
                "id": "340a45a1-54e2-411e-b22c-8ffebcaf1c75"
                }
            }
        ]
    }

}
