/* tslint:disable */
/* eslint-disable */
/**
 * Arke IAM API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  SettingsDetails,
  SettingsUpdate,
} from '../models/index';
import {
    SettingsDetailsFromJSON,
    SettingsDetailsToJSON,
    SettingsUpdateFromJSON,
    SettingsUpdateToJSON,
} from '../models/index';

export interface CreateSettingsRequest {
    settingsDetails?: SettingsDetails;
}

export interface ShowSettingsRequest {
    key: string;
    xApiKey: string;
}

export interface UpdateSettingsValueRequest {
    key: string;
    settingsUpdate?: SettingsUpdate;
}

/**
 * 
 */
export class SettingsApi extends runtime.BaseAPI {

    /**
     */
    async createSettingsRaw(requestParameters: CreateSettingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SettingsDetails>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/system/settings`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: SettingsDetailsToJSON(requestParameters['settingsDetails']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SettingsDetailsFromJSON(jsonValue));
    }

    /**
     */
    async createSettings(requestParameters: CreateSettingsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SettingsDetails> {
        const response = await this.createSettingsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async listSettingsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SettingsDetails>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/system/settings`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SettingsDetailsFromJSON));
    }

    /**
     */
    async listSettings(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SettingsDetails>> {
        const response = await this.listSettingsRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async showSettingsRaw(requestParameters: ShowSettingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SettingsDetails>> {
        if (requestParameters['key'] == null) {
            throw new runtime.RequiredError(
                'key',
                'Required parameter "key" was null or undefined when calling showSettings().'
            );
        }

        if (requestParameters['xApiKey'] == null) {
            throw new runtime.RequiredError(
                'xApiKey',
                'Required parameter "xApiKey" was null or undefined when calling showSettings().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xApiKey'] != null) {
            headerParameters['x-api-key'] = String(requestParameters['xApiKey']);
        }

        const response = await this.request({
            path: `/system/settings/{key}`.replace(`{${"key"}}`, encodeURIComponent(String(requestParameters['key']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SettingsDetailsFromJSON(jsonValue));
    }

    /**
     */
    async showSettings(requestParameters: ShowSettingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SettingsDetails> {
        const response = await this.showSettingsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async updateSettingsValueRaw(requestParameters: UpdateSettingsValueRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SettingsDetails>> {
        if (requestParameters['key'] == null) {
            throw new runtime.RequiredError(
                'key',
                'Required parameter "key" was null or undefined when calling updateSettingsValue().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/system/settings/{key}/_update-value`.replace(`{${"key"}}`, encodeURIComponent(String(requestParameters['key']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SettingsUpdateToJSON(requestParameters['settingsUpdate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SettingsDetailsFromJSON(jsonValue));
    }

    /**
     */
    async updateSettingsValue(requestParameters: UpdateSettingsValueRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SettingsDetails> {
        const response = await this.updateSettingsValueRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
