/* tslint:disable */
/* eslint-disable */
/**
 * Arke Product API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ActiveOrderProduct } from './ActiveOrderProduct';
import {
    ActiveOrderProductFromJSON,
    ActiveOrderProductFromJSONTyped,
    ActiveOrderProductToJSON,
    ActiveOrderProductToJSONTyped,
} from './ActiveOrderProduct';
import type { GenericAttr } from './GenericAttr';
import {
    GenericAttrFromJSON,
    GenericAttrFromJSONTyped,
    GenericAttrToJSON,
    GenericAttrToJSONTyped,
} from './GenericAttr';
import type { CompanyAttr } from './CompanyAttr';
import {
    CompanyAttrFromJSON,
    CompanyAttrFromJSONTyped,
    CompanyAttrToJSON,
    CompanyAttrToJSONTyped,
} from './CompanyAttr';

/**
 * 
 * @export
 * @interface ActiveOrder
 */
export interface ActiveOrder {
    /**
     * 
     * @type {string}
     * @memberof ActiveOrder
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ActiveOrder
     */
    internalId?: string;
    /**
     * 
     * @type {string}
     * @memberof ActiveOrder
     */
    externalId?: string;
    /**
     * 
     * @type {Date}
     * @memberof ActiveOrder
     */
    time?: Date;
    /**
     * 
     * @type {number}
     * @memberof ActiveOrder
     */
    priority?: number;
    /**
     * 
     * @type {string}
     * @memberof ActiveOrder
     */
    status: ActiveOrderStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof ActiveOrder
     */
    defaultCurrency?: string;
    /**
     * 
     * @type {number}
     * @memberof ActiveOrder
     */
    totalVatIncl: number;
    /**
     * 
     * @type {Date}
     * @memberof ActiveOrder
     */
    expectedShippingTime: Date;
    /**
     * 
     * @type {CompanyAttr}
     * @memberof ActiveOrder
     */
    customerAttr?: CompanyAttr;
    /**
     * 
     * @type {string}
     * @memberof ActiveOrder
     */
    shipped?: ActiveOrderShippedEnum;
    /**
     * 
     * @type {GenericAttr}
     * @memberof ActiveOrder
     */
    salesChannelAttr?: GenericAttr;
    /**
     * 
     * @type {Array<ActiveOrderProduct>}
     * @memberof ActiveOrder
     */
    products: Array<ActiveOrderProduct>;
}


/**
 * @export
 */
export const ActiveOrderStatusEnum = {
    Draft: 'draft',
    Accepted: 'accepted',
    Sent: 'sent'
} as const;
export type ActiveOrderStatusEnum = typeof ActiveOrderStatusEnum[keyof typeof ActiveOrderStatusEnum];

/**
 * @export
 */
export const ActiveOrderShippedEnum = {
    Completed: 'completed',
    NotShipped: 'not shipped',
    Partial: 'partial'
} as const;
export type ActiveOrderShippedEnum = typeof ActiveOrderShippedEnum[keyof typeof ActiveOrderShippedEnum];


/**
 * Check if a given object implements the ActiveOrder interface.
 */
export function instanceOfActiveOrder(value: object): value is ActiveOrder {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('totalVatIncl' in value) || value['totalVatIncl'] === undefined) return false;
    if (!('expectedShippingTime' in value) || value['expectedShippingTime'] === undefined) return false;
    if (!('products' in value) || value['products'] === undefined) return false;
    return true;
}

export function ActiveOrderFromJSON(json: any): ActiveOrder {
    return ActiveOrderFromJSONTyped(json, false);
}

export function ActiveOrderFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActiveOrder {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'internalId': json['internal_id'] == null ? undefined : json['internal_id'],
        'externalId': json['external_id'] == null ? undefined : json['external_id'],
        'time': json['time'] == null ? undefined : (new Date(json['time'])),
        'priority': json['priority'] == null ? undefined : json['priority'],
        'status': json['status'],
        'defaultCurrency': json['default_currency'] == null ? undefined : json['default_currency'],
        'totalVatIncl': json['total_vat_incl'],
        'expectedShippingTime': (new Date(json['expected_shipping_time'])),
        'customerAttr': json['customer_attr'] == null ? undefined : CompanyAttrFromJSON(json['customer_attr']),
        'shipped': json['shipped'] == null ? undefined : json['shipped'],
        'salesChannelAttr': json['sales_channel_attr'] == null ? undefined : GenericAttrFromJSON(json['sales_channel_attr']),
        'products': ((json['products'] as Array<any>).map(ActiveOrderProductFromJSON)),
    };
}

export function ActiveOrderToJSON(json: any): ActiveOrder {
    return ActiveOrderToJSONTyped(json, false);
}

export function ActiveOrderToJSONTyped(value?: ActiveOrder | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'internal_id': value['internalId'],
        'external_id': value['externalId'],
        'time': value['time'] == null ? undefined : ((value['time']).toISOString()),
        'priority': value['priority'],
        'status': value['status'],
        'default_currency': value['defaultCurrency'],
        'total_vat_incl': value['totalVatIncl'],
        'expected_shipping_time': ((value['expectedShippingTime']).toISOString()),
        'customer_attr': CompanyAttrToJSON(value['customerAttr']),
        'shipped': value['shipped'],
        'sales_channel_attr': GenericAttrToJSON(value['salesChannelAttr']),
        'products': ((value['products'] as Array<any>).map(ActiveOrderProductToJSON)),
    };
}

