/* tslint:disable */
/* eslint-disable */
/**
 * Arke Product API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AffiliationCustomer } from './AffiliationCustomer';
import {
    AffiliationCustomerFromJSON,
    AffiliationCustomerFromJSONTyped,
    AffiliationCustomerToJSON,
    AffiliationCustomerToJSONTyped,
} from './AffiliationCustomer';

/**
 * 
 * @export
 * @interface Affiliation
 */
export interface Affiliation {
    /**
     * 
     * @type {string}
     * @memberof Affiliation
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Affiliation
     */
    customerId?: string;
    /**
     * 
     * @type {string}
     * @memberof Affiliation
     */
    affiliateId?: string;
    /**
     * 
     * @type {AffiliationCustomer}
     * @memberof Affiliation
     */
    customer?: AffiliationCustomer;
    /**
     * 
     * @type {AffiliationCustomer}
     * @memberof Affiliation
     */
    affiliate?: AffiliationCustomer;
}

/**
 * Check if a given object implements the Affiliation interface.
 */
export function instanceOfAffiliation(value: object): value is Affiliation {
    return true;
}

export function AffiliationFromJSON(json: any): Affiliation {
    return AffiliationFromJSONTyped(json, false);
}

export function AffiliationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Affiliation {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'customerId': json['customer_id'] == null ? undefined : json['customer_id'],
        'affiliateId': json['affiliate_id'] == null ? undefined : json['affiliate_id'],
        'customer': json['customer'] == null ? undefined : AffiliationCustomerFromJSON(json['customer']),
        'affiliate': json['affiliate'] == null ? undefined : AffiliationCustomerFromJSON(json['affiliate']),
    };
}

export function AffiliationToJSON(json: any): Affiliation {
    return AffiliationToJSONTyped(json, false);
}

export function AffiliationToJSONTyped(value?: Affiliation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'customer_id': value['customerId'],
        'affiliate_id': value['affiliateId'],
        'customer': AffiliationCustomerToJSON(value['customer']),
        'affiliate': AffiliationCustomerToJSON(value['affiliate']),
    };
}

