/* tslint:disable */
/* eslint-disable */
/**
 * Arke Product API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EmailAttr } from './EmailAttr';
import {
    EmailAttrFromJSON,
    EmailAttrFromJSONTyped,
    EmailAttrToJSON,
    EmailAttrToJSONTyped,
} from './EmailAttr';
import type { PhoneAttr } from './PhoneAttr';
import {
    PhoneAttrFromJSON,
    PhoneAttrFromJSONTyped,
    PhoneAttrToJSON,
    PhoneAttrToJSONTyped,
} from './PhoneAttr';

/**
 * 
 * @export
 * @interface CustomerSummary
 */
export interface CustomerSummary {
    /**
     * 
     * @type {string}
     * @memberof CustomerSummary
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerSummary
     */
    name: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CustomerSummary
     */
    categories: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof CustomerSummary
     */
    vatNo: string;
    /**
     * 
     * @type {Array<PhoneAttr>}
     * @memberof CustomerSummary
     */
    phones: Array<PhoneAttr>;
    /**
     * 
     * @type {string}
     * @memberof CustomerSummary
     */
    defaultCurrency: string;
    /**
     * 
     * @type {Array<EmailAttr>}
     * @memberof CustomerSummary
     */
    emails: Array<EmailAttr>;
}

/**
 * Check if a given object implements the CustomerSummary interface.
 */
export function instanceOfCustomerSummary(value: object): value is CustomerSummary {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('categories' in value) || value['categories'] === undefined) return false;
    if (!('vatNo' in value) || value['vatNo'] === undefined) return false;
    if (!('phones' in value) || value['phones'] === undefined) return false;
    if (!('defaultCurrency' in value) || value['defaultCurrency'] === undefined) return false;
    if (!('emails' in value) || value['emails'] === undefined) return false;
    return true;
}

export function CustomerSummaryFromJSON(json: any): CustomerSummary {
    return CustomerSummaryFromJSONTyped(json, false);
}

export function CustomerSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
        'categories': json['categories'],
        'vatNo': json['vat_no'],
        'phones': ((json['phones'] as Array<any>).map(PhoneAttrFromJSON)),
        'defaultCurrency': json['default_currency'],
        'emails': ((json['emails'] as Array<any>).map(EmailAttrFromJSON)),
    };
}

export function CustomerSummaryToJSON(json: any): CustomerSummary {
    return CustomerSummaryToJSONTyped(json, false);
}

export function CustomerSummaryToJSONTyped(value?: CustomerSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'categories': value['categories'],
        'vat_no': value['vatNo'],
        'phones': ((value['phones'] as Array<any>).map(PhoneAttrToJSON)),
        'default_currency': value['defaultCurrency'],
        'emails': ((value['emails'] as Array<any>).map(EmailAttrToJSON)),
    };
}

