/* tslint:disable */
/* eslint-disable */
/**
 * Arke Product API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CustomFilterAttr } from './CustomFilterAttr';
import {
    CustomFilterAttrFromJSON,
    CustomFilterAttrFromJSONTyped,
    CustomFilterAttrToJSON,
    CustomFilterAttrToJSONTyped,
} from './CustomFilterAttr';

/**
 * 
 * @export
 * @interface CustomFieldDefinitionAttr
 */
export interface CustomFieldDefinitionAttr {
    /**
     * 
     * @type {string}
     * @memberof CustomFieldDefinitionAttr
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CustomFieldDefinitionAttr
     */
    label: string;
    /**
     * 
     * @type {string}
     * @memberof CustomFieldDefinitionAttr
     */
    type: string;
    /**
     * 
     * @type {number}
     * @memberof CustomFieldDefinitionAttr
     */
    index: number;
    /**
     * 
     * @type {Array<CustomFilterAttr>}
     * @memberof CustomFieldDefinitionAttr
     */
    filters?: Array<CustomFilterAttr>;
}

/**
 * Check if a given object implements the CustomFieldDefinitionAttr interface.
 */
export function instanceOfCustomFieldDefinitionAttr(value: object): value is CustomFieldDefinitionAttr {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('label' in value) || value['label'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('index' in value) || value['index'] === undefined) return false;
    return true;
}

export function CustomFieldDefinitionAttrFromJSON(json: any): CustomFieldDefinitionAttr {
    return CustomFieldDefinitionAttrFromJSONTyped(json, false);
}

export function CustomFieldDefinitionAttrFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomFieldDefinitionAttr {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'label': json['label'],
        'type': json['type'],
        'index': json['index'],
        'filters': json['filters'] == null ? undefined : ((json['filters'] as Array<any>).map(CustomFilterAttrFromJSON)),
    };
}

export function CustomFieldDefinitionAttrToJSON(json: any): CustomFieldDefinitionAttr {
    return CustomFieldDefinitionAttrToJSONTyped(json, false);
}

export function CustomFieldDefinitionAttrToJSONTyped(value?: CustomFieldDefinitionAttr | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'label': value['label'],
        'type': value['type'],
        'index': value['index'],
        'filters': value['filters'] == null ? undefined : ((value['filters'] as Array<any>).map(CustomFilterAttrToJSON)),
    };
}

