/* tslint:disable */
/* eslint-disable */
/**
 * Arke Product API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ForecastItem
 */
export interface ForecastItem {
    /**
     * 
     * @type {string}
     * @memberof ForecastItem
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ForecastItem
     */
    extraId: string;
    /**
     * 
     * @type {string}
     * @memberof ForecastItem
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof ForecastItem
     */
    quantity: number;
    /**
     * 
     * @type {string}
     * @memberof ForecastItem
     */
    uom: string;
    /**
     * 
     * @type {Date}
     * @memberof ForecastItem
     */
    startsAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ForecastItem
     */
    endsAt?: Date;
}

/**
 * Check if a given object implements the ForecastItem interface.
 */
export function instanceOfForecastItem(value: object): value is ForecastItem {
    if (!('extraId' in value) || value['extraId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    if (!('uom' in value) || value['uom'] === undefined) return false;
    return true;
}

export function ForecastItemFromJSON(json: any): ForecastItem {
    return ForecastItemFromJSONTyped(json, false);
}

export function ForecastItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): ForecastItem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'extraId': json['extra_id'],
        'name': json['name'],
        'quantity': json['quantity'],
        'uom': json['uom'],
        'startsAt': json['starts_at'] == null ? undefined : (new Date(json['starts_at'])),
        'endsAt': json['ends_at'] == null ? undefined : (new Date(json['ends_at'])),
    };
}

export function ForecastItemToJSON(json: any): ForecastItem {
    return ForecastItemToJSONTyped(json, false);
}

export function ForecastItemToJSONTyped(value?: ForecastItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'extra_id': value['extraId'],
        'name': value['name'],
        'quantity': value['quantity'],
        'uom': value['uom'],
        'starts_at': value['startsAt'] == null ? undefined : ((value['startsAt']).toISOString()),
        'ends_at': value['endsAt'] == null ? undefined : ((value['endsAt']).toISOString()),
    };
}

