/* tslint:disable */
/* eslint-disable */
/**
 * Arke Product API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface QuantifiedItem
 */
export interface QuantifiedItem {
    /**
     * 
     * @type {string}
     * @memberof QuantifiedItem
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof QuantifiedItem
     */
    extraId: string;
    /**
     * 
     * @type {string}
     * @memberof QuantifiedItem
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof QuantifiedItem
     */
    quantity: number;
    /**
     * 
     * @type {string}
     * @memberof QuantifiedItem
     */
    uom: string;
    /**
     * 
     * @type {string}
     * @memberof QuantifiedItem
     */
    itemId?: string;
    /**
     * 
     * @type {string}
     * @memberof QuantifiedItem
     */
    lot?: string;
    /**
     * 
     * @type {string}
     * @memberof QuantifiedItem
     */
    orderId?: string;
}

/**
 * Check if a given object implements the QuantifiedItem interface.
 */
export function instanceOfQuantifiedItem(value: object): value is QuantifiedItem {
    if (!('extraId' in value) || value['extraId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    if (!('uom' in value) || value['uom'] === undefined) return false;
    return true;
}

export function QuantifiedItemFromJSON(json: any): QuantifiedItem {
    return QuantifiedItemFromJSONTyped(json, false);
}

export function QuantifiedItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): QuantifiedItem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'extraId': json['extra_id'],
        'name': json['name'],
        'quantity': json['quantity'],
        'uom': json['uom'],
        'itemId': json['item_id'] == null ? undefined : json['item_id'],
        'lot': json['lot'] == null ? undefined : json['lot'],
        'orderId': json['order_id'] == null ? undefined : json['order_id'],
    };
}

export function QuantifiedItemToJSON(json: any): QuantifiedItem {
    return QuantifiedItemToJSONTyped(json, false);
}

export function QuantifiedItemToJSONTyped(value?: QuantifiedItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'extra_id': value['extraId'],
        'name': value['name'],
        'quantity': value['quantity'],
        'uom': value['uom'],
        'item_id': value['itemId'],
        'lot': value['lot'],
        'order_id': value['orderId'],
    };
}

