/* tslint:disable */
/* eslint-disable */
/**
 * Arke Product API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DateAttr } from './DateAttr';
import {
    DateAttrFromJSON,
    DateAttrFromJSONTyped,
    DateAttrToJSON,
    DateAttrToJSONTyped,
} from './DateAttr';
import type { CustomFormValues } from './CustomFormValues';
import {
    CustomFormValuesFromJSON,
    CustomFormValuesFromJSONTyped,
    CustomFormValuesToJSON,
    CustomFormValuesToJSONTyped,
} from './CustomFormValues';
import type { QuantifiedItem } from './QuantifiedItem';
import {
    QuantifiedItemFromJSON,
    QuantifiedItemFromJSONTyped,
    QuantifiedItemToJSON,
    QuantifiedItemToJSONTyped,
} from './QuantifiedItem';
import type { OrderDetails } from './OrderDetails';
import {
    OrderDetailsFromJSON,
    OrderDetailsFromJSONTyped,
    OrderDetailsToJSON,
    OrderDetailsToJSONTyped,
} from './OrderDetails';
import type { WarehouseAttr } from './WarehouseAttr';
import {
    WarehouseAttrFromJSON,
    WarehouseAttrFromJSONTyped,
    WarehouseAttrToJSON,
    WarehouseAttrToJSONTyped,
} from './WarehouseAttr';

/**
 * 
 * @export
 * @interface TransportDocumentDetails
 */
export interface TransportDocumentDetails {
    /**
     * 
     * @type {DateAttr}
     * @memberof TransportDocumentDetails
     */
    created?: DateAttr;
    /**
     * 
     * @type {DateAttr}
     * @memberof TransportDocumentDetails
     */
    updated?: DateAttr;
    /**
     * 
     * @type {number}
     * @memberof TransportDocumentDetails
     */
    version: number;
    /**
     * 
     * @type {boolean}
     * @memberof TransportDocumentDetails
     */
    archived?: boolean;
    /**
     * 
     * @type {string}
     * @memberof TransportDocumentDetails
     */
    notes?: string;
    /**
     * 
     * @type {CustomFormValues}
     * @memberof TransportDocumentDetails
     */
    customFormValues?: CustomFormValues;
    /**
     * 
     * @type {object}
     * @memberof TransportDocumentDetails
     */
    foreignIds?: object;
    /**
     * 
     * @type {string}
     * @memberof TransportDocumentDetails
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof TransportDocumentDetails
     */
    internalId?: string;
    /**
     * 
     * @type {string}
     * @memberof TransportDocumentDetails
     */
    status: TransportDocumentDetailsStatusEnum;
    /**
     * 
     * @type {Date}
     * @memberof TransportDocumentDetails
     */
    time?: Date;
    /**
     * 
     * @type {string}
     * @memberof TransportDocumentDetails
     */
    orderInternalId: string;
    /**
     * 
     * @type {string}
     * @memberof TransportDocumentDetails
     */
    orderId: string;
    /**
     * 
     * @type {WarehouseAttr}
     * @memberof TransportDocumentDetails
     */
    warehouseAttr?: WarehouseAttr;
    /**
     * 
     * @type {string}
     * @memberof TransportDocumentDetails
     */
    warehouseId?: string;
    /**
     * 
     * @type {number}
     * @memberof TransportDocumentDetails
     */
    weight?: number;
    /**
     * 
     * @type {Array<QuantifiedItem>}
     * @memberof TransportDocumentDetails
     */
    products: Array<QuantifiedItem>;
    /**
     * 
     * @type {string}
     * @memberof TransportDocumentDetails
     */
    shippingAddress: string;
    /**
     * 
     * @type {OrderDetails}
     * @memberof TransportDocumentDetails
     */
    order?: OrderDetails;
    /**
     * 
     * @type {string}
     * @memberof TransportDocumentDetails
     */
    carrier?: string;
    /**
     * 
     * @type {string}
     * @memberof TransportDocumentDetails
     */
    reason?: string;
}


/**
 * @export
 */
export const TransportDocumentDetailsStatusEnum = {
    Draft: 'draft',
    Accepted: 'accepted',
    Sent: 'sent'
} as const;
export type TransportDocumentDetailsStatusEnum = typeof TransportDocumentDetailsStatusEnum[keyof typeof TransportDocumentDetailsStatusEnum];


/**
 * Check if a given object implements the TransportDocumentDetails interface.
 */
export function instanceOfTransportDocumentDetails(value: object): value is TransportDocumentDetails {
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('orderInternalId' in value) || value['orderInternalId'] === undefined) return false;
    if (!('orderId' in value) || value['orderId'] === undefined) return false;
    if (!('products' in value) || value['products'] === undefined) return false;
    if (!('shippingAddress' in value) || value['shippingAddress'] === undefined) return false;
    return true;
}

export function TransportDocumentDetailsFromJSON(json: any): TransportDocumentDetails {
    return TransportDocumentDetailsFromJSONTyped(json, false);
}

export function TransportDocumentDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransportDocumentDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'created': json['created'] == null ? undefined : DateAttrFromJSON(json['created']),
        'updated': json['updated'] == null ? undefined : DateAttrFromJSON(json['updated']),
        'version': json['version'],
        'archived': json['archived'] == null ? undefined : json['archived'],
        'notes': json['notes'] == null ? undefined : json['notes'],
        'customFormValues': json['custom_form_values'] == null ? undefined : CustomFormValuesFromJSON(json['custom_form_values']),
        'foreignIds': json['foreign_ids'] == null ? undefined : json['foreign_ids'],
        'id': json['id'] == null ? undefined : json['id'],
        'internalId': json['internal_id'] == null ? undefined : json['internal_id'],
        'status': json['status'],
        'time': json['time'] == null ? undefined : (new Date(json['time'])),
        'orderInternalId': json['order_internal_id'],
        'orderId': json['order_id'],
        'warehouseAttr': json['warehouse_attr'] == null ? undefined : WarehouseAttrFromJSON(json['warehouse_attr']),
        'warehouseId': json['warehouse_id'] == null ? undefined : json['warehouse_id'],
        'weight': json['weight'] == null ? undefined : json['weight'],
        'products': ((json['products'] as Array<any>).map(QuantifiedItemFromJSON)),
        'shippingAddress': json['shipping_address'],
        'order': json['order'] == null ? undefined : OrderDetailsFromJSON(json['order']),
        'carrier': json['carrier'] == null ? undefined : json['carrier'],
        'reason': json['reason'] == null ? undefined : json['reason'],
    };
}

export function TransportDocumentDetailsToJSON(json: any): TransportDocumentDetails {
    return TransportDocumentDetailsToJSONTyped(json, false);
}

export function TransportDocumentDetailsToJSONTyped(value?: TransportDocumentDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created': DateAttrToJSON(value['created']),
        'updated': DateAttrToJSON(value['updated']),
        'version': value['version'],
        'archived': value['archived'],
        'notes': value['notes'],
        'custom_form_values': CustomFormValuesToJSON(value['customFormValues']),
        'foreign_ids': value['foreignIds'],
        'id': value['id'],
        'internal_id': value['internalId'],
        'status': value['status'],
        'time': value['time'] == null ? undefined : ((value['time']).toISOString()),
        'order_internal_id': value['orderInternalId'],
        'order_id': value['orderId'],
        'warehouse_attr': WarehouseAttrToJSON(value['warehouseAttr']),
        'warehouse_id': value['warehouseId'],
        'weight': value['weight'],
        'products': ((value['products'] as Array<any>).map(QuantifiedItemToJSON)),
        'shipping_address': value['shippingAddress'],
        'order': OrderDetailsToJSON(value['order']),
        'carrier': value['carrier'],
        'reason': value['reason'],
    };
}

