/* tslint:disable */
/* eslint-disable */
/**
 * Arke Analytics API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HistoryItem } from './HistoryItem';
import {
    HistoryItemFromJSON,
    HistoryItemFromJSONTyped,
    HistoryItemToJSON,
    HistoryItemToJSONTyped,
} from './HistoryItem';

/**
 * 
 * @export
 * @interface AgentQuestion
 */
export interface AgentQuestion {
    /**
     * The question to ask the agent
     * @type {string}
     * @memberof AgentQuestion
     */
    ask: string;
    /**
     * The model for the agent to use
     * @type {string}
     * @memberof AgentQuestion
     */
    model?: AgentQuestionModelEnum;
    /**
     * The conversation history for the agent
     * @type {Array<HistoryItem>}
     * @memberof AgentQuestion
     */
    history: Array<HistoryItem>;
}


/**
 * @export
 */
export const AgentQuestionModelEnum = {
    Gemini20Flash: 'gemini-2.0-flash'
} as const;
export type AgentQuestionModelEnum = typeof AgentQuestionModelEnum[keyof typeof AgentQuestionModelEnum];


/**
 * Check if a given object implements the AgentQuestion interface.
 */
export function instanceOfAgentQuestion(value: object): value is AgentQuestion {
    if (!('ask' in value) || value['ask'] === undefined) return false;
    if (!('history' in value) || value['history'] === undefined) return false;
    return true;
}

export function AgentQuestionFromJSON(json: any): AgentQuestion {
    return AgentQuestionFromJSONTyped(json, false);
}

export function AgentQuestionFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgentQuestion {
    if (json == null) {
        return json;
    }
    return {
        
        'ask': json['ask'],
        'model': json['model'] == null ? undefined : json['model'],
        'history': ((json['history'] as Array<any>).map(HistoryItemFromJSON)),
    };
}

export function AgentQuestionToJSON(json: any): AgentQuestion {
    return AgentQuestionToJSONTyped(json, false);
}

export function AgentQuestionToJSONTyped(value?: AgentQuestion | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ask': value['ask'],
        'model': value['model'],
        'history': ((value['history'] as Array<any>).map(HistoryItemToJSON)),
    };
}

