/* tslint:disable */
/* eslint-disable */
/**
 * Arke Analytics API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HistoryItem } from './HistoryItem';
import {
    HistoryItemFromJSON,
    HistoryItemFromJSONTyped,
    HistoryItemToJSON,
    HistoryItemToJSONTyped,
} from './HistoryItem';

/**
 * 
 * @export
 * @interface AgentAnswer
 */
export interface AgentAnswer {
    /**
     * The agent's response
     * @type {string}
     * @memberof AgentAnswer
     */
    answer: string;
    /**
     * The updated conversation history
     * @type {Array<HistoryItem>}
     * @memberof AgentAnswer
     */
    history: Array<HistoryItem>;
    /**
     * 
     * @type {boolean}
     * @memberof AgentAnswer
     */
    isIntent: boolean;
    /**
     * An object containing error details, if any
     * @type {object}
     * @memberof AgentAnswer
     */
    error?: object;
}

/**
 * Check if a given object implements the AgentAnswer interface.
 */
export function instanceOfAgentAnswer(value: object): value is AgentAnswer {
    if (!('answer' in value) || value['answer'] === undefined) return false;
    if (!('history' in value) || value['history'] === undefined) return false;
    if (!('isIntent' in value) || value['isIntent'] === undefined) return false;
    return true;
}

export function AgentAnswerFromJSON(json: any): AgentAnswer {
    return AgentAnswerFromJSONTyped(json, false);
}

export function AgentAnswerFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgentAnswer {
    if (json == null) {
        return json;
    }
    return {
        
        'answer': json['answer'],
        'history': ((json['history'] as Array<any>).map(HistoryItemFromJSON)),
        'isIntent': json['is_intent'],
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function AgentAnswerToJSON(json: any): AgentAnswer {
    return AgentAnswerToJSONTyped(json, false);
}

export function AgentAnswerToJSONTyped(value?: AgentAnswer | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'answer': value['answer'],
        'history': ((value['history'] as Array<any>).map(HistoryItemToJSON)),
        'is_intent': value['isIntent'],
        'error': value['error'],
    };
}

