/* tslint:disable */
/* eslint-disable */
/**
 * Arke Analytics API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DbQuestion
 */
export interface DbQuestion {
    /**
     * 
     * @type {string}
     * @memberof DbQuestion
     */
    ask: string;
    /**
     * 
     * @type {string}
     * @memberof DbQuestion
     */
    model?: DbQuestionModelEnum;
}


/**
 * @export
 */
export const DbQuestionModelEnum = {
    Gemini20Flash: 'gemini-2.0-flash'
} as const;
export type DbQuestionModelEnum = typeof DbQuestionModelEnum[keyof typeof DbQuestionModelEnum];


/**
 * Check if a given object implements the DbQuestion interface.
 */
export function instanceOfDbQuestion(value: object): value is DbQuestion {
    if (!('ask' in value) || value['ask'] === undefined) return false;
    return true;
}

export function DbQuestionFromJSON(json: any): DbQuestion {
    return DbQuestionFromJSONTyped(json, false);
}

export function DbQuestionFromJSONTyped(json: any, ignoreDiscriminator: boolean): DbQuestion {
    if (json == null) {
        return json;
    }
    return {
        
        'ask': json['ask'],
        'model': json['model'] == null ? undefined : json['model'],
    };
}

export function DbQuestionToJSON(json: any): DbQuestion {
    return DbQuestionToJSONTyped(json, false);
}

export function DbQuestionToJSONTyped(value?: DbQuestion | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ask': value['ask'],
        'model': value['model'],
    };
}

