/* tslint:disable */
/* eslint-disable */
/**
 * Document Extraction API
 * API for extracting text and entities from documents using Google Document AI
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConversionResponse
 */
export interface ConversionResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ConversionResponse
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ConversionResponse
     */
    message?: string;
    /**
     * 
     * @type {Date}
     * @memberof ConversionResponse
     */
    receivedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof ConversionResponse
     */
    originalFilename?: string;
    /**
     * 
     * @type {number}
     * @memberof ConversionResponse
     */
    originalSize?: number;
    /**
     * 
     * @type {string}
     * @memberof ConversionResponse
     */
    originalSizeFormatted?: string;
    /**
     * 
     * @type {number}
     * @memberof ConversionResponse
     */
    pdfSize?: number;
    /**
     * 
     * @type {string}
     * @memberof ConversionResponse
     */
    pdfSizeFormatted?: string;
    /**
     * Base64 encoded PDF content
     * @type {string}
     * @memberof ConversionResponse
     */
    pdf?: string;
}

/**
 * Check if a given object implements the ConversionResponse interface.
 */
export function instanceOfConversionResponse(value: object): value is ConversionResponse {
    return true;
}

export function ConversionResponseFromJSON(json: any): ConversionResponse {
    return ConversionResponseFromJSONTyped(json, false);
}

export function ConversionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConversionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'message': json['message'] == null ? undefined : json['message'],
        'receivedAt': json['receivedAt'] == null ? undefined : (new Date(json['receivedAt'])),
        'originalFilename': json['originalFilename'] == null ? undefined : json['originalFilename'],
        'originalSize': json['originalSize'] == null ? undefined : json['originalSize'],
        'originalSizeFormatted': json['originalSizeFormatted'] == null ? undefined : json['originalSizeFormatted'],
        'pdfSize': json['pdfSize'] == null ? undefined : json['pdfSize'],
        'pdfSizeFormatted': json['pdfSizeFormatted'] == null ? undefined : json['pdfSizeFormatted'],
        'pdf': json['pdf'] == null ? undefined : json['pdf'],
    };
}

export function ConversionResponseToJSON(json: any): ConversionResponse {
    return ConversionResponseToJSONTyped(json, false);
}

export function ConversionResponseToJSONTyped(value?: ConversionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
        'receivedAt': value['receivedAt'] == null ? undefined : ((value['receivedAt']).toISOString()),
        'originalFilename': value['originalFilename'],
        'originalSize': value['originalSize'],
        'originalSizeFormatted': value['originalSizeFormatted'],
        'pdfSize': value['pdfSize'],
        'pdfSizeFormatted': value['pdfSizeFormatted'],
        'pdf': value['pdf'],
    };
}

