/* tslint:disable */
/* eslint-disable */
/**
 * Document Extraction API
 * API for extracting text and entities from documents using Google Document AI
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DocumentEntity
 */
export interface DocumentEntity {
    /**
     * 
     * @type {string}
     * @memberof DocumentEntity
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentEntity
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentEntity
     */
    mentionText?: string;
    /**
     * 
     * @type {number}
     * @memberof DocumentEntity
     */
    confidence?: number;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof DocumentEntity
     */
    properties?: { [key: string]: any; };
}

/**
 * Check if a given object implements the DocumentEntity interface.
 */
export function instanceOfDocumentEntity(value: object): value is DocumentEntity {
    return true;
}

export function DocumentEntityFromJSON(json: any): DocumentEntity {
    return DocumentEntityFromJSONTyped(json, false);
}

export function DocumentEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentEntity {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'id': json['id'] == null ? undefined : json['id'],
        'mentionText': json['mentionText'] == null ? undefined : json['mentionText'],
        'confidence': json['confidence'] == null ? undefined : json['confidence'],
        'properties': json['properties'] == null ? undefined : json['properties'],
    };
}

export function DocumentEntityToJSON(json: any): DocumentEntity {
    return DocumentEntityToJSONTyped(json, false);
}

export function DocumentEntityToJSONTyped(value?: DocumentEntity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'id': value['id'],
        'mentionText': value['mentionText'],
        'confidence': value['confidence'],
        'properties': value['properties'],
    };
}

