/* tslint:disable */
/* eslint-disable */
/**
 * Document Extraction API
 * API for extracting text and entities from documents using Google Document AI
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExSchemaBaseMetadataAnnotations } from './ExSchemaBaseMetadataAnnotations';
import {
    ExSchemaBaseMetadataAnnotationsFromJSON,
    ExSchemaBaseMetadataAnnotationsFromJSONTyped,
    ExSchemaBaseMetadataAnnotationsToJSON,
    ExSchemaBaseMetadataAnnotationsToJSONTyped,
} from './ExSchemaBaseMetadataAnnotations';

/**
 * 
 * @export
 * @interface ExSchemaBaseMetadata
 */
export interface ExSchemaBaseMetadata {
    /**
     * 
     * @type {string}
     * @memberof ExSchemaBaseMetadata
     */
    uid?: string;
    /**
     * 
     * @type {string}
     * @memberof ExSchemaBaseMetadata
     */
    creationTimestamp?: string;
    /**
     * 
     * @type {ExSchemaBaseMetadataAnnotations}
     * @memberof ExSchemaBaseMetadata
     */
    annotations?: ExSchemaBaseMetadataAnnotations;
}

/**
 * Check if a given object implements the ExSchemaBaseMetadata interface.
 */
export function instanceOfExSchemaBaseMetadata(value: object): value is ExSchemaBaseMetadata {
    return true;
}

export function ExSchemaBaseMetadataFromJSON(json: any): ExSchemaBaseMetadata {
    return ExSchemaBaseMetadataFromJSONTyped(json, false);
}

export function ExSchemaBaseMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExSchemaBaseMetadata {
    if (json == null) {
        return json;
    }
    return {
        
        'uid': json['uid'] == null ? undefined : json['uid'],
        'creationTimestamp': json['creationTimestamp'] == null ? undefined : json['creationTimestamp'],
        'annotations': json['annotations'] == null ? undefined : ExSchemaBaseMetadataAnnotationsFromJSON(json['annotations']),
    };
}

export function ExSchemaBaseMetadataToJSON(json: any): ExSchemaBaseMetadata {
    return ExSchemaBaseMetadataToJSONTyped(json, false);
}

export function ExSchemaBaseMetadataToJSONTyped(value?: ExSchemaBaseMetadata | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'uid': value['uid'],
        'creationTimestamp': value['creationTimestamp'],
        'annotations': ExSchemaBaseMetadataAnnotationsToJSON(value['annotations']),
    };
}

