/* tslint:disable */
/* eslint-disable */
/**
 * Document Extraction API
 * API for extracting text and entities from documents using Google Document AI
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DocumentExtractionType } from './DocumentExtractionType';
import {
    DocumentExtractionTypeFromJSON,
    DocumentExtractionTypeFromJSONTyped,
    DocumentExtractionTypeToJSON,
    DocumentExtractionTypeToJSONTyped,
} from './DocumentExtractionType';

/**
 * 
 * @export
 * @interface ExtractionRequest
 */
export interface ExtractionRequest {
    /**
     * Base64 encoded content of the document
     * @type {string}
     * @memberof ExtractionRequest
     */
    content: string;
    /**
     * Name of the file
     * @type {string}
     * @memberof ExtractionRequest
     */
    filename?: string;
    /**
     * MIME type of the document
     * @type {string}
     * @memberof ExtractionRequest
     */
    mimeType?: ExtractionRequestMimeTypeEnum;
    /**
     * 
     * @type {DocumentExtractionType}
     * @memberof ExtractionRequest
     */
    documentType?: DocumentExtractionType;
    /**
     * Additional options for extraction
     * @type {object}
     * @memberof ExtractionRequest
     */
    options?: object;
}


/**
 * @export
 */
export const ExtractionRequestMimeTypeEnum = {
    ApplicationPdf: 'application/pdf',
    TextPlain: 'text/plain'
} as const;
export type ExtractionRequestMimeTypeEnum = typeof ExtractionRequestMimeTypeEnum[keyof typeof ExtractionRequestMimeTypeEnum];


/**
 * Check if a given object implements the ExtractionRequest interface.
 */
export function instanceOfExtractionRequest(value: object): value is ExtractionRequest {
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function ExtractionRequestFromJSON(json: any): ExtractionRequest {
    return ExtractionRequestFromJSONTyped(json, false);
}

export function ExtractionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExtractionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'],
        'filename': json['filename'] == null ? undefined : json['filename'],
        'mimeType': json['mimeType'] == null ? undefined : json['mimeType'],
        'documentType': json['documentType'] == null ? undefined : DocumentExtractionTypeFromJSON(json['documentType']),
        'options': json['options'] == null ? undefined : json['options'],
    };
}

export function ExtractionRequestToJSON(json: any): ExtractionRequest {
    return ExtractionRequestToJSONTyped(json, false);
}

export function ExtractionRequestToJSONTyped(value?: ExtractionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'],
        'filename': value['filename'],
        'mimeType': value['mimeType'],
        'documentType': DocumentExtractionTypeToJSON(value['documentType']),
        'options': value['options'],
    };
}

