/* tslint:disable */
/* eslint-disable */
/**
 * Document Extraction API
 * API for extracting text and entities from documents using Google Document AI
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BomExSpecAttrColor } from './BomExSpecAttrColor';
import {
    BomExSpecAttrColorFromJSON,
    BomExSpecAttrColorFromJSONTyped,
    BomExSpecAttrColorToJSON,
    BomExSpecAttrColorToJSONTyped,
} from './BomExSpecAttrColor';

/**
 * 
 * @export
 * @interface ExtractedRawMaterial
 */
export interface ExtractedRawMaterial {
    /**
     * 
     * @type {string}
     * @memberof ExtractedRawMaterial
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof ExtractedRawMaterial
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof ExtractedRawMaterial
     */
    quantity?: number;
    /**
     * 
     * @type {string}
     * @memberof ExtractedRawMaterial
     */
    uom?: string;
    /**
     * 
     * @type {BomExSpecAttrColor}
     * @memberof ExtractedRawMaterial
     */
    attrColor?: BomExSpecAttrColor;
    /**
     * 
     * @type {string}
     * @memberof ExtractedRawMaterial
     */
    attrSize?: string;
}

/**
 * Check if a given object implements the ExtractedRawMaterial interface.
 */
export function instanceOfExtractedRawMaterial(value: object): value is ExtractedRawMaterial {
    return true;
}

export function ExtractedRawMaterialFromJSON(json: any): ExtractedRawMaterial {
    return ExtractedRawMaterialFromJSONTyped(json, false);
}

export function ExtractedRawMaterialFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExtractedRawMaterial {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'name': json['name'] == null ? undefined : json['name'],
        'quantity': json['quantity'] == null ? undefined : json['quantity'],
        'uom': json['uom'] == null ? undefined : json['uom'],
        'attrColor': json['attrColor'] == null ? undefined : BomExSpecAttrColorFromJSON(json['attrColor']),
        'attrSize': json['attrSize'] == null ? undefined : json['attrSize'],
    };
}

export function ExtractedRawMaterialToJSON(json: any): ExtractedRawMaterial {
    return ExtractedRawMaterialToJSONTyped(json, false);
}

export function ExtractedRawMaterialToJSONTyped(value?: ExtractedRawMaterial | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'name': value['name'],
        'quantity': value['quantity'],
        'uom': value['uom'],
        'attrColor': BomExSpecAttrColorToJSON(value['attrColor']),
        'attrSize': value['attrSize'],
    };
}

