/* tslint:disable */
/* eslint-disable */
/**
 * Document Extraction API
 * API for extracting text and entities from documents using Google Document AI
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TextToPdfRequest
 */
export interface TextToPdfRequest {
    /**
     * Base64 encoded content of the text document
     * @type {string}
     * @memberof TextToPdfRequest
     */
    content: string;
    /**
     * Name of the file
     * @type {string}
     * @memberof TextToPdfRequest
     */
    filename?: string;
    /**
     * MIME type of the content
     * @type {string}
     * @memberof TextToPdfRequest
     */
    contentType?: string;
    /**
     * Additional conversion options
     * @type {object}
     * @memberof TextToPdfRequest
     */
    options?: object;
}

/**
 * Check if a given object implements the TextToPdfRequest interface.
 */
export function instanceOfTextToPdfRequest(value: object): value is TextToPdfRequest {
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function TextToPdfRequestFromJSON(json: any): TextToPdfRequest {
    return TextToPdfRequestFromJSONTyped(json, false);
}

export function TextToPdfRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TextToPdfRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'],
        'filename': json['filename'] == null ? undefined : json['filename'],
        'contentType': json['contentType'] == null ? undefined : json['contentType'],
        'options': json['options'] == null ? undefined : json['options'],
    };
}

export function TextToPdfRequestToJSON(json: any): TextToPdfRequest {
    return TextToPdfRequestToJSONTyped(json, false);
}

export function TextToPdfRequestToJSONTyped(value?: TextToPdfRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'],
        'filename': value['filename'],
        'contentType': value['contentType'],
        'options': value['options'],
    };
}

