/* tslint:disable */
/* eslint-disable */
/**
 * Arke Product API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ProductInventoryEventSummary,
} from '../models/index';
import {
    ProductInventoryEventSummaryFromJSON,
    ProductInventoryEventSummaryToJSON,
} from '../models/index';

export interface ListProductInventoryEventsRequest {
    limit?: number;
    offset?: number;
    search?: string;
}

/**
 * 
 */
export class InventoryApi extends runtime.BaseAPI {

    /**
     * lists the inventory events
     */
    async listProductInventoryEventsRaw(requestParameters: ListProductInventoryEventsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ProductInventoryEventSummary>>> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/inventory/product/event`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ProductInventoryEventSummaryFromJSON));
    }

    /**
     * lists the inventory events
     */
    async listProductInventoryEvents(requestParameters: ListProductInventoryEventsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ProductInventoryEventSummary>> {
        const response = await this.listProductInventoryEventsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
