/* tslint:disable */
/* eslint-disable */
/**
 * Arke Product API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ItemPhaseCompletionRequest,
  ProductionItemPhaseDetails,
  ProductionItemPhaseSummary,
} from '../models/index';
import {
    ItemPhaseCompletionRequestFromJSON,
    ItemPhaseCompletionRequestToJSON,
    ProductionItemPhaseDetailsFromJSON,
    ProductionItemPhaseDetailsToJSON,
    ProductionItemPhaseSummaryFromJSON,
    ProductionItemPhaseSummaryToJSON,
} from '../models/index';

export interface CompleteProductionPhaseRequest {
    itemPhaseId: string;
    itemPhaseCompletionRequest?: ItemPhaseCompletionRequest;
}

export interface ListItemPhasesRequest {
    phaseId: string;
}

export interface ShowProductionItemPhaseRequest {
    itemPhaseId: string;
}

export interface StartProductionPhaseRequest {
    itemPhaseId: string;
}

/**
 * 
 */
export class ProductionItemPhaseApi extends runtime.BaseAPI {

    /**
     */
    async completeProductionPhaseRaw(requestParameters: CompleteProductionPhaseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProductionItemPhaseDetails>> {
        if (requestParameters['itemPhaseId'] == null) {
            throw new runtime.RequiredError(
                'itemPhaseId',
                'Required parameter "itemPhaseId" was null or undefined when calling completeProductionPhase().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/production-item-phase/{itemPhaseId}/_complete`.replace(`{${"itemPhaseId"}}`, encodeURIComponent(String(requestParameters['itemPhaseId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ItemPhaseCompletionRequestToJSON(requestParameters['itemPhaseCompletionRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProductionItemPhaseDetailsFromJSON(jsonValue));
    }

    /**
     */
    async completeProductionPhase(requestParameters: CompleteProductionPhaseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProductionItemPhaseDetails> {
        const response = await this.completeProductionPhaseRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async listItemPhasesRaw(requestParameters: ListItemPhasesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ProductionItemPhaseSummary>>> {
        if (requestParameters['phaseId'] == null) {
            throw new runtime.RequiredError(
                'phaseId',
                'Required parameter "phaseId" was null or undefined when calling listItemPhases().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/production-phase/{phaseId}/item-phase`.replace(`{${"phaseId"}}`, encodeURIComponent(String(requestParameters['phaseId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ProductionItemPhaseSummaryFromJSON));
    }

    /**
     */
    async listItemPhases(requestParameters: ListItemPhasesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ProductionItemPhaseSummary>> {
        const response = await this.listItemPhasesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async showProductionItemPhaseRaw(requestParameters: ShowProductionItemPhaseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProductionItemPhaseDetails>> {
        if (requestParameters['itemPhaseId'] == null) {
            throw new runtime.RequiredError(
                'itemPhaseId',
                'Required parameter "itemPhaseId" was null or undefined when calling showProductionItemPhase().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/production-item-phase/{itemPhaseId}`.replace(`{${"itemPhaseId"}}`, encodeURIComponent(String(requestParameters['itemPhaseId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProductionItemPhaseDetailsFromJSON(jsonValue));
    }

    /**
     */
    async showProductionItemPhase(requestParameters: ShowProductionItemPhaseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProductionItemPhaseDetails> {
        const response = await this.showProductionItemPhaseRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async startProductionPhaseRaw(requestParameters: StartProductionPhaseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProductionItemPhaseDetails>> {
        if (requestParameters['itemPhaseId'] == null) {
            throw new runtime.RequiredError(
                'itemPhaseId',
                'Required parameter "itemPhaseId" was null or undefined when calling startProductionPhase().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/production-item-phase/{itemPhaseId}/_start`.replace(`{${"itemPhaseId"}}`, encodeURIComponent(String(requestParameters['itemPhaseId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProductionItemPhaseDetailsFromJSON(jsonValue));
    }

    /**
     */
    async startProductionPhase(requestParameters: StartProductionPhaseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProductionItemPhaseDetails> {
        const response = await this.startProductionPhaseRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
