/* tslint:disable */
/* eslint-disable */
/**
 * Arke Analytics API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AgentAnswer,
  AgentQuestion,
  DbAnswer,
  DbQuestion,
} from '../models/index';
import {
    AgentAnswerFromJSON,
    AgentAnswerToJSON,
    AgentQuestionFromJSON,
    AgentQuestionToJSON,
    DbAnswerFromJSON,
    DbAnswerToJSON,
    DbQuestionFromJSON,
    DbQuestionToJSON,
} from '../models/index';

export interface AgentAskRequest {
    agentQuestion?: AgentQuestion;
}

export interface DbAskRequest {
    dbQuestion?: DbQuestion;
}

export interface DbReplayRequest {
    dbQuestion?: DbQuestion;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     */
    async agentAskRaw(requestParameters: AgentAskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AgentAnswer>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/analytics/agent/_ask`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AgentQuestionToJSON(requestParameters['agentQuestion']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AgentAnswerFromJSON(jsonValue));
    }

    /**
     */
    async agentAsk(requestParameters: AgentAskRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AgentAnswer> {
        const response = await this.agentAskRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async dbAskRaw(requestParameters: DbAskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DbAnswer>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/analytics/database/_ask`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DbQuestionToJSON(requestParameters['dbQuestion']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DbAnswerFromJSON(jsonValue));
    }

    /**
     */
    async dbAsk(requestParameters: DbAskRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DbAnswer> {
        const response = await this.dbAskRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async dbReplayRaw(requestParameters: DbReplayRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DbAnswer>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/analytics/database/_replay`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DbQuestionToJSON(requestParameters['dbQuestion']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DbAnswerFromJSON(jsonValue));
    }

    /**
     */
    async dbReplay(requestParameters: DbReplayRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DbAnswer> {
        const response = await this.dbReplayRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
