/* tslint:disable */
/* eslint-disable */
/**
 * Arke Integrations API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelApiResponse
 */
export interface ModelApiResponse {
    /**
     * 
     * @type {string}
     * @memberof ModelApiResponse
     */
    arkeId?: string;
    /**
     * 
     * @type {object}
     * @memberof ModelApiResponse
     */
    attributes?: object;
    /**
     * 
     * @type {string}
     * @memberof ModelApiResponse
     */
    error?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelApiResponse
     */
    status: ModelApiResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof ModelApiResponse
     */
    resourceType?: string;
}


/**
 * @export
 */
export const ModelApiResponseStatusEnum = {
    Ok: 'ok',
    Queued: 'queued',
    Error: 'error'
} as const;
export type ModelApiResponseStatusEnum = typeof ModelApiResponseStatusEnum[keyof typeof ModelApiResponseStatusEnum];


/**
 * Check if a given object implements the ModelApiResponse interface.
 */
export function instanceOfModelApiResponse(value: object): value is ModelApiResponse {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function ModelApiResponseFromJSON(json: any): ModelApiResponse {
    return ModelApiResponseFromJSONTyped(json, false);
}

export function ModelApiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelApiResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'arkeId': json['arke_id'] == null ? undefined : json['arke_id'],
        'attributes': json['attributes'] == null ? undefined : json['attributes'],
        'error': json['error'] == null ? undefined : json['error'],
        'status': json['status'],
        'resourceType': json['resource_type'] == null ? undefined : json['resource_type'],
    };
}

export function ModelApiResponseToJSON(json: any): ModelApiResponse {
    return ModelApiResponseToJSONTyped(json, false);
}

export function ModelApiResponseToJSONTyped(value?: ModelApiResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'arke_id': value['arkeId'],
        'attributes': value['attributes'],
        'error': value['error'],
        'status': value['status'],
        'resource_type': value['resourceType'],
    };
}

