/* tslint:disable */
/* eslint-disable */
/**
 * Arke Integrations API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CustomerSimple } from './CustomerSimple';
import {
    CustomerSimpleFromJSON,
    CustomerSimpleFromJSONTyped,
    CustomerSimpleToJSON,
    CustomerSimpleToJSONTyped,
} from './CustomerSimple';
import type { ProductWithQuantity } from './ProductWithQuantity';
import {
    ProductWithQuantityFromJSON,
    ProductWithQuantityFromJSONTyped,
    ProductWithQuantityToJSON,
    ProductWithQuantityToJSONTyped,
} from './ProductWithQuantity';
import type { OrderSimpleShippingAddress } from './OrderSimpleShippingAddress';
import {
    OrderSimpleShippingAddressFromJSON,
    OrderSimpleShippingAddressFromJSONTyped,
    OrderSimpleShippingAddressToJSON,
    OrderSimpleShippingAddressToJSONTyped,
} from './OrderSimpleShippingAddress';

/**
 * 
 * @export
 * @interface OrderSimple
 */
export interface OrderSimple {
    /**
     * 
     * @type {string}
     * @memberof OrderSimple
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof OrderSimple
     */
    createdAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof OrderSimple
     */
    contactEmail?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderSimple
     */
    currency: OrderSimpleCurrencyEnum;
    /**
     * 
     * @type {string}
     * @memberof OrderSimple
     */
    email?: string;
    /**
     * 
     * @type {number}
     * @memberof OrderSimple
     */
    orderNumber?: number;
    /**
     * 
     * @type {OrderSimpleShippingAddress}
     * @memberof OrderSimple
     */
    shippingAddress: OrderSimpleShippingAddress;
    /**
     * 
     * @type {OrderSimpleShippingAddress}
     * @memberof OrderSimple
     */
    billingAddress?: OrderSimpleShippingAddress;
    /**
     * 
     * @type {number}
     * @memberof OrderSimple
     */
    total: number;
    /**
     * 
     * @type {Array<ProductWithQuantity>}
     * @memberof OrderSimple
     */
    products: Array<ProductWithQuantity>;
    /**
     * 
     * @type {CustomerSimple}
     * @memberof OrderSimple
     */
    customer: CustomerSimple;
    /**
     * 
     * @type {string}
     * @memberof OrderSimple
     */
    salesChannelId?: string;
}


/**
 * @export
 */
export const OrderSimpleCurrencyEnum = {
    Eur: 'EUR',
    Usd: 'USD',
    Gbp: 'GBP'
} as const;
export type OrderSimpleCurrencyEnum = typeof OrderSimpleCurrencyEnum[keyof typeof OrderSimpleCurrencyEnum];


/**
 * Check if a given object implements the OrderSimple interface.
 */
export function instanceOfOrderSimple(value: object): value is OrderSimple {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('shippingAddress' in value) || value['shippingAddress'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('products' in value) || value['products'] === undefined) return false;
    if (!('customer' in value) || value['customer'] === undefined) return false;
    return true;
}

export function OrderSimpleFromJSON(json: any): OrderSimple {
    return OrderSimpleFromJSONTyped(json, false);
}

export function OrderSimpleFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderSimple {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'contactEmail': json['contact_email'] == null ? undefined : json['contact_email'],
        'currency': json['currency'],
        'email': json['email'] == null ? undefined : json['email'],
        'orderNumber': json['order_number'] == null ? undefined : json['order_number'],
        'shippingAddress': OrderSimpleShippingAddressFromJSON(json['shipping_address']),
        'billingAddress': json['billing_address'] == null ? undefined : OrderSimpleShippingAddressFromJSON(json['billing_address']),
        'total': json['total'],
        'products': ((json['products'] as Array<any>).map(ProductWithQuantityFromJSON)),
        'customer': CustomerSimpleFromJSON(json['customer']),
        'salesChannelId': json['sales_channel_id'] == null ? undefined : json['sales_channel_id'],
    };
}

export function OrderSimpleToJSON(json: any): OrderSimple {
    return OrderSimpleToJSONTyped(json, false);
}

export function OrderSimpleToJSONTyped(value?: OrderSimple | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'created_at': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'contact_email': value['contactEmail'],
        'currency': value['currency'],
        'email': value['email'],
        'order_number': value['orderNumber'],
        'shipping_address': OrderSimpleShippingAddressToJSON(value['shippingAddress']),
        'billing_address': OrderSimpleShippingAddressToJSON(value['billingAddress']),
        'total': value['total'],
        'products': ((value['products'] as Array<any>).map(ProductWithQuantityToJSON)),
        'customer': CustomerSimpleToJSON(value['customer']),
        'sales_channel_id': value['salesChannelId'],
    };
}

