/* tslint:disable */
/* eslint-disable */
/**
 * Arke Integrations API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProductWithQuantity
 */
export interface ProductWithQuantity {
    /**
     * 
     * @type {string}
     * @memberof ProductWithQuantity
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ProductWithQuantity
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof ProductWithQuantity
     */
    price: number;
    /**
     * 
     * @type {string}
     * @memberof ProductWithQuantity
     */
    currency?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductWithQuantity
     */
    description?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ProductWithQuantity
     */
    categories?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof ProductWithQuantity
     */
    quantity: number;
}

/**
 * Check if a given object implements the ProductWithQuantity interface.
 */
export function instanceOfProductWithQuantity(value: object): value is ProductWithQuantity {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    return true;
}

export function ProductWithQuantityFromJSON(json: any): ProductWithQuantity {
    return ProductWithQuantityFromJSONTyped(json, false);
}

export function ProductWithQuantityFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductWithQuantity {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'price': json['price'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'description': json['description'] == null ? undefined : json['description'],
        'categories': json['categories'] == null ? undefined : json['categories'],
        'quantity': json['quantity'],
    };
}

export function ProductWithQuantityToJSON(json: any): ProductWithQuantity {
    return ProductWithQuantityToJSONTyped(json, false);
}

export function ProductWithQuantityToJSONTyped(value?: ProductWithQuantity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'price': value['price'],
        'currency': value['currency'],
        'description': value['description'],
        'categories': value['categories'],
        'quantity': value['quantity'],
    };
}

