/* tslint:disable */
/* eslint-disable */
/**
 * Arke Product API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  TransportDocumentDetails,
  TransportDocumentSummary,
} from '../models/index';
import {
    TransportDocumentDetailsFromJSON,
    TransportDocumentDetailsToJSON,
    TransportDocumentSummaryFromJSON,
    TransportDocumentSummaryToJSON,
} from '../models/index';

export interface CreateTransportDocumentRequest {
    transportDocumentDetails?: TransportDocumentDetails;
}

/**
 * 
 */
export class TransportDocumentsApi extends runtime.BaseAPI {

    /**
     * creates a transport document
     */
    async createTransportDocumentRaw(requestParameters: CreateTransportDocumentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransportDocumentSummary>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/transport-document`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: TransportDocumentDetailsToJSON(requestParameters['transportDocumentDetails']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransportDocumentSummaryFromJSON(jsonValue));
    }

    /**
     * creates a transport document
     */
    async createTransportDocument(requestParameters: CreateTransportDocumentRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransportDocumentSummary> {
        const response = await this.createTransportDocumentRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
