/* tslint:disable */
/* eslint-disable */
/**
 * Arke Product API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MissingProductBuckets
 */
export interface MissingProductBuckets {
    /**
     * 
     * @type {number}
     * @memberof MissingProductBuckets
     */
    planned: number;
    /**
     * 
     * @type {number}
     * @memberof MissingProductBuckets
     */
    inProduction: number;
    /**
     * 
     * @type {number}
     * @memberof MissingProductBuckets
     */
    available: number;
    /**
     * 
     * @type {number}
     * @memberof MissingProductBuckets
     */
    reserved: number;
    /**
     * 
     * @type {number}
     * @memberof MissingProductBuckets
     */
    shipped: number;
    /**
     * 
     * @type {number}
     * @memberof MissingProductBuckets
     */
    needed: number;
    /**
     * 
     * @type {number}
     * @memberof MissingProductBuckets
     */
    missing: number;
}

/**
 * Check if a given object implements the MissingProductBuckets interface.
 */
export function instanceOfMissingProductBuckets(value: object): value is MissingProductBuckets {
    if (!('planned' in value) || value['planned'] === undefined) return false;
    if (!('inProduction' in value) || value['inProduction'] === undefined) return false;
    if (!('available' in value) || value['available'] === undefined) return false;
    if (!('reserved' in value) || value['reserved'] === undefined) return false;
    if (!('shipped' in value) || value['shipped'] === undefined) return false;
    if (!('needed' in value) || value['needed'] === undefined) return false;
    if (!('missing' in value) || value['missing'] === undefined) return false;
    return true;
}

export function MissingProductBucketsFromJSON(json: any): MissingProductBuckets {
    return MissingProductBucketsFromJSONTyped(json, false);
}

export function MissingProductBucketsFromJSONTyped(json: any, ignoreDiscriminator: boolean): MissingProductBuckets {
    if (json == null) {
        return json;
    }
    return {
        
        'planned': json['planned'],
        'inProduction': json['in_production'],
        'available': json['available'],
        'reserved': json['reserved'],
        'shipped': json['shipped'],
        'needed': json['needed'],
        'missing': json['missing'],
    };
}

export function MissingProductBucketsToJSON(json: any): MissingProductBuckets {
    return MissingProductBucketsToJSONTyped(json, false);
}

export function MissingProductBucketsToJSONTyped(value?: MissingProductBuckets | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'planned': value['planned'],
        'in_production': value['inProduction'],
        'available': value['available'],
        'reserved': value['reserved'],
        'shipped': value['shipped'],
        'needed': value['needed'],
        'missing': value['missing'],
    };
}

