/* tslint:disable */
/* eslint-disable */
/**
 * Arke Product API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DateAttr } from './DateAttr';
import {
    DateAttrFromJSON,
    DateAttrFromJSONTyped,
    DateAttrToJSON,
    DateAttrToJSONTyped,
} from './DateAttr';
import type { MissingProductBuckets } from './MissingProductBuckets';
import {
    MissingProductBucketsFromJSON,
    MissingProductBucketsFromJSONTyped,
    MissingProductBucketsToJSON,
    MissingProductBucketsToJSONTyped,
} from './MissingProductBuckets';
import type { PricesAttr } from './PricesAttr';
import {
    PricesAttrFromJSON,
    PricesAttrFromJSONTyped,
    PricesAttrToJSON,
    PricesAttrToJSONTyped,
} from './PricesAttr';
import type { OrderMetaAttr } from './OrderMetaAttr';
import {
    OrderMetaAttrFromJSON,
    OrderMetaAttrFromJSONTyped,
    OrderMetaAttrToJSON,
    OrderMetaAttrToJSONTyped,
} from './OrderMetaAttr';

/**
 * 
 * @export
 * @interface MissingProduct
 */
export interface MissingProduct {
    /**
     * 
     * @type {string}
     * @memberof MissingProduct
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof MissingProduct
     */
    internalId?: string;
    /**
     * 
     * @type {string}
     * @memberof MissingProduct
     */
    masterType?: string;
    /**
     * 
     * @type {string}
     * @memberof MissingProduct
     */
    type: MissingProductTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof MissingProduct
     */
    name: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof MissingProduct
     */
    categories: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof MissingProduct
     */
    uom: string;
    /**
     * 
     * @type {string}
     * @memberof MissingProduct
     */
    semiId?: string;
    /**
     * 
     * @type {PricesAttr}
     * @memberof MissingProduct
     */
    prices: PricesAttr;
    /**
     * 
     * @type {DateAttr}
     * @memberof MissingProduct
     */
    created?: DateAttr;
    /**
     * 
     * @type {MissingProductBuckets}
     * @memberof MissingProduct
     */
    inventory: MissingProductBuckets;
    /**
     * 
     * @type {Array<OrderMetaAttr>}
     * @memberof MissingProduct
     */
    orders?: Array<OrderMetaAttr>;
}


/**
 * @export
 */
export const MissingProductTypeEnum = {
    Producible: 'producible',
    Purchasable: 'purchasable',
    Bundle: 'bundle'
} as const;
export type MissingProductTypeEnum = typeof MissingProductTypeEnum[keyof typeof MissingProductTypeEnum];


/**
 * Check if a given object implements the MissingProduct interface.
 */
export function instanceOfMissingProduct(value: object): value is MissingProduct {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('categories' in value) || value['categories'] === undefined) return false;
    if (!('uom' in value) || value['uom'] === undefined) return false;
    if (!('prices' in value) || value['prices'] === undefined) return false;
    if (!('inventory' in value) || value['inventory'] === undefined) return false;
    return true;
}

export function MissingProductFromJSON(json: any): MissingProduct {
    return MissingProductFromJSONTyped(json, false);
}

export function MissingProductFromJSONTyped(json: any, ignoreDiscriminator: boolean): MissingProduct {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'internalId': json['internal_id'] == null ? undefined : json['internal_id'],
        'masterType': json['master_type'] == null ? undefined : json['master_type'],
        'type': json['type'],
        'name': json['name'],
        'categories': json['categories'],
        'uom': json['uom'],
        'semiId': json['semi_id'] == null ? undefined : json['semi_id'],
        'prices': PricesAttrFromJSON(json['prices']),
        'created': json['created'] == null ? undefined : DateAttrFromJSON(json['created']),
        'inventory': MissingProductBucketsFromJSON(json['inventory']),
        'orders': json['orders'] == null ? undefined : ((json['orders'] as Array<any>).map(OrderMetaAttrFromJSON)),
    };
}

export function MissingProductToJSON(json: any): MissingProduct {
    return MissingProductToJSONTyped(json, false);
}

export function MissingProductToJSONTyped(value?: MissingProduct | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'internal_id': value['internalId'],
        'master_type': value['masterType'],
        'type': value['type'],
        'name': value['name'],
        'categories': value['categories'],
        'uom': value['uom'],
        'semi_id': value['semiId'],
        'prices': PricesAttrToJSON(value['prices']),
        'created': DateAttrToJSON(value['created']),
        'inventory': MissingProductBucketsToJSON(value['inventory']),
        'orders': value['orders'] == null ? undefined : ((value['orders'] as Array<any>).map(OrderMetaAttrToJSON)),
    };
}

