/* tslint:disable */
/* eslint-disable */
/**
 * Arke Product API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PhaseAttr
 */
export interface PhaseAttr {
    /**
     * 
     * @type {string}
     * @memberof PhaseAttr
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof PhaseAttr
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof PhaseAttr
     */
    description: string;
}

/**
 * Check if a given object implements the PhaseAttr interface.
 */
export function instanceOfPhaseAttr(value: object): value is PhaseAttr {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function PhaseAttrFromJSON(json: any): PhaseAttr {
    return PhaseAttrFromJSONTyped(json, false);
}

export function PhaseAttrFromJSONTyped(json: any, ignoreDiscriminator: boolean): PhaseAttr {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': json['description'],
    };
}

export function PhaseAttrToJSON(json: any): PhaseAttr {
    return PhaseAttrToJSONTyped(json, false);
}

export function PhaseAttrToJSONTyped(value?: PhaseAttr | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
    };
}

