/* tslint:disable */
/* eslint-disable */
/**
 * Arke Product API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PlanProcessProperties
 */
export interface PlanProcessProperties {
    /**
     * 
     * @type {string}
     * @memberof PlanProcessProperties
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof PlanProcessProperties
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof PlanProcessProperties
     */
    description: string;
    /**
     * duration in minutes
     * @type {number}
     * @memberof PlanProcessProperties
     */
    duration: number;
}

/**
 * Check if a given object implements the PlanProcessProperties interface.
 */
export function instanceOfPlanProcessProperties(value: object): value is PlanProcessProperties {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('duration' in value) || value['duration'] === undefined) return false;
    return true;
}

export function PlanProcessPropertiesFromJSON(json: any): PlanProcessProperties {
    return PlanProcessPropertiesFromJSONTyped(json, false);
}

export function PlanProcessPropertiesFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlanProcessProperties {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': json['description'],
        'duration': json['duration'],
    };
}

export function PlanProcessPropertiesToJSON(json: any): PlanProcessProperties {
    return PlanProcessPropertiesToJSONTyped(json, false);
}

export function PlanProcessPropertiesToJSONTyped(value?: PlanProcessProperties | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'duration': value['duration'],
    };
}

