/* tslint:disable */
/* eslint-disable */
/**
 * Arke Product API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DateAttr } from './DateAttr';
import {
    DateAttrFromJSON,
    DateAttrFromJSONTyped,
    DateAttrToJSON,
} from './DateAttr';
import type { ProcessLine } from './ProcessLine';
import {
    ProcessLineFromJSON,
    ProcessLineFromJSONTyped,
    ProcessLineToJSON,
} from './ProcessLine';

/**
 * 
 * @export
 * @interface ProcessDetails
 */
export interface ProcessDetails {
    /**
     * 
     * @type {DateAttr}
     * @memberof ProcessDetails
     */
    created?: DateAttr;
    /**
     * 
     * @type {DateAttr}
     * @memberof ProcessDetails
     */
    updated?: DateAttr;
    /**
     * 
     * @type {number}
     * @memberof ProcessDetails
     */
    version: number;
    /**
     * 
     * @type {boolean}
     * @memberof ProcessDetails
     */
    archived?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ProcessDetails
     */
    notes?: string;
    /**
     * 
     * @type {string}
     * @memberof ProcessDetails
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ProcessDetails
     */
    description?: string;
    /**
     * 
     * @type {Array<ProcessLine>}
     * @memberof ProcessDetails
     */
    lines?: Array<ProcessLine>;
    /**
     * 
     * @type {boolean}
     * @memberof ProcessDetails
     */
    template: boolean;
}

/**
 * Check if a given object implements the ProcessDetails interface.
 */
export function instanceOfProcessDetails(value: object): value is ProcessDetails {
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('template' in value) || value['template'] === undefined) return false;
    return true;
}

export function ProcessDetailsFromJSON(json: any): ProcessDetails {
    return ProcessDetailsFromJSONTyped(json, false);
}

export function ProcessDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProcessDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'created': json['created'] == null ? undefined : DateAttrFromJSON(json['created']),
        'updated': json['updated'] == null ? undefined : DateAttrFromJSON(json['updated']),
        'version': json['version'],
        'archived': json['archived'] == null ? undefined : json['archived'],
        'notes': json['notes'] == null ? undefined : json['notes'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'lines': json['lines'] == null ? undefined : ((json['lines'] as Array<any>).map(ProcessLineFromJSON)),
        'template': json['template'],
    };
}

export function ProcessDetailsToJSON(value?: ProcessDetails | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'created': DateAttrToJSON(value['created']),
        'updated': DateAttrToJSON(value['updated']),
        'version': value['version'],
        'archived': value['archived'],
        'notes': value['notes'],
        'name': value['name'],
        'description': value['description'],
        'lines': value['lines'] == null ? undefined : ((value['lines'] as Array<any>).map(ProcessLineToJSON)),
        'template': value['template'],
    };
}

