/* tslint:disable */
/* eslint-disable */
/**
 * Arke Product API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WarehouseAttr } from './WarehouseAttr';
import {
    WarehouseAttrFromJSON,
    WarehouseAttrFromJSONTyped,
    WarehouseAttrToJSON,
    WarehouseAttrToJSONTyped,
} from './WarehouseAttr';

/**
 * 
 * @export
 * @interface ProductInventoryAdjustment
 */
export interface ProductInventoryAdjustment {
    /**
     * 
     * @type {string}
     * @memberof ProductInventoryAdjustment
     */
    itemId?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductInventoryAdjustment
     */
    bucket: string;
    /**
     * 
     * @type {number}
     * @memberof ProductInventoryAdjustment
     */
    quantity: number;
    /**
     * 
     * @type {string}
     * @memberof ProductInventoryAdjustment
     */
    reason: string;
    /**
     * 
     * @type {WarehouseAttr}
     * @memberof ProductInventoryAdjustment
     */
    warehouseAttr: WarehouseAttr;
    /**
     * 
     * @type {string}
     * @memberof ProductInventoryAdjustment
     */
    warehouseId: string;
}

/**
 * Check if a given object implements the ProductInventoryAdjustment interface.
 */
export function instanceOfProductInventoryAdjustment(value: object): value is ProductInventoryAdjustment {
    if (!('bucket' in value) || value['bucket'] === undefined) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    if (!('reason' in value) || value['reason'] === undefined) return false;
    if (!('warehouseAttr' in value) || value['warehouseAttr'] === undefined) return false;
    if (!('warehouseId' in value) || value['warehouseId'] === undefined) return false;
    return true;
}

export function ProductInventoryAdjustmentFromJSON(json: any): ProductInventoryAdjustment {
    return ProductInventoryAdjustmentFromJSONTyped(json, false);
}

export function ProductInventoryAdjustmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductInventoryAdjustment {
    if (json == null) {
        return json;
    }
    return {
        
        'itemId': json['item_id'] == null ? undefined : json['item_id'],
        'bucket': json['bucket'],
        'quantity': json['quantity'],
        'reason': json['reason'],
        'warehouseAttr': WarehouseAttrFromJSON(json['warehouse_attr']),
        'warehouseId': json['warehouse_id'],
    };
}

export function ProductInventoryAdjustmentToJSON(json: any): ProductInventoryAdjustment {
    return ProductInventoryAdjustmentToJSONTyped(json, false);
}

export function ProductInventoryAdjustmentToJSONTyped(value?: ProductInventoryAdjustment | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'item_id': value['itemId'],
        'bucket': value['bucket'],
        'quantity': value['quantity'],
        'reason': value['reason'],
        'warehouse_attr': WarehouseAttrToJSON(value['warehouseAttr']),
        'warehouse_id': value['warehouseId'],
    };
}

