/* tslint:disable */
/* eslint-disable */
/**
 * Arke Product API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GenericAttr } from './GenericAttr';
import {
    GenericAttrFromJSON,
    GenericAttrFromJSONTyped,
    GenericAttrToJSON,
    GenericAttrToJSONTyped,
} from './GenericAttr';
import type { ProductInventoryEventSummaryInventoryItem } from './ProductInventoryEventSummaryInventoryItem';
import {
    ProductInventoryEventSummaryInventoryItemFromJSON,
    ProductInventoryEventSummaryInventoryItemFromJSONTyped,
    ProductInventoryEventSummaryInventoryItemToJSON,
    ProductInventoryEventSummaryInventoryItemToJSONTyped,
} from './ProductInventoryEventSummaryInventoryItem';

/**
 * 
 * @export
 * @interface ProductInventoryEventSummary
 */
export interface ProductInventoryEventSummary {
    /**
     * 
     * @type {string}
     * @memberof ProductInventoryEventSummary
     */
    id?: string;
    /**
     * 
     * @type {Date}
     * @memberof ProductInventoryEventSummary
     */
    time: Date;
    /**
     * 
     * @type {string}
     * @memberof ProductInventoryEventSummary
     */
    productId: string;
    /**
     * 
     * @type {string}
     * @memberof ProductInventoryEventSummary
     */
    productInternalId: string;
    /**
     * 
     * @type {string}
     * @memberof ProductInventoryEventSummary
     */
    productName: string;
    /**
     * 
     * @type {number}
     * @memberof ProductInventoryEventSummary
     */
    quantity: number;
    /**
     * 
     * @type {string}
     * @memberof ProductInventoryEventSummary
     */
    fromBucket: ProductInventoryEventSummaryFromBucketEnum;
    /**
     * 
     * @type {string}
     * @memberof ProductInventoryEventSummary
     */
    toBucket: ProductInventoryEventSummaryToBucketEnum;
    /**
     * 
     * @type {Array<GenericAttr>}
     * @memberof ProductInventoryEventSummary
     */
    refs: Array<GenericAttr>;
    /**
     * 
     * @type {string}
     * @memberof ProductInventoryEventSummary
     */
    reasonDescription?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductInventoryEventSummary
     */
    reasonType?: string;
    /**
     * 
     * @type {ProductInventoryEventSummaryInventoryItem}
     * @memberof ProductInventoryEventSummary
     */
    inventoryItem?: ProductInventoryEventSummaryInventoryItem;
}


/**
 * @export
 */
export const ProductInventoryEventSummaryFromBucketEnum = {
    Planned: 'planned',
    InProduction: 'in_production',
    Empty: ''
} as const;
export type ProductInventoryEventSummaryFromBucketEnum = typeof ProductInventoryEventSummaryFromBucketEnum[keyof typeof ProductInventoryEventSummaryFromBucketEnum];

/**
 * @export
 */
export const ProductInventoryEventSummaryToBucketEnum = {
    Planned: 'planned',
    InProduction: 'in_production',
    Available: 'available',
    Reserved: 'reserved',
    Shipped: 'shipped',
    Empty: ''
} as const;
export type ProductInventoryEventSummaryToBucketEnum = typeof ProductInventoryEventSummaryToBucketEnum[keyof typeof ProductInventoryEventSummaryToBucketEnum];


/**
 * Check if a given object implements the ProductInventoryEventSummary interface.
 */
export function instanceOfProductInventoryEventSummary(value: object): value is ProductInventoryEventSummary {
    if (!('time' in value) || value['time'] === undefined) return false;
    if (!('productId' in value) || value['productId'] === undefined) return false;
    if (!('productInternalId' in value) || value['productInternalId'] === undefined) return false;
    if (!('productName' in value) || value['productName'] === undefined) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    if (!('fromBucket' in value) || value['fromBucket'] === undefined) return false;
    if (!('toBucket' in value) || value['toBucket'] === undefined) return false;
    if (!('refs' in value) || value['refs'] === undefined) return false;
    return true;
}

export function ProductInventoryEventSummaryFromJSON(json: any): ProductInventoryEventSummary {
    return ProductInventoryEventSummaryFromJSONTyped(json, false);
}

export function ProductInventoryEventSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductInventoryEventSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'time': (new Date(json['time'])),
        'productId': json['product_id'],
        'productInternalId': json['product_internal_id'],
        'productName': json['product_name'],
        'quantity': json['quantity'],
        'fromBucket': json['from_bucket'],
        'toBucket': json['to_bucket'],
        'refs': ((json['refs'] as Array<any>).map(GenericAttrFromJSON)),
        'reasonDescription': json['reason_description'] == null ? undefined : json['reason_description'],
        'reasonType': json['reason_type'] == null ? undefined : json['reason_type'],
        'inventoryItem': json['inventory_item'] == null ? undefined : ProductInventoryEventSummaryInventoryItemFromJSON(json['inventory_item']),
    };
}

export function ProductInventoryEventSummaryToJSON(json: any): ProductInventoryEventSummary {
    return ProductInventoryEventSummaryToJSONTyped(json, false);
}

export function ProductInventoryEventSummaryToJSONTyped(value?: ProductInventoryEventSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'time': ((value['time']).toISOString()),
        'product_id': value['productId'],
        'product_internal_id': value['productInternalId'],
        'product_name': value['productName'],
        'quantity': value['quantity'],
        'from_bucket': value['fromBucket'],
        'to_bucket': value['toBucket'],
        'refs': ((value['refs'] as Array<any>).map(GenericAttrToJSON)),
        'reason_description': value['reasonDescription'],
        'reason_type': value['reasonType'],
        'inventory_item': ProductInventoryEventSummaryInventoryItemToJSON(value['inventoryItem']),
    };
}

