/* tslint:disable */
/* eslint-disable */
/**
 * Arke Product API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DateAttr } from './DateAttr';
import {
    DateAttrFromJSON,
    DateAttrFromJSONTyped,
    DateAttrToJSON,
    DateAttrToJSONTyped,
} from './DateAttr';
import type { CustomFormValues } from './CustomFormValues';
import {
    CustomFormValuesFromJSON,
    CustomFormValuesFromJSONTyped,
    CustomFormValuesToJSON,
    CustomFormValuesToJSONTyped,
} from './CustomFormValues';
import type { QuantifiedItem } from './QuantifiedItem';
import {
    QuantifiedItemFromJSON,
    QuantifiedItemFromJSONTyped,
    QuantifiedItemToJSON,
    QuantifiedItemToJSONTyped,
} from './QuantifiedItem';
import type { PricesAttr } from './PricesAttr';
import {
    PricesAttrFromJSON,
    PricesAttrFromJSONTyped,
    PricesAttrToJSON,
    PricesAttrToJSONTyped,
} from './PricesAttr';
import type { PlanPhase } from './PlanPhase';
import {
    PlanPhaseFromJSON,
    PlanPhaseFromJSONTyped,
    PlanPhaseToJSON,
    PlanPhaseToJSONTyped,
} from './PlanPhase';
import type { ProcessLine } from './ProcessLine';
import {
    ProcessLineFromJSON,
    ProcessLineFromJSONTyped,
    ProcessLineToJSON,
    ProcessLineToJSONTyped,
} from './ProcessLine';

/**
 * 
 * @export
 * @interface ProductDetails
 */
export interface ProductDetails {
    /**
     * 
     * @type {DateAttr}
     * @memberof ProductDetails
     */
    created?: DateAttr;
    /**
     * 
     * @type {DateAttr}
     * @memberof ProductDetails
     */
    updated?: DateAttr;
    /**
     * 
     * @type {number}
     * @memberof ProductDetails
     */
    version: number;
    /**
     * 
     * @type {boolean}
     * @memberof ProductDetails
     */
    archived?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ProductDetails
     */
    notes?: string;
    /**
     * 
     * @type {CustomFormValues}
     * @memberof ProductDetails
     */
    customFormValues?: CustomFormValues;
    /**
     * 
     * @type {object}
     * @memberof ProductDetails
     */
    foreignIds?: object;
    /**
     * 
     * @type {string}
     * @memberof ProductDetails
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductDetails
     */
    internalId?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductDetails
     */
    masterType?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductDetails
     */
    type: ProductDetailsTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ProductDetails
     */
    name: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ProductDetails
     */
    categories: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ProductDetails
     */
    uom: string;
    /**
     * 
     * @type {string}
     * @memberof ProductDetails
     */
    semiId?: string;
    /**
     * 
     * @type {PricesAttr}
     * @memberof ProductDetails
     */
    prices: PricesAttr;
    /**
     * 
     * @type {string}
     * @memberof ProductDetails
     */
    description: string;
    /**
     * 
     * @type {Array<QuantifiedItem>}
     * @memberof ProductDetails
     */
    rawMaterials?: Array<QuantifiedItem>;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof ProductDetails
     */
    attributes: { [key: string]: any; };
    /**
     * 
     * @type {Array<ProcessLine>}
     * @memberof ProductDetails
     */
    processLines?: Array<ProcessLine>;
    /**
     * 
     * @type {Array<QuantifiedItem>}
     * @memberof ProductDetails
     */
    bundledProducts?: Array<QuantifiedItem>;
    /**
     * 
     * @type {Array<PlanPhase>}
     * @memberof ProductDetails
     */
    plan?: Array<PlanPhase>;
    /**
     * 
     * @type {boolean}
     * @memberof ProductDetails
     */
    trackSupplierWarehouses?: boolean;
}


/**
 * @export
 */
export const ProductDetailsTypeEnum = {
    Producible: 'producible',
    Purchasable: 'purchasable',
    Bundle: 'bundle'
} as const;
export type ProductDetailsTypeEnum = typeof ProductDetailsTypeEnum[keyof typeof ProductDetailsTypeEnum];


/**
 * Check if a given object implements the ProductDetails interface.
 */
export function instanceOfProductDetails(value: object): value is ProductDetails {
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('categories' in value) || value['categories'] === undefined) return false;
    if (!('uom' in value) || value['uom'] === undefined) return false;
    if (!('prices' in value) || value['prices'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('attributes' in value) || value['attributes'] === undefined) return false;
    return true;
}

export function ProductDetailsFromJSON(json: any): ProductDetails {
    return ProductDetailsFromJSONTyped(json, false);
}

export function ProductDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'created': json['created'] == null ? undefined : DateAttrFromJSON(json['created']),
        'updated': json['updated'] == null ? undefined : DateAttrFromJSON(json['updated']),
        'version': json['version'],
        'archived': json['archived'] == null ? undefined : json['archived'],
        'notes': json['notes'] == null ? undefined : json['notes'],
        'customFormValues': json['custom_form_values'] == null ? undefined : CustomFormValuesFromJSON(json['custom_form_values']),
        'foreignIds': json['foreign_ids'] == null ? undefined : json['foreign_ids'],
        'id': json['id'] == null ? undefined : json['id'],
        'internalId': json['internal_id'] == null ? undefined : json['internal_id'],
        'masterType': json['master_type'] == null ? undefined : json['master_type'],
        'type': json['type'],
        'name': json['name'],
        'categories': json['categories'],
        'uom': json['uom'],
        'semiId': json['semi_id'] == null ? undefined : json['semi_id'],
        'prices': PricesAttrFromJSON(json['prices']),
        'description': json['description'],
        'rawMaterials': json['raw_materials'] == null ? undefined : ((json['raw_materials'] as Array<any>).map(QuantifiedItemFromJSON)),
        'attributes': json['attributes'],
        'processLines': json['process_lines'] == null ? undefined : ((json['process_lines'] as Array<any>).map(ProcessLineFromJSON)),
        'bundledProducts': json['bundled_products'] == null ? undefined : ((json['bundled_products'] as Array<any>).map(QuantifiedItemFromJSON)),
        'plan': json['plan'] == null ? undefined : ((json['plan'] as Array<any>).map(PlanPhaseFromJSON)),
        'trackSupplierWarehouses': json['track_supplier_warehouses'] == null ? undefined : json['track_supplier_warehouses'],
    };
}

export function ProductDetailsToJSON(json: any): ProductDetails {
    return ProductDetailsToJSONTyped(json, false);
}

export function ProductDetailsToJSONTyped(value?: ProductDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created': DateAttrToJSON(value['created']),
        'updated': DateAttrToJSON(value['updated']),
        'version': value['version'],
        'archived': value['archived'],
        'notes': value['notes'],
        'custom_form_values': CustomFormValuesToJSON(value['customFormValues']),
        'foreign_ids': value['foreignIds'],
        'id': value['id'],
        'internal_id': value['internalId'],
        'master_type': value['masterType'],
        'type': value['type'],
        'name': value['name'],
        'categories': value['categories'],
        'uom': value['uom'],
        'semi_id': value['semiId'],
        'prices': PricesAttrToJSON(value['prices']),
        'description': value['description'],
        'raw_materials': value['rawMaterials'] == null ? undefined : ((value['rawMaterials'] as Array<any>).map(QuantifiedItemToJSON)),
        'attributes': value['attributes'],
        'process_lines': value['processLines'] == null ? undefined : ((value['processLines'] as Array<any>).map(ProcessLineToJSON)),
        'bundled_products': value['bundledProducts'] == null ? undefined : ((value['bundledProducts'] as Array<any>).map(QuantifiedItemToJSON)),
        'plan': value['plan'] == null ? undefined : ((value['plan'] as Array<any>).map(PlanPhaseToJSON)),
        'track_supplier_warehouses': value['trackSupplierWarehouses'],
    };
}

