/* tslint:disable */
/* eslint-disable */
/**
 * Arke Product API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProductionPhaseSummary
 */
export interface ProductionPhaseSummary {
    /**
     * 
     * @type {string}
     * @memberof ProductionPhaseSummary
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductionPhaseSummary
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductionPhaseSummary
     */
    description?: string;
}

/**
 * Check if a given object implements the ProductionPhaseSummary interface.
 */
export function instanceOfProductionPhaseSummary(value: object): value is ProductionPhaseSummary {
    return true;
}

export function ProductionPhaseSummaryFromJSON(json: any): ProductionPhaseSummary {
    return ProductionPhaseSummaryFromJSONTyped(json, false);
}

export function ProductionPhaseSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductionPhaseSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function ProductionPhaseSummaryToJSON(json: any): ProductionPhaseSummary {
    return ProductionPhaseSummaryToJSONTyped(json, false);
}

export function ProductionPhaseSummaryToJSONTyped(value?: ProductionPhaseSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
    };
}

