/* tslint:disable */
/* eslint-disable */
/**
 * Arke Product API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DateAttr } from './DateAttr';
import {
    DateAttrFromJSON,
    DateAttrFromJSONTyped,
    DateAttrToJSON,
    DateAttrToJSONTyped,
} from './DateAttr';

/**
 * 
 * @export
 * @interface ProductionItemPhaseNote
 */
export interface ProductionItemPhaseNote {
    /**
     * 
     * @type {string}
     * @memberof ProductionItemPhaseNote
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductionItemPhaseNote
     */
    text?: string;
    /**
     * 
     * @type {DateAttr}
     * @memberof ProductionItemPhaseNote
     */
    created?: DateAttr;
}

/**
 * Check if a given object implements the ProductionItemPhaseNote interface.
 */
export function instanceOfProductionItemPhaseNote(value: object): value is ProductionItemPhaseNote {
    return true;
}

export function ProductionItemPhaseNoteFromJSON(json: any): ProductionItemPhaseNote {
    return ProductionItemPhaseNoteFromJSONTyped(json, false);
}

export function ProductionItemPhaseNoteFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductionItemPhaseNote {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'text': json['text'] == null ? undefined : json['text'],
        'created': json['created'] == null ? undefined : DateAttrFromJSON(json['created']),
    };
}

export function ProductionItemPhaseNoteToJSON(json: any): ProductionItemPhaseNote {
    return ProductionItemPhaseNoteToJSONTyped(json, false);
}

export function ProductionItemPhaseNoteToJSONTyped(value?: ProductionItemPhaseNote | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'text': value['text'],
        'created': DateAttrToJSON(value['created']),
    };
}

