/* tslint:disable */
/* eslint-disable */
/**
 * Arke Product API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProductionItemPhaseLog
 */
export interface ProductionItemPhaseLog {
    /**
     * 
     * @type {string}
     * @memberof ProductionItemPhaseLog
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ProductionItemPhaseLog
     */
    event: ProductionItemPhaseLogEventEnum;
    /**
     * 
     * @type {Date}
     * @memberof ProductionItemPhaseLog
     */
    createdAt: Date;
}


/**
 * @export
 */
export const ProductionItemPhaseLogEventEnum = {
    Started: 'started',
    Completed: 'completed'
} as const;
export type ProductionItemPhaseLogEventEnum = typeof ProductionItemPhaseLogEventEnum[keyof typeof ProductionItemPhaseLogEventEnum];


/**
 * Check if a given object implements the ProductionItemPhaseLog interface.
 */
export function instanceOfProductionItemPhaseLog(value: object): value is ProductionItemPhaseLog {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('event' in value) || value['event'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function ProductionItemPhaseLogFromJSON(json: any): ProductionItemPhaseLog {
    return ProductionItemPhaseLogFromJSONTyped(json, false);
}

export function ProductionItemPhaseLogFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductionItemPhaseLog {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'event': json['event'],
        'createdAt': (new Date(json['created_at'])),
    };
}

export function ProductionItemPhaseLogToJSON(json: any): ProductionItemPhaseLog {
    return ProductionItemPhaseLogToJSONTyped(json, false);
}

export function ProductionItemPhaseLogToJSONTyped(value?: ProductionItemPhaseLog | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'event': value['event'],
        'created_at': ((value['createdAt']).toISOString()),
    };
}

