/* tslint:disable */
/* eslint-disable */
/**
 * Arke Product API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProductionItem } from './ProductionItem';
import {
    ProductionItemFromJSON,
    ProductionItemFromJSONTyped,
    ProductionItemToJSON,
    ProductionItemToJSONTyped,
} from './ProductionItem';
import type { ProductionPhaseSummary } from './ProductionPhaseSummary';
import {
    ProductionPhaseSummaryFromJSON,
    ProductionPhaseSummaryFromJSONTyped,
    ProductionPhaseSummaryToJSON,
    ProductionPhaseSummaryToJSONTyped,
} from './ProductionPhaseSummary';
import type { ProductionItemPhaseLog } from './ProductionItemPhaseLog';
import {
    ProductionItemPhaseLogFromJSON,
    ProductionItemPhaseLogFromJSONTyped,
    ProductionItemPhaseLogToJSON,
    ProductionItemPhaseLogToJSONTyped,
} from './ProductionItemPhaseLog';

/**
 * 
 * @export
 * @interface ProductionItemPhaseSummary
 */
export interface ProductionItemPhaseSummary {
    /**
     * 
     * @type {string}
     * @memberof ProductionItemPhaseSummary
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ProductionItemPhaseSummary
     */
    status: ProductionItemPhaseSummaryStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof ProductionItemPhaseSummary
     */
    step?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductionItemPhaseSummary
     */
    percentage?: number;
    /**
     * 
     * @type {Date}
     * @memberof ProductionItemPhaseSummary
     */
    startedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ProductionItemPhaseSummary
     */
    completedAt?: Date;
    /**
     * 
     * @type {Array<ProductionItemPhaseLog>}
     * @memberof ProductionItemPhaseSummary
     */
    logs?: Array<ProductionItemPhaseLog>;
    /**
     * 
     * @type {ProductionPhaseSummary}
     * @memberof ProductionItemPhaseSummary
     */
    phase?: ProductionPhaseSummary;
    /**
     * 
     * @type {ProductionItem}
     * @memberof ProductionItemPhaseSummary
     */
    productionItem: ProductionItem;
}


/**
 * @export
 */
export const ProductionItemPhaseSummaryStatusEnum = {
    NotReady: 'not_ready',
    Ready: 'ready',
    Started: 'started',
    Completed: 'completed'
} as const;
export type ProductionItemPhaseSummaryStatusEnum = typeof ProductionItemPhaseSummaryStatusEnum[keyof typeof ProductionItemPhaseSummaryStatusEnum];


/**
 * Check if a given object implements the ProductionItemPhaseSummary interface.
 */
export function instanceOfProductionItemPhaseSummary(value: object): value is ProductionItemPhaseSummary {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('productionItem' in value) || value['productionItem'] === undefined) return false;
    return true;
}

export function ProductionItemPhaseSummaryFromJSON(json: any): ProductionItemPhaseSummary {
    return ProductionItemPhaseSummaryFromJSONTyped(json, false);
}

export function ProductionItemPhaseSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductionItemPhaseSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'status': json['status'],
        'step': json['step'] == null ? undefined : json['step'],
        'percentage': json['percentage'] == null ? undefined : json['percentage'],
        'startedAt': json['started_at'] == null ? undefined : (new Date(json['started_at'])),
        'completedAt': json['completed_at'] == null ? undefined : (new Date(json['completed_at'])),
        'logs': json['logs'] == null ? undefined : ((json['logs'] as Array<any>).map(ProductionItemPhaseLogFromJSON)),
        'phase': json['phase'] == null ? undefined : ProductionPhaseSummaryFromJSON(json['phase']),
        'productionItem': ProductionItemFromJSON(json['production_item']),
    };
}

export function ProductionItemPhaseSummaryToJSON(json: any): ProductionItemPhaseSummary {
    return ProductionItemPhaseSummaryToJSONTyped(json, false);
}

export function ProductionItemPhaseSummaryToJSONTyped(value?: ProductionItemPhaseSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'status': value['status'],
        'step': value['step'],
        'percentage': value['percentage'],
        'started_at': value['startedAt'] == null ? undefined : ((value['startedAt']).toISOString()),
        'completed_at': value['completedAt'] == null ? undefined : ((value['completedAt']).toISOString()),
        'logs': value['logs'] == null ? undefined : ((value['logs'] as Array<any>).map(ProductionItemPhaseLogToJSON)),
        'phase': ProductionPhaseSummaryToJSON(value['phase']),
        'production_item': ProductionItemToJSON(value['productionItem']),
    };
}

