/* tslint:disable */
/* eslint-disable */
/**
 * Arke Product API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DateAttr } from './DateAttr';
import {
    DateAttrFromJSON,
    DateAttrFromJSONTyped,
    DateAttrToJSON,
    DateAttrToJSONTyped,
} from './DateAttr';
import type { CustomFormValues } from './CustomFormValues';
import {
    CustomFormValuesFromJSON,
    CustomFormValuesFromJSONTyped,
    CustomFormValuesToJSON,
    CustomFormValuesToJSONTyped,
} from './CustomFormValues';
import type { PricesAttr } from './PricesAttr';
import {
    PricesAttrFromJSON,
    PricesAttrFromJSONTyped,
    PricesAttrToJSON,
    PricesAttrToJSONTyped,
} from './PricesAttr';
import type { CompanyAttr } from './CompanyAttr';
import {
    CompanyAttrFromJSON,
    CompanyAttrFromJSONTyped,
    CompanyAttrToJSON,
    CompanyAttrToJSONTyped,
} from './CompanyAttr';

/**
 * 
 * @export
 * @interface ProductSupplierDetails
 */
export interface ProductSupplierDetails {
    /**
     * 
     * @type {DateAttr}
     * @memberof ProductSupplierDetails
     */
    created?: DateAttr;
    /**
     * 
     * @type {DateAttr}
     * @memberof ProductSupplierDetails
     */
    updated?: DateAttr;
    /**
     * 
     * @type {number}
     * @memberof ProductSupplierDetails
     */
    version: number;
    /**
     * 
     * @type {boolean}
     * @memberof ProductSupplierDetails
     */
    archived?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ProductSupplierDetails
     */
    notes?: string;
    /**
     * 
     * @type {CustomFormValues}
     * @memberof ProductSupplierDetails
     */
    customFormValues?: CustomFormValues;
    /**
     * 
     * @type {object}
     * @memberof ProductSupplierDetails
     */
    foreignIds?: object;
    /**
     * 
     * @type {string}
     * @memberof ProductSupplierDetails
     */
    supplierId: string;
    /**
     * 
     * @type {string}
     * @memberof ProductSupplierDetails
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductSupplierDetails
     */
    externalId: string;
    /**
     * 
     * @type {string}
     * @memberof ProductSupplierDetails
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductSupplierDetails
     */
    description?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ProductSupplierDetails
     */
    categories?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ProductSupplierDetails
     */
    uom?: string;
    /**
     * 
     * @type {CompanyAttr}
     * @memberof ProductSupplierDetails
     */
    supplierAttr?: CompanyAttr;
    /**
     * 
     * @type {string}
     * @memberof ProductSupplierDetails
     */
    aggregateOfId?: string;
    /**
     * 
     * @type {number}
     * @memberof ProductSupplierDetails
     */
    aggregateQuantity?: number;
    /**
     * 
     * @type {PricesAttr}
     * @memberof ProductSupplierDetails
     */
    prices?: PricesAttr;
    /**
     * 
     * @type {number}
     * @memberof ProductSupplierDetails
     */
    minimumQuantity: number;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof ProductSupplierDetails
     */
    attributes?: { [key: string]: any; };
    /**
     * 
     * @type {string}
     * @memberof ProductSupplierDetails
     */
    leadTime?: string;
}

/**
 * Check if a given object implements the ProductSupplierDetails interface.
 */
export function instanceOfProductSupplierDetails(value: object): value is ProductSupplierDetails {
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('supplierId' in value) || value['supplierId'] === undefined) return false;
    if (!('externalId' in value) || value['externalId'] === undefined) return false;
    if (!('minimumQuantity' in value) || value['minimumQuantity'] === undefined) return false;
    return true;
}

export function ProductSupplierDetailsFromJSON(json: any): ProductSupplierDetails {
    return ProductSupplierDetailsFromJSONTyped(json, false);
}

export function ProductSupplierDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductSupplierDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'created': json['created'] == null ? undefined : DateAttrFromJSON(json['created']),
        'updated': json['updated'] == null ? undefined : DateAttrFromJSON(json['updated']),
        'version': json['version'],
        'archived': json['archived'] == null ? undefined : json['archived'],
        'notes': json['notes'] == null ? undefined : json['notes'],
        'customFormValues': json['custom_form_values'] == null ? undefined : CustomFormValuesFromJSON(json['custom_form_values']),
        'foreignIds': json['foreign_ids'] == null ? undefined : json['foreign_ids'],
        'supplierId': json['supplier_id'],
        'id': json['id'] == null ? undefined : json['id'],
        'externalId': json['external_id'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'categories': json['categories'] == null ? undefined : json['categories'],
        'uom': json['uom'] == null ? undefined : json['uom'],
        'supplierAttr': json['supplier_attr'] == null ? undefined : CompanyAttrFromJSON(json['supplier_attr']),
        'aggregateOfId': json['aggregate_of_id'] == null ? undefined : json['aggregate_of_id'],
        'aggregateQuantity': json['aggregate_quantity'] == null ? undefined : json['aggregate_quantity'],
        'prices': json['prices'] == null ? undefined : PricesAttrFromJSON(json['prices']),
        'minimumQuantity': json['minimum_quantity'],
        'attributes': json['attributes'] == null ? undefined : json['attributes'],
        'leadTime': json['lead_time'] == null ? undefined : json['lead_time'],
    };
}

export function ProductSupplierDetailsToJSON(json: any): ProductSupplierDetails {
    return ProductSupplierDetailsToJSONTyped(json, false);
}

export function ProductSupplierDetailsToJSONTyped(value?: ProductSupplierDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created': DateAttrToJSON(value['created']),
        'updated': DateAttrToJSON(value['updated']),
        'version': value['version'],
        'archived': value['archived'],
        'notes': value['notes'],
        'custom_form_values': CustomFormValuesToJSON(value['customFormValues']),
        'foreign_ids': value['foreignIds'],
        'supplier_id': value['supplierId'],
        'id': value['id'],
        'external_id': value['externalId'],
        'name': value['name'],
        'description': value['description'],
        'categories': value['categories'],
        'uom': value['uom'],
        'supplier_attr': CompanyAttrToJSON(value['supplierAttr']),
        'aggregate_of_id': value['aggregateOfId'],
        'aggregate_quantity': value['aggregateQuantity'],
        'prices': PricesAttrToJSON(value['prices']),
        'minimum_quantity': value['minimumQuantity'],
        'attributes': value['attributes'],
        'lead_time': value['leadTime'],
    };
}

