/* tslint:disable */
/* eslint-disable */
/**
 * Arke Product API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProductionItemLog
 */
export interface ProductionItemLog {
    /**
     * 
     * @type {string}
     * @memberof ProductionItemLog
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ProductionItemLog
     */
    event: ProductionItemLogEventEnum;
    /**
     * 
     * @type {Date}
     * @memberof ProductionItemLog
     */
    createdAt: Date;
    /**
     * 
     * @type {number}
     * @memberof ProductionItemLog
     */
    quantity?: number;
}


/**
 * @export
 */
export const ProductionItemLogEventEnum = {
    Started: 'started',
    Completed: 'completed',
    Updated: 'updated'
} as const;
export type ProductionItemLogEventEnum = typeof ProductionItemLogEventEnum[keyof typeof ProductionItemLogEventEnum];


/**
 * Check if a given object implements the ProductionItemLog interface.
 */
export function instanceOfProductionItemLog(value: object): value is ProductionItemLog {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('event' in value) || value['event'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function ProductionItemLogFromJSON(json: any): ProductionItemLog {
    return ProductionItemLogFromJSONTyped(json, false);
}

export function ProductionItemLogFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductionItemLog {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'event': json['event'],
        'createdAt': (new Date(json['created_at'])),
        'quantity': json['quantity'] == null ? undefined : json['quantity'],
    };
}

export function ProductionItemLogToJSON(json: any): ProductionItemLog {
    return ProductionItemLogToJSONTyped(json, false);
}

export function ProductionItemLogToJSONTyped(value?: ProductionItemLog | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'event': value['event'],
        'created_at': ((value['createdAt']).toISOString()),
        'quantity': value['quantity'],
    };
}

