/* tslint:disable */
/* eslint-disable */
/**
 * Arke Product API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProductionSearchStatus } from './ProductionSearchStatus';
import {
    ProductionSearchStatusFromJSON,
    ProductionSearchStatusFromJSONTyped,
    ProductionSearchStatusToJSON,
    ProductionSearchStatusToJSONTyped,
} from './ProductionSearchStatus';

/**
 * 
 * @export
 * @interface ProductionSearchRequest
 */
export interface ProductionSearchRequest {
    /**
     * 
     * @type {Array<ProductionSearchStatus>}
     * @memberof ProductionSearchRequest
     */
    statuses?: Array<ProductionSearchStatus>;
}

/**
 * Check if a given object implements the ProductionSearchRequest interface.
 */
export function instanceOfProductionSearchRequest(value: object): value is ProductionSearchRequest {
    return true;
}

export function ProductionSearchRequestFromJSON(json: any): ProductionSearchRequest {
    return ProductionSearchRequestFromJSONTyped(json, false);
}

export function ProductionSearchRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductionSearchRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'statuses': json['statuses'] == null ? undefined : ((json['statuses'] as Array<any>).map(ProductionSearchStatusFromJSON)),
    };
}

export function ProductionSearchRequestToJSON(json: any): ProductionSearchRequest {
    return ProductionSearchRequestToJSONTyped(json, false);
}

export function ProductionSearchRequestToJSONTyped(value?: ProductionSearchRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'statuses': value['statuses'] == null ? undefined : ((value['statuses'] as Array<any>).map(ProductionSearchStatusToJSON)),
    };
}

