/* tslint:disable */
/* eslint-disable */
/**
 * Arke Product API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProductionUpdateRequest
 */
export interface ProductionUpdateRequest {
    /**
     * 
     * @type {number}
     * @memberof ProductionUpdateRequest
     */
    quantity: number;
}

/**
 * Check if a given object implements the ProductionUpdateRequest interface.
 */
export function instanceOfProductionUpdateRequest(value: object): value is ProductionUpdateRequest {
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    return true;
}

export function ProductionUpdateRequestFromJSON(json: any): ProductionUpdateRequest {
    return ProductionUpdateRequestFromJSONTyped(json, false);
}

export function ProductionUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductionUpdateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'quantity': json['quantity'],
    };
}

export function ProductionUpdateRequestToJSON(json: any): ProductionUpdateRequest {
    return ProductionUpdateRequestToJSONTyped(json, false);
}

export function ProductionUpdateRequestToJSONTyped(value?: ProductionUpdateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'quantity': value['quantity'],
    };
}

