/* tslint:disable */
/* eslint-disable */
/**
 * Arke IAM API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmailAttachment
 */
export interface EmailAttachment {
    /**
     * 
     * @type {string}
     * @memberof EmailAttachment
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof EmailAttachment
     */
    content: string;
    /**
     * 
     * @type {string}
     * @memberof EmailAttachment
     */
    path?: string;
}

/**
 * Check if a given object implements the EmailAttachment interface.
 */
export function instanceOfEmailAttachment(value: object): value is EmailAttachment {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function EmailAttachmentFromJSON(json: any): EmailAttachment {
    return EmailAttachmentFromJSONTyped(json, false);
}

export function EmailAttachmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailAttachment {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'content': json['content'],
        'path': json['path'] == null ? undefined : json['path'],
    };
}

export function EmailAttachmentToJSON(json: any): EmailAttachment {
    return EmailAttachmentToJSONTyped(json, false);
}

export function EmailAttachmentToJSONTyped(value?: EmailAttachment | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'content': value['content'],
        'path': value['path'],
    };
}

