/* tslint:disable */
/* eslint-disable */
/**
 * Arke IAM API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListDocuments200ResponseInner
 */
export interface ListDocuments200ResponseInner {
    /**
     * 
     * @type {string}
     * @memberof ListDocuments200ResponseInner
     */
    name: string;
    /**
     * 
     * @type {Date}
     * @memberof ListDocuments200ResponseInner
     */
    updated: Date;
}

/**
 * Check if a given object implements the ListDocuments200ResponseInner interface.
 */
export function instanceOfListDocuments200ResponseInner(value: object): value is ListDocuments200ResponseInner {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('updated' in value) || value['updated'] === undefined) return false;
    return true;
}

export function ListDocuments200ResponseInnerFromJSON(json: any): ListDocuments200ResponseInner {
    return ListDocuments200ResponseInnerFromJSONTyped(json, false);
}

export function ListDocuments200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListDocuments200ResponseInner {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'updated': (new Date(json['updated'])),
    };
}

export function ListDocuments200ResponseInnerToJSON(json: any): ListDocuments200ResponseInner {
    return ListDocuments200ResponseInnerToJSONTyped(json, false);
}

export function ListDocuments200ResponseInnerToJSONTyped(value?: ListDocuments200ResponseInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'updated': ((value['updated']).toISOString()),
    };
}

