/* tslint:disable */
/* eslint-disable */
/**
 * Arke IAM API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StoreDocumentRequest
 */
export interface StoreDocumentRequest {
    /**
     * 
     * @type {string}
     * @memberof StoreDocumentRequest
     */
    file: string;
    /**
     * 
     * @type {string}
     * @memberof StoreDocumentRequest
     */
    name: string;
}

/**
 * Check if a given object implements the StoreDocumentRequest interface.
 */
export function instanceOfStoreDocumentRequest(value: object): value is StoreDocumentRequest {
    if (!('file' in value) || value['file'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function StoreDocumentRequestFromJSON(json: any): StoreDocumentRequest {
    return StoreDocumentRequestFromJSONTyped(json, false);
}

export function StoreDocumentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoreDocumentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'file': json['file'],
        'name': json['name'],
    };
}

export function StoreDocumentRequestToJSON(json: any): StoreDocumentRequest {
    return StoreDocumentRequestToJSONTyped(json, false);
}

export function StoreDocumentRequestToJSONTyped(value?: StoreDocumentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'file': value['file'],
        'name': value['name'],
    };
}

