/* tslint:disable */
/* eslint-disable */
/**
 * Arke Supply API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { wait } from '$utils/wait';
import type {
    MissingRawMaterial,
    SupplyNeedsDetails,
} from '../models/index';
import {
    MissingRawMaterialFromJSON,
    SupplyNeedsDetailsToJSON
} from '../models/index';
import * as runtime from '../runtime';

export interface CalculateSupplyNeedsRequest {
    supplyNeedsDetails?: Array<SupplyNeedsDetails>;
}

export interface CalculateSupplyNeedsForProductionRequest {
    supplyNeedsDetails?: SupplyNeedsDetails;
}

export interface CalculateSupplyNeedsForProductionPhaseRequest {
    supplyNeedsDetails?: SupplyNeedsDetails;
}

/**
 * 
 */
export class AnalyticsApi extends runtime.BaseAPI {

    /**
     */
    async calculateSupplyNeedsRaw(requestParameters: CalculateSupplyNeedsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<MissingRawMaterial>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/analytics/supply-needs/_calculate`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['supplyNeedsDetails']!.map(SupplyNeedsDetailsToJSON),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(MissingRawMaterialFromJSON));
    }

    /**
     */
    async calculateSupplyNeeds(requestParameters: CalculateSupplyNeedsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<MissingRawMaterial>> {
        const response = await this.calculateSupplyNeedsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async calculateSupplyNeedsForProductionRaw(requestParameters: CalculateSupplyNeedsForProductionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<MissingRawMaterial>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/analytics/supply-needs/_calculate-for-production`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SupplyNeedsDetailsToJSON(requestParameters['supplyNeedsDetails']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(MissingRawMaterialFromJSON));
    }

    /**
     */
    async calculateSupplyNeedsForProduction(requestParameters: CalculateSupplyNeedsForProductionRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<MissingRawMaterial>> {
        const response = await this.calculateSupplyNeedsForProductionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async calculateSupplyNeedsForProductionPhaseRaw(requestParameters: CalculateSupplyNeedsForProductionPhaseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<MissingRawMaterial>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/analytics/supply-needs/_calculate-for-production-phase`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SupplyNeedsDetailsToJSON(requestParameters['supplyNeedsDetails']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(MissingRawMaterialFromJSON));
    }

    /**
     */
    async calculateSupplyNeedsForProductionPhase(requestParameters: CalculateSupplyNeedsForProductionPhaseRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<MissingRawMaterial>> {
        const response = await this.calculateSupplyNeedsForProductionPhaseRaw(requestParameters, initOverrides);
        return await response.value();
    }
    
    /**
     */
    async showSupplyNeeds(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<MissingRawMaterial>> {
        await wait(Math.random() * 500)

        return [
            {
                "alternatives": [],
                "categories": [
                    "pelle",
                    "contovendita"
                ],
                "created": {
                    "at": "2025-01-08T17:44:28.036459458Z",
                    "by": {
                        "id": "81425a4f-7c86-4324-ac12-1c3846479dbf",
                        "fullName": "Michela Andreolli",
                        "username": "Michi"
                    }
                },
                "description": "",
                "estimatedCost": {
                    "currency": "EUR",
                    "unit": 100,
                    "vat": 22
                },
                "externalId": "Pel-Prad-1",
                "id": "62826f82-4e62-4469-b1d9-2ed9e416174a",
                "inventory": {
                    "inbound": 0,
                    "inStock": 0,
                    "inUse": 1,
                    "consumed": 0,
                    "discarded": 0,
                    "ordered": 1,
                    "needed": 2,
                    "missing": 2
                },
                "leadTime": "30d",
                "minimumQuantity": 1,
                "name": "Pelle di prada maculata",
                "prices": {
                    "currency": "EUR",
                    "unit": 100,
                    "deals": [
                        {
                            "minQuantity": 1,
                            "unit": 100,
                            "category": ""
                        }
                    ],
                    "vat": 22
                },
                "supplierAttr": {
                    "id": "8efbb61f-b578-4e3b-b43d-c92f843cadcc",
                    "name": "Prada - fornitore",
                    "vat": "IT123456789"
                },
                "supplierId": "8efbb61f-b578-4e3b-b43d-c92f843cadcc",
                "uom": "unit"
            },
            {
                "alternatives": [],
                "categories": [
                    "paints"
                ],
                "created": {
                    "at": "2024-11-13T12:19:12.898820471Z",
                    "by": {
                        "id": "46bcd6af-0b84-4252-b336-7b117005061f",
                        "fullName": "Arke Team",
                        "username": "team"
                    }
                },
                "description": "",
                "externalId": "SKU-Lockman II-4-21731500328719",
                "id": "43b5f701-6d04-4ee9-a7d1-ca982a77a55b",
                "inventory": {
                    "inbound": 13,
                    "inStock": 19,
                    "inUse": 0,
                    "consumed": 0,
                    "discarded": 0,
                    "ordered": 9,
                    "needed": 1.9,
                    "missing": 15
                },
                "minimumQuantity": 15,
                "name": "Gorgeous Rubber Computer 704",
                "prices": {
                    "currency": "EUR",
                    "unit": 24,
                    "deals": [
                        {
                            "minQuantity": 1,
                            "unit": 24,
                            "category": ""
                        }
                    ],
                    "vat": 22
                },
                "supplierAttr": {
                    "id": "c3a8977c-507f-4d3b-84de-1d96c7b0de0c",
                    "name": "Lockman II",
                    "vat": ""
                },
                "supplierId": "c3a8977c-507f-4d3b-84de-1d96c7b0de0c",
                "uom": "unit"
            },
            {
                "alternatives": [],
                "categories": [
                    "cotone"
                ],
                "created": {
                    "at": "2025-01-13T16:56:13.257534397Z",
                    "by": {
                        "id": "e2c98d1b-3ef1-47e2-8815-8e4642279271",
                        "fullName": "matteoferravante",
                        "username": "matteo_arke"
                    }
                },
                "description": "",
                "estimatedCost": {
                    "currency": "EUR",
                    "unit": 3000,
                    "vat": 22
                },
                "externalId": "COT-0001-2024",
                "id": "4f1b0db6-4aba-47d2-bca8-e07de80c46e3",
                "inventory": {
                    "inbound": 0,
                    "inStock": 0,
                    "inUse": 0,
                    "consumed": 0,
                    "discarded": 0,
                    "ordered": 0,
                    "needed": 600,
                    "missing": 600
                },
                "leadTime": "",
                "minimumQuantity": 0,
                "name": "Filato di cotone grezzo",
                "prices": {
                    "currency": "EUR",
                    "unit": 5,
                    "deals": [
                        {
                            "minQuantity": 1,
                            "unit": 5,
                            "category": ""
                        }
                    ],
                    "vat": 22
                },
                "supplierAttr": {
                    "id": "59a51f9a-1227-4c21-b7a8-6a1eaefec7e3",
                    "name": "Witting-Botsford",
                    "vat": "2128738302"
                },
                "supplierId": "59a51f9a-1227-4c21-b7a8-6a1eaefec7e3",
                "uom": "meter"
            },
            {
                "alternatives": [],
                "categories": [
                    "leather",
                    "cotone"
                ],
                "created": {
                    "at": "2024-11-13T12:18:53.634210634Z",
                    "by": {
                        "id": "46bcd6af-0b84-4252-b336-7b117005061f",
                        "fullName": "Arke Team",
                        "username": "team"
                    }
                },
                "description": "",
                "externalId": "SKU-Hills-Schamberger-1-31731500309424",
                "id": "041403ae-dfdc-46e4-9b86-d6078dab9842",
                "inventory": {
                    "inbound": 0,
                    "inStock": 2,
                    "inUse": 0,
                    "consumed": 0,
                    "discarded": 2,
                    "ordered": 0,
                    "needed": 1,
                    "missing": 1
                },
                "minimumQuantity": 1,
                "name": "Practical Cotton Car 340",
                "prices": {
                    "currency": "EUR",
                    "unit": 18,
                    "deals": [
                        {
                            "minQuantity": 1,
                            "unit": 18,
                            "category": ""
                        }
                    ],
                    "vat": 22
                },
                "supplierAttr": {
                    "id": "05ec7042-58b8-4194-8496-11e0357adaa9",
                    "name": "Hills-Schamberger",
                    "vat": ""
                },
                "supplierId": "05ec7042-58b8-4194-8496-11e0357adaa9",
                "uom": "unit"
            },
            {
                "alternatives": [],
                "categories": [
                    "paints"
                ],
                "created": {
                    "at": "2024-11-13T12:18:46.631316006Z",
                    "by": {
                        "id": "46bcd6af-0b84-4252-b336-7b117005061f",
                        "fullName": "Arke Team",
                        "username": "team"
                    }
                },
                "description": "",
                "externalId": "SKU-Solomon Pi-0-21731500302420",
                "id": "0784750f-5343-426e-95b9-76be229eb1a4",
                "inventory": {
                    "inbound": 0,
                    "inStock": 0,
                    "inUse": 0,
                    "consumed": 0,
                    "discarded": 0,
                    "ordered": 0,
                    "needed": 1,
                    "missing": 93
                },
                "minimumQuantity": 92,
                "name": "Intelligent Steel Car 095",
                "prices": {
                    "currency": "EUR",
                    "unit": 91,
                    "vat": 22
                },
                "supplierAttr": {
                    "id": "b3863588-8430-4c03-99a7-e71f86a2eef6",
                    "name": "Solomon Pi",
                    "vat": ""
                },
                "supplierId": "b3863588-8430-4c03-99a7-e71f86a2eef6",
                "uom": "unit"
            },
            {
                "alternatives": [],
                "categories": [
                    "screws",
                    "leather",
                    "paints",
                    "tools",
                    "ciao",
                    "mv",
                    "dij"
                ],
                "created": {
                    "at": "2024-12-12T14:50:07.392061087Z",
                    "by": {
                        "id": "46bcd6af-0b84-4252-b336-7b117005061f",
                        "fullName": "Arke Team",
                        "username": "team"
                    }
                },
                "description": "CP (EAN) - codice univoco del prodotto generato dal fornitore\nSKU - codice del magazzino che diamo noi? gestione interna\n",
                "externalId": "cocco1",
                "id": "331021c8-92db-4306-be7e-e1455fb7833f",
                "inventory": {
                    "inbound": -8,
                    "inStock": 500056,
                    "inUse": -21,
                    "consumed": 0,
                    "discarded": 0,
                    "ordered": 32,
                    "needed": 1.3,
                    "missing": 14
                },
                "leadTime": "29d",
                "minimumQuantity": 14,
                "name": "pelle di coccodrillo ",
                "prices": {
                    "currency": "EUR",
                    "unit": 50,
                    "deals": [
                        {
                            "minQuantity": 2,
                            "unit": 50,
                            "category": ""
                        },
                        {
                            "minQuantity": 10,
                            "unit": 20,
                            "category": ""
                        }
                    ],
                    "vat": 22
                },
                "supplierAttr": {
                    "id": "b25fa3fb-5958-438d-851a-47c4a03a76fb",
                    "name": "mavi srl",
                    "vat": "12345"
                },
                "supplierId": "b25fa3fb-5958-438d-851a-47c4a03a76fb",
                "uom": "unit"
            },
            {
                "alternatives": [],
                "categories": [],
                "created": {
                    "at": "2025-07-23T09:20:19.901584334Z",
                    "by": {
                        "id": "46bcd6af-0b84-4252-b336-7b117005061f",
                        "fullName": "Arke Team",
                        "username": "team"
                    }
                },
                "description": "",
                "externalId": "00010",
                "id": "4cb3867a-f982-49f8-b3ce-2de74dc0c969",
                "inventory": {
                    "inbound": 0,
                    "inStock": 0,
                    "inUse": 0,
                    "consumed": 0,
                    "discarded": 0,
                    "ordered": 0,
                    "needed": 0.27,
                    "missing": 0.27
                },
                "leadTime": "",
                "minimumQuantity": 0,
                "name": "CROSTA KID 1.6/1.8",
                "prices": {
                    "currency": "EUR",
                    "unit": 10,
                    "deals": [
                        {
                            "minQuantity": 1,
                            "unit": 10,
                            "category": "principale"
                        }
                    ],
                    "vat": 22
                },
                "supplierAttr": {
                    "id": "0bf7f249-d120-448a-831f-222325140dce",
                    "name": "Fornitore fornitissimo",
                    "vat": "IT1234567890"
                },
                "supplierId": "0bf7f249-d120-448a-831f-222325140dce",
                "uom": "pq"
            },
            {
                "alternatives": [],
                "categories": [],
                "created": {
                    "at": "2024-12-27T14:16:27.434310969Z",
                    "by": {
                        "id": "46bcd6af-0b84-4252-b336-7b117005061f",
                        "fullName": "Arke Team",
                        "username": "team"
                    }
                },
                "description": "",
                "estimatedCost": {
                    "currency": "EUR",
                    "unit": 70,
                    "vat": 22
                },
                "externalId": "Fibbie1234_24",
                "id": "50f0fd9c-0233-4dc2-b8f8-40cae531bf99",
                "inventory": {
                    "inbound": 0,
                    "inStock": 998,
                    "inUse": 0,
                    "consumed": 2,
                    "discarded": 0,
                    "ordered": 1,
                    "needed": 1001,
                    "missing": 2
                },
                "leadTime": "",
                "minimumQuantity": 0,
                "name": "Fibbie metalliche",
                "prices": {
                    "currency": "EUR",
                    "unit": 35,
                    "deals": [
                        {
                            "minQuantity": 50,
                            "unit": 25,
                            "category": "Sconto Quantità - 50 pezzi"
                        },
                        {
                            "minQuantity": 10,
                            "unit": 30,
                            "category": "Sconto Quantità - 10 pezzi"
                        },
                        {
                            "minQuantity": 1,
                            "unit": 35,
                            "category": ""
                        }
                    ],
                    "vat": 22
                },
                "supplierAttr": {
                    "id": "c3a8977c-507f-4d3b-84de-1d96c7b0de0c",
                    "name": "Lockman II",
                    "vat": "6476763039"
                },
                "supplierId": "c3a8977c-507f-4d3b-84de-1d96c7b0de0c",
                "uom": "unit"
            },
            {
                "alternatives": [],
                "categories": [
                    "tools"
                ],
                "created": {
                    "at": "2024-11-13T12:18:46.665054368Z",
                    "by": {
                        "id": "46bcd6af-0b84-4252-b336-7b117005061f",
                        "fullName": "Arke Team",
                        "username": "team"
                    }
                },
                "description": "",
                "externalId": "SKU-Solomon Pi-0-31731500302486",
                "id": "64aa2436-154d-41df-89f4-37a7d0ed7ee6",
                "inventory": {
                    "inbound": 0,
                    "inStock": 0,
                    "inUse": 0,
                    "consumed": 0,
                    "discarded": 0,
                    "ordered": 0,
                    "needed": 1,
                    "missing": 6
                },
                "minimumQuantity": 5,
                "name": "Practical Rubber Gloves 380",
                "prices": {
                    "currency": "EUR",
                    "unit": 82,
                    "vat": 22
                },
                "supplierAttr": {
                    "id": "b3863588-8430-4c03-99a7-e71f86a2eef6",
                    "name": "Solomon Pi",
                    "vat": ""
                },
                "supplierId": "b3863588-8430-4c03-99a7-e71f86a2eef6",
                "uom": "unit"
            },
            {
                "alternatives": [],
                "categories": [],
                "created": {
                    "at": "2025-09-30T08:52:15.534169532Z",
                    "by": {
                        "id": "46bcd6af-0b84-4252-b336-7b117005061f",
                        "fullName": "Arke Team",
                        "username": "team"
                    }
                },
                "description": "",
                "externalId": "345PL",
                "id": "a8ec1778-11af-4020-b4b2-8a39311e3f9d",
                "inventory": {
                    "inbound": 0,
                    "inStock": 0,
                    "inUse": 0,
                    "consumed": 0,
                    "discarded": 0,
                    "ordered": 0,
                    "needed": 0.5,
                    "missing": 0.5
                },
                "leadTime": "10d",
                "minimumQuantity": 0,
                "name": "STRUZZO",
                "prices": {
                    "currency": "EUR",
                    "unit": 1,
                    "deals": [
                        {
                            "minQuantity": 1,
                            "unit": 1,
                            "category": "ttt"
                        }
                    ],
                    "vat": 22
                },
                "supplierAttr": {
                    "id": "0bf7f249-d120-448a-831f-222325140dce",
                    "name": "Fornitore fornitissimo",
                    "vat": "IT1234567890"
                },
                "supplierId": "0bf7f249-d120-448a-831f-222325140dce",
                "uom": "liter"
            },
            {
                "alternatives": [],
                "categories": [
                    "leather"
                ],
                "created": {
                    "at": "2024-11-13T12:18:48.737355936Z",
                    "by": {
                        "id": "46bcd6af-0b84-4252-b336-7b117005061f",
                        "fullName": "Arke Team",
                        "username": "team"
                    }
                },
                "description": "",
                "estimatedCost": {
                    "currency": "EUR",
                    "unit": 110,
                    "vat": 22
                },
                "externalId": "SKU-Solomon Pi-0-231731500304278",
                "id": "96684b97-2051-4902-a4ed-4498f6e06585",
                "inventory": {
                    "inbound": 0,
                    "inStock": 0,
                    "inUse": 0,
                    "consumed": 0,
                    "discarded": 0,
                    "ordered": 0,
                    "needed": 5,
                    "missing": 69
                },
                "minimumQuantity": 64,
                "name": "Sleek Rubber Chair 178",
                "prices": {
                    "currency": "EUR",
                    "unit": 22,
                    "deals": [
                        {
                            "minQuantity": 1,
                            "unit": 22,
                            "category": "Basic"
                        }
                    ],
                    "vat": 22
                },
                "supplierAttr": {
                    "id": "b3863588-8430-4c03-99a7-e71f86a2eef6",
                    "name": "Solomon Pi",
                    "vat": ""
                },
                "supplierId": "b3863588-8430-4c03-99a7-e71f86a2eef6",
                "uom": "unit"
            },
            {
                "alternatives": [],
                "categories": [
                    "pelle",
                    "coccodrillo",
                    "mv"
                ],
                "created": {
                    "at": "2024-12-05T13:48:52.360698678Z",
                    "by": {
                        "id": "46bcd6af-0b84-4252-b336-7b117005061f",
                        "fullName": "Arke Team",
                        "username": "team"
                    }
                },
                "description": "",
                "externalId": "cocco2",
                "id": "d97b4fa0-b1d0-4db1-83a1-8cb94401369d",
                "inventory": {
                    "inbound": 0,
                    "inStock": 0,
                    "inUse": 0,
                    "consumed": 0,
                    "discarded": 0,
                    "ordered": 2,
                    "needed": 2,
                    "missing": 2
                },
                "leadTime": "10d",
                "minimumQuantity": 2,
                "name": "pelle di coccodrillo.1",
                "prices": {
                    "currency": "EUR",
                    "unit": 1111,
                    "deals": [
                        {
                            "minQuantity": 1,
                            "unit": 1111,
                            "category": ""
                        }
                    ],
                    "vat": 0
                },
                "supplierAttr": {
                    "id": "05ec7042-58b8-4194-8496-11e0357adaa9",
                    "name": "Hills-Schamberger",
                    "vat": "4138837102"
                },
                "supplierId": "05ec7042-58b8-4194-8496-11e0357adaa9",
                "uom": "unit"
            },
            {
                "alternatives": [],
                "categories": [
                    "pelle"
                ],
                "created": {
                    "at": "2025-01-05T18:25:33.564994119Z",
                    "by": {
                        "id": "46bcd6af-0b84-4252-b336-7b117005061f",
                        "fullName": "Arke Team",
                        "username": "team"
                    }
                },
                "description": "",
                "externalId": "SKU-002",
                "id": "90bcf4d0-587e-443f-a8df-1deb19d57365",
                "inventory": {
                    "inbound": 89.999,
                    "inStock": 888.999,
                    "inUse": 100.001,
                    "consumed": 15.000999,
                    "discarded": 48,
                    "ordered": 12.001,
                    "needed": 10,
                    "missing": 0
                },
                "leadTime": "0d",
                "minimumQuantity": 0,
                "name": "Pelle Bovino / Marrone",
                "prices": {
                    "currency": "EUR",
                    "unit": 1,
                    "deals": [
                        {
                            "minQuantity": 1,
                            "unit": 1,
                            "category": ""
                        }
                    ],
                    "vat": 22
                },
                "supplierAttr": {
                    "id": "c68636b2-2b4c-4288-b257-c9b5e70e3b4e",
                    "name": "Acme 12345",
                    "vat": "0123456789"
                },
                "supplierId": "c68636b2-2b4c-4288-b257-c9b5e70e3b4e",
                "uom": "meter"
            }
        ]
    }

}
