/* tslint:disable */
/* eslint-disable */
/**
 * Arke Supply API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { wait } from '$utils/wait';
import type {
    MonthlyPurchases,
    SupplierDetails,
} from '../models/index';
import {
    SupplierDetailsFromJSON
} from '../models/index';
import * as runtime from '../runtime';

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     */
    async lastTwoMonthPurchases(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<MonthlyPurchases>> {
        await wait(Math.random() * 500)

        return [
            {
                "month": "2025-10",
                "orderCount": 15,
                "total": 406.99
            },
            {
                "month": "2025-11",
                "orderCount": 4,
                "total": 524.5
            }
        ]
    }

    /**
     */
    async listSupplierCategoriesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<string>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/supplier/_categories`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async listSupplierCategories(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<string>> {
        const response = await this.listSupplierCategoriesRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async showSelfSupplierRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SupplierDetails>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/supplier/_self`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SupplierDetailsFromJSON(jsonValue));
    }

    /**
     */
    async showSelfSupplier(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SupplierDetails> {
        const response = await this.showSelfSupplierRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async upsertSelfSupplierRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/supplier/_self`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async upsertSelfSupplier(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.upsertSelfSupplierRaw(initOverrides);
    }

}
