/* tslint:disable */
/* eslint-disable */
/**
 * Arke Supply API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

export interface InternalStartIngestionPurchaseInvoicesRequest {
    simulate?: boolean;
    body?: object;
}

/**
 * 
 */
export class InternalApi extends runtime.BaseAPI {

    /**
     */
    async internalStartIngestionPurchaseInvoicesRaw(requestParameters: InternalStartIngestionPurchaseInvoicesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['simulate'] != null) {
            queryParameters['simulate'] = requestParameters['simulate'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/xml';

        const response = await this.request({
            path: `/internal/purchase-invoice/_start-ingestion`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async internalStartIngestionPurchaseInvoices(requestParameters: InternalStartIngestionPurchaseInvoicesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.internalStartIngestionPurchaseInvoicesRaw(requestParameters, initOverrides);
    }

}
