/* tslint:disable */
/* eslint-disable */
/**
 * Arke Supply API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { wait } from '$utils/wait';
import type {
    BulkOrderDetails,
    ComputeOrderCompletionDetails,
    OrderDetails,
    OrderSummary,
    SendOrderCommand,
} from '../models/index';
import {
    BulkOrderDetailsToJSON,
    ComputeOrderCompletionDetailsFromJSON,
    OrderDetailsFromJSON,
    OrderDetailsToJSON,
    OrderSummaryFromJSON,
    SendOrderCommandFromJSON
} from '../models/index';
import * as runtime from '../runtime';

export interface AcceptOrderRequest {
    orderId: string;
}

export interface ArchiveOrderRequest {
    orderId: string;
}

export interface ComputeOrderCompletionRequest {
    orderId: string;
}

export interface CreateBulkOrderRequest {
    bulkOrderDetails?: Array<BulkOrderDetails>;
}

export interface CreateOrderRequest {
    orderDetails?: OrderDetails;
}

export interface ExportOrdersRequest {
    search?: string;
    status?: Array<string>;
}

export interface ListOrdersRequest {
    limit?: number;
    offset?: number;
    search?: string;
    status?: Array<string>;
    query?: string;
    from?: Date;
    to?: Date;
}

export interface ListOrdersBySupplierRequest {
    supplierId?: string;
    limit?: number;
    offset?: number;
    search?: string;
    archived?: string;
    status?: Array<string>;
    query?: string;
    from?: Date;
    to?: Date;
}

export interface RejectOrderRequest {
    orderId: string;
}

export interface SendOrderRequest {
    orderId: string;
}

export interface ShowOrderRequest {
    orderId: string;
}

export interface UpdateOrderRequest {
    orderId: string;
    orderDetails?: OrderDetails;
}

/**
 * 
 */
export class OrdersApi extends runtime.BaseAPI {

    /**
     * Flags an order as accepted by the supplier. It also kicks off a workflow in which the items are marked as  \"inbound\", and an event is generated
     * flags an order as accepted by the supplier
     */
    async acceptOrderRaw(requestParameters: AcceptOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrderDetails>> {
        if (requestParameters['orderId'] == null) {
            throw new runtime.RequiredError(
                'orderId',
                'Required parameter "orderId" was null or undefined when calling acceptOrder().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/order/{orderId}/_accept`.replace(`{${"orderId"}}`, encodeURIComponent(String(requestParameters['orderId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrderDetailsFromJSON(jsonValue));
    }

    /**
     * Flags an order as accepted by the supplier. It also kicks off a workflow in which the items are marked as  \"inbound\", and an event is generated
     * flags an order as accepted by the supplier
     */
    async acceptOrder(requestParameters: AcceptOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrderDetails> {
        const response = await this.acceptOrderRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async archiveOrderRaw(requestParameters: ArchiveOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['orderId'] == null) {
            throw new runtime.RequiredError(
                'orderId',
                'Required parameter "orderId" was null or undefined when calling archiveOrder().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/order/{orderId}`.replace(`{${"orderId"}}`, encodeURIComponent(String(requestParameters['orderId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async archiveOrder(requestParameters: ArchiveOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.archiveOrderRaw(requestParameters, initOverrides);
    }

    /**
     */
    async computeOrderCompletionRaw(requestParameters: ComputeOrderCompletionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ComputeOrderCompletionDetails>> {
        if (requestParameters['orderId'] == null) {
            throw new runtime.RequiredError(
                'orderId',
                'Required parameter "orderId" was null or undefined when calling computeOrderCompletion().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/order/{orderId}/_compute-completion`.replace(`{${"orderId"}}`, encodeURIComponent(String(requestParameters['orderId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ComputeOrderCompletionDetailsFromJSON(jsonValue));
    }

    /**
     */
    async computeOrderCompletion(requestParameters: ComputeOrderCompletionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ComputeOrderCompletionDetails> {
        const response = await this.computeOrderCompletionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async createBulkOrderRaw(requestParameters: CreateBulkOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<OrderDetails>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/order/_createBulk`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['bulkOrderDetails']!.map(BulkOrderDetailsToJSON),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(OrderDetailsFromJSON));
    }

    /**
     */
    async createBulkOrder(requestParameters: CreateBulkOrderRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<OrderDetails>> {
        const response = await this.createBulkOrderRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * creates an order
     */
    async createOrderRaw(requestParameters: CreateOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrderDetails>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/order`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: OrderDetailsToJSON(requestParameters['orderDetails']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrderDetailsFromJSON(jsonValue));
    }

    /**
     * creates an order
     */
    async createOrder(requestParameters: CreateOrderRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrderDetails> {
        const response = await this.createOrderRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async exportOrdersRaw(requestParameters: ExportOrdersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        const queryParameters: any = {};

        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/order/_export`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     */
    async exportOrders(requestParameters: ExportOrdersRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.exportOrdersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * lists active orders
     */
    async listActiveOrders(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<OrderSummary>> {
        await wait(Math.random() * 500)

        return [
            {
                "buckets": {
                    "inbound": 1,
                    "inStock": 0,
                    "inUse": 0,
                    "consumed": 0,
                    "discarded": 0
                },
                "default_currency": "EUR",
                "expected_delivery_time": "2024-11-27T23:00:00Z",
                "id": "46f1abc9-ef07-496d-8d59-47cb8ea6d624",
                "internal_id": "PO-2024/0017",
                "name": "Acme Inc 2024/11/26",
                "status": "accepted",
                "supplier_attr": {
                    "id": "fd350ff9-e8fa-41b3-8801-d79b2ec4e805",
                    "name": "Acme Inc",
                    "vat": "11111222233334444"
                },
                "time": "2024-11-26T18:35:20.266Z",
                "total_vat_incl": 0.92,
                "warehouse_attr": {
                    "id": "c6c13283-d4f7-488b-af73-2f54cdb29c4d",
                    "name": "Main warehouse"
                },
                "warehouse_id": "c6c13283-d4f7-488b-af73-2f54cdb29c4d"
            },
            {
                "buckets": {
                    "inbound": 1000,
                    "inStock": 0,
                    "inUse": 0,
                    "consumed": 0,
                    "discarded": 0
                },
                "default_currency": "EUR",
                "expected_delivery_time": "2025-10-23T22:00:00Z",
                "id": "c006d6b1-67d0-467d-9ae6-ed4d01e23262",
                "internal_id": "PO-2025/0076",
                "name": "Acme Inc 2025/10/20",
                "status": "accepted",
                "supplier_attr": {
                    "id": "fd350ff9-e8fa-41b3-8801-d79b2ec4e805",
                    "name": "Acme Inc",
                    "vat": "11111222233334444"
                },
                "time": "2025-10-20T18:00:59.851Z",
                "total_vat_incl": 12.2,
                "warehouse_attr": {
                    "id": "c6c13283-d4f7-488b-af73-2f54cdb29c4d",
                    "name": "Main warehouse"
                },
                "warehouse_id": "c6c13283-d4f7-488b-af73-2f54cdb29c4d"
            },
            {
                "buckets": {
                    "inbound": 1,
                    "inStock": 0,
                    "inUse": 0,
                    "consumed": 0,
                    "discarded": 0
                },
                "default_currency": "EUR",
                "expected_delivery_time": "2025-10-21T22:00:00Z",
                "id": "daef9c39-e2b5-4d78-9fed-2c47e1e149a2",
                "internal_id": "PO-2025/0080",
                "name": "Casa della brugola 2025/10/22",
                "status": "accepted",
                "supplier_attr": {
                    "id": "24d77612-0b04-49eb-8202-65d0d551b42f",
                    "name": "Casa della brugola",
                    "vat": "11111222233334444"
                },
                "time": "2025-10-22T14:37:00.972Z",
                "total_vat_incl": 183,
                "warehouse_attr": {
                    "id": "c6c13283-d4f7-488b-af73-2f54cdb29c4d",
                    "name": "Main warehouse"
                },
                "warehouse_id": "c6c13283-d4f7-488b-af73-2f54cdb29c4d"
            },
            {
                "buckets": {
                    "inbound": 55,
                    "inStock": 60,
                    "inUse": 0,
                    "consumed": 0,
                    "discarded": 0
                },
                "default_currency": "EUR",
                "expected_delivery_time": "2024-12-17T23:00:00Z",
                "id": "2db6fcae-9e4c-4b3b-9839-42b3554d04ae",
                "internal_id": "PO-2024/0030",
                "name": "Acme Inc 2024/12/12",
                "status": "accepted",
                "supplier_attr": {
                    "id": "fd350ff9-e8fa-41b3-8801-d79b2ec4e805",
                    "name": "Acme Inc",
                    "vat": "11111222233334444"
                },
                "time": "2024-12-12T23:29:23.323Z",
                "total_vat_incl": 106.75,
                "warehouse_attr": {
                    "id": "c6c13283-d4f7-488b-af73-2f54cdb29c4d",
                    "name": "Main warehouse"
                },
                "warehouse_id": "c6c13283-d4f7-488b-af73-2f54cdb29c4d"
            },
            {
                "buckets": {
                    "inbound": 1,
                    "inStock": 0,
                    "inUse": 0,
                    "consumed": 0,
                    "discarded": 0
                },
                "default_currency": "EUR",
                "expected_delivery_time": "2024-11-29T23:00:00Z",
                "id": "b265254c-d6c7-41d0-bbd6-1904c1aa7eb8",
                "internal_id": "PO-2024/0014",
                "name": "Acme Inc 2024/11/26",
                "status": "accepted",
                "supplier_attr": {
                    "id": "fd350ff9-e8fa-41b3-8801-d79b2ec4e805",
                    "name": "Acme Inc",
                    "vat": "11111222233334444"
                },
                "time": "2024-11-26T17:36:23.849Z",
                "total_vat_incl": 0.92,
                "warehouse_attr": {
                    "id": "c6c13283-d4f7-488b-af73-2f54cdb29c4d",
                    "name": "Main warehouse"
                },
                "warehouse_id": "c6c13283-d4f7-488b-af73-2f54cdb29c4d"
            },
            {
                "buckets": {
                    "inbound": 20,
                    "inStock": 80,
                    "inUse": 0,
                    "consumed": 0,
                    "discarded": 0
                },
                "default_currency": "EUR",
                "expected_delivery_time": "2024-11-29T23:00:00Z",
                "id": "d6600ca5-460f-4c9f-88b8-8a9d4ac68a62",
                "internal_id": "PO-2024/0015",
                "name": "Acme Inc 2024/11/26",
                "status": "accepted",
                "supplier_attr": {
                    "id": "fd350ff9-e8fa-41b3-8801-d79b2ec4e805",
                    "name": "Acme Inc",
                    "vat": "11111222233334444"
                },
                "time": "2024-11-26T17:59:17.995Z",
                "total_vat_incl": 18.3,
                "warehouse_attr": {
                    "id": "c6c13283-d4f7-488b-af73-2f54cdb29c4d",
                    "name": "Main warehouse"
                },
                "warehouse_id": "c6c13283-d4f7-488b-af73-2f54cdb29c4d"
            },
            {
                "buckets": {
                    "inbound": 1,
                    "inStock": 0,
                    "inUse": 0,
                    "consumed": 0,
                    "discarded": 0
                },
                "default_currency": "EUR",
                "expected_delivery_time": "2024-11-29T23:00:00Z",
                "id": "d9812fc8-446d-4359-8a56-90378b600ad4",
                "internal_id": "PO-2024/0012",
                "name": "Acme Inc 2024/11/26",
                "status": "accepted",
                "supplier_attr": {
                    "id": "fd350ff9-e8fa-41b3-8801-d79b2ec4e805",
                    "name": "Acme Inc",
                    "vat": "11111222233334444"
                },
                "time": "2024-11-26T16:47:38.793Z",
                "total_vat_incl": 4.47,
                "warehouse_attr": {
                    "id": "c6c13283-d4f7-488b-af73-2f54cdb29c4d",
                    "name": "Main warehouse"
                },
                "warehouse_id": "c6c13283-d4f7-488b-af73-2f54cdb29c4d"
            },
            {
                "buckets": {
                    "inbound": 1,
                    "inStock": 0,
                    "inUse": 0,
                    "consumed": 0,
                    "discarded": 0
                },
                "default_currency": "EUR",
                "expected_delivery_time": "2024-11-28T23:00:00Z",
                "id": "ae0d1a72-123d-4486-bfc4-0a6297c40667",
                "internal_id": "PO-2024/0016",
                "name": "Acme Inc 2024/11/26",
                "status": "accepted",
                "supplier_attr": {
                    "id": "fd350ff9-e8fa-41b3-8801-d79b2ec4e805",
                    "name": "Acme Inc",
                    "vat": "11111222233334444"
                },
                "time": "2024-11-26T18:26:51.161Z",
                "total_vat_incl": 0.92,
                "warehouse_attr": {
                    "id": "c6c13283-d4f7-488b-af73-2f54cdb29c4d",
                    "name": "Main warehouse"
                },
                "warehouse_id": "c6c13283-d4f7-488b-af73-2f54cdb29c4d"
            },
            {
                "buckets": {
                    "inbound": 100,
                    "inStock": 100,
                    "inUse": 0,
                    "consumed": 0,
                    "discarded": 0
                },
                "default_currency": "EUR",
                "expected_delivery_time": "2024-11-29T23:00:00Z",
                "id": "4e35fe51-6b83-4df8-97f9-743fd5057fb8",
                "internal_id": "PO-2024/0022",
                "name": "Acme Inc 2024/11/28",
                "status": "accepted",
                "supplier_attr": {
                    "id": "fd350ff9-e8fa-41b3-8801-d79b2ec4e805",
                    "name": "Acme Inc",
                    "vat": "11111222233334444"
                },
                "time": "2024-11-28T11:55:02.546Z",
                "total_vat_incl": 79.3,
                "warehouse_attr": {
                    "id": "c6c13283-d4f7-488b-af73-2f54cdb29c4d",
                    "name": "Main warehouse"
                },
                "warehouse_id": "c6c13283-d4f7-488b-af73-2f54cdb29c4d"
            },
            {
                "buckets": {
                    "inbound": 50,
                    "inStock": 50,
                    "inUse": 0,
                    "consumed": 0,
                    "discarded": 0
                },
                "default_currency": "EUR",
                "expected_delivery_time": "2024-12-19T23:00:00Z",
                "id": "e1e317d3-b77a-4937-97f0-cfb0f03a1cf5",
                "internal_id": "PO-2024/0026",
                "name": "Acme Inc 2024/12/05",
                "status": "accepted",
                "supplier_attr": {
                    "id": "fd350ff9-e8fa-41b3-8801-d79b2ec4e805",
                    "name": "Acme Inc",
                    "vat": "11111222233334444"
                },
                "time": "2024-12-05T14:13:20.779Z",
                "total_vat_incl": 36.6,
                "warehouse_attr": {
                    "id": "c6c13283-d4f7-488b-af73-2f54cdb29c4d",
                    "name": "Main warehouse"
                },
                "warehouse_id": "c6c13283-d4f7-488b-af73-2f54cdb29c4d"
            },
            {
                "buckets": {
                    "inbound": 50,
                    "inStock": 50,
                    "inUse": 0,
                    "consumed": 0,
                    "discarded": 0
                },
                "default_currency": "EUR",
                "expected_delivery_time": "2024-12-17T23:00:00Z",
                "id": "7074dda3-6660-443c-950f-65ec888884b9",
                "internal_id": "PO-2024/0028",
                "name": "Acme Inc 2024/12/08",
                "status": "accepted",
                "supplier_attr": {
                    "id": "fd350ff9-e8fa-41b3-8801-d79b2ec4e805",
                    "name": "Acme Inc",
                    "vat": "11111222233334444"
                },
                "time": "2024-12-08T16:57:04.905Z",
                "total_vat_incl": 61,
                "warehouse_attr": {
                    "id": "c6c13283-d4f7-488b-af73-2f54cdb29c4d",
                    "name": "Main warehouse"
                },
                "warehouse_id": "c6c13283-d4f7-488b-af73-2f54cdb29c4d"
            },
            {
                "buckets": {
                    "inbound": 1,
                    "inStock": 0,
                    "inUse": 0,
                    "consumed": 0,
                    "discarded": 0
                },
                "default_currency": "EUR",
                "expected_delivery_time": "2025-09-25T22:00:00Z",
                "id": "f0a8d9dd-64b5-442e-a413-e759edf1cb6d",
                "internal_id": "PO-2025/0069",
                "name": "Arke 2025/09/23",
                "status": "sent",
                "supplier_attr": {
                    "id": "bcdb6a1b-3dd4-4204-89d8-0349181a73bc",
                    "name": "Arke",
                    "vat": "1234567890"
                },
                "time": "2025-09-23T13:46:05.817848Z",
                "total_vat_incl": 6.1,
                "warehouse_attr": {
                    "id": "c6c13283-d4f7-488b-af73-2f54cdb29c4d",
                    "name": "Main warehouse"
                },
                "warehouse_id": "c6c13283-d4f7-488b-af73-2f54cdb29c4d"
            },
            {
                "buckets": {
                    "inbound": 1,
                    "inStock": 1,
                    "inUse": 0,
                    "consumed": 0,
                    "discarded": 0
                },
                "default_currency": "EUR",
                "expected_delivery_time": "2025-01-15T23:00:00Z",
                "id": "115f7b53-4e9e-4d96-b785-0d10e93c32a1",
                "internal_id": "PO-2025/0006",
                "name": "Acme Inc 2025/01/09",
                "status": "accepted",
                "supplier_attr": {
                    "id": "fd350ff9-e8fa-41b3-8801-d79b2ec4e805",
                    "name": "Acme Inc",
                    "vat": "11111222233334444"
                },
                "time": "2025-01-09T17:26:15.605Z",
                "total_vat_incl": 19.52,
                "warehouse_attr": {
                    "id": "c6c13283-d4f7-488b-af73-2f54cdb29c4d",
                    "name": "Main warehouse"
                },
                "warehouse_id": "c6c13283-d4f7-488b-af73-2f54cdb29c4d"
            },
            {
                "buckets": {
                    "inbound": 4,
                    "inStock": 6,
                    "inUse": 0,
                    "consumed": 0,
                    "discarded": 0
                },
                "default_currency": "EUR",
                "expected_delivery_time": "2025-01-27T23:00:00Z",
                "id": "827b52c3-f22c-42cd-887d-2d59cc7aed31",
                "internal_id": "PO-2025/0008",
                "name": "Acme Inc 2025/01/23",
                "status": "accepted",
                "supplier_attr": {
                    "id": "fd350ff9-e8fa-41b3-8801-d79b2ec4e805",
                    "name": "Acme Inc",
                    "vat": "11111222233334444"
                },
                "time": "2025-01-23T17:27:32.654Z",
                "total_vat_incl": 91.5,
                "warehouse_attr": {
                    "id": "c6c13283-d4f7-488b-af73-2f54cdb29c4d",
                    "name": "Main warehouse"
                },
                "warehouse_id": "c6c13283-d4f7-488b-af73-2f54cdb29c4d"
            },
            {
                "buckets": {
                    "inbound": 1,
                    "inStock": 0,
                    "inUse": 0,
                    "consumed": 0,
                    "discarded": 0
                },
                "default_currency": "EUR",
                "expected_delivery_time": "2025-02-14T23:00:00Z",
                "id": "a6509937-5461-40dd-94c8-05b97724b851",
                "internal_id": "PO-2025/0010",
                "name": "Acme Inc 2025/02/07",
                "status": "accepted",
                "supplier_attr": {
                    "id": "fd350ff9-e8fa-41b3-8801-d79b2ec4e805",
                    "name": "Acme Inc",
                    "vat": "11111222233334444"
                },
                "time": "2025-02-07T09:31:36.808Z",
                "total_vat_incl": 1.22,
                "warehouse_attr": {
                    "id": "c6c13283-d4f7-488b-af73-2f54cdb29c4d",
                    "name": "Main warehouse"
                },
                "warehouse_id": "c6c13283-d4f7-488b-af73-2f54cdb29c4d"
            },
            {
                "buckets": {
                    "inbound": 200,
                    "inStock": 0,
                    "inUse": 0,
                    "consumed": 0,
                    "discarded": 0
                },
                "default_currency": "EUR",
                "expected_delivery_time": "2025-04-19T22:00:00Z",
                "id": "a114bf67-72b5-4172-b6d6-76301acede72",
                "internal_id": "PO-2025/0020",
                "name": "Acme Inc 2025/04/04",
                "status": "accepted",
                "supplier_attr": {
                    "id": "fd350ff9-e8fa-41b3-8801-d79b2ec4e805",
                    "name": "Acme Inc",
                    "vat": "11111222233334444"
                },
                "time": "2025-04-04T15:13:57.976Z",
                "total_vat_incl": 2.44,
                "warehouse_attr": {
                    "id": "c6c13283-d4f7-488b-af73-2f54cdb29c4d",
                    "name": "Main warehouse"
                },
                "warehouse_id": "c6c13283-d4f7-488b-af73-2f54cdb29c4d"
            },
            {
                "buckets": {
                    "inbound": 1,
                    "inStock": 0,
                    "inUse": 0,
                    "consumed": 0,
                    "discarded": 0
                },
                "default_currency": "EUR",
                "expected_delivery_time": "2025-06-19T22:00:00Z",
                "id": "608e5c46-bb24-4649-8434-7a9787933bf3",
                "internal_id": "PO-2025/0043",
                "name": "Acme Inc 2025/06/04",
                "status": "sent",
                "supplier_attr": {
                    "id": "fd350ff9-e8fa-41b3-8801-d79b2ec4e805",
                    "name": "Acme Inc",
                    "vat": "11111222233334444"
                },
                "time": "2025-06-04T10:12:02.638591Z",
                "total_vat_incl": 0.01,
                "warehouse_attr": {
                    "id": "c6c13283-d4f7-488b-af73-2f54cdb29c4d",
                    "name": "Main warehouse"
                },
                "warehouse_id": "c6c13283-d4f7-488b-af73-2f54cdb29c4d"
            },
            {
                "buckets": {
                    "inbound": 1,
                    "inStock": 4,
                    "inUse": 0,
                    "consumed": 0,
                    "discarded": 0
                },
                "default_currency": "EUR",
                "expected_delivery_time": "2025-11-08T16:27:39.946Z",
                "id": "ea05a34a-0523-4617-903c-61cf84d0dcb7",
                "internal_id": "PO-2025/0089",
                "name": "Acme Inc 2025/11/06",
                "status": "accepted",
                "supplier_attr": {
                    "id": "fd350ff9-e8fa-41b3-8801-d79b2ec4e805",
                    "name": "Acme Inc",
                    "vat": "11111222233334444"
                },
                "time": "2025-11-06T16:27:47.06Z",
                "total_vat_incl": 305,
                "warehouse_attr": {
                    "id": "c6c13283-d4f7-488b-af73-2f54cdb29c4d",
                    "name": "Main warehouse"
                },
                "warehouse_id": "c6c13283-d4f7-488b-af73-2f54cdb29c4d"
            },
            {
                "buckets": {
                    "inbound": 1,
                    "inStock": 0,
                    "inUse": 0,
                    "consumed": 0,
                    "discarded": 0
                },
                "default_currency": "EUR",
                "expected_delivery_time": "2025-06-19T22:00:00Z",
                "id": "cae7d5fd-20d6-40f9-be64-02dd5e73886c",
                "internal_id": "PO-2025/0047",
                "name": "Acme Inc 2025/06/04",
                "status": "sent",
                "supplier_attr": {
                    "id": "fd350ff9-e8fa-41b3-8801-d79b2ec4e805",
                    "name": "Acme Inc",
                    "vat": "11111222233334444"
                },
                "time": "2025-06-04T10:14:17.220931Z",
                "total_vat_incl": 9.15,
                "warehouse_attr": {
                    "id": "c6c13283-d4f7-488b-af73-2f54cdb29c4d",
                    "name": "Main warehouse"
                },
                "warehouse_id": "c6c13283-d4f7-488b-af73-2f54cdb29c4d"
            },
            {
                "buckets": {
                    "inbound": 2,
                    "inStock": 0,
                    "inUse": 0,
                    "consumed": 0,
                    "discarded": 0
                },
                "default_currency": "EUR",
                "expected_delivery_time": "2025-06-19T22:00:00Z",
                "id": "294d9287-d308-4442-afbb-807a48d70468",
                "internal_id": "PO-2025/0049",
                "name": "Road Runner Inc 2025/06/04",
                "status": "sent",
                "supplier_attr": {
                    "id": "b5a4540d-f1ba-4fc6-a36d-e12b9daa3aec",
                    "name": "Road Runner Inc",
                    "vat": "0987654321"
                },
                "time": "2025-06-04T10:16:41.14Z",
                "total_vat_incl": 24.4,
                "warehouse_attr": {
                    "id": "c6c13283-d4f7-488b-af73-2f54cdb29c4d",
                    "name": "Main warehouse"
                },
                "warehouse_id": "c6c13283-d4f7-488b-af73-2f54cdb29c4d"
            },
            {
                "buckets": {
                    "inbound": 10.375,
                    "inStock": 0,
                    "inUse": 0,
                    "consumed": 0,
                    "discarded": 0
                },
                "default_currency": "EUR",
                "expected_delivery_time": "2025-06-27T22:00:00Z",
                "id": "155f7bb1-95d4-4371-a662-56ae865fbc6c",
                "internal_id": "PO-2025/0050",
                "name": "Acme Inc 2025/06/04",
                "status": "sent",
                "supplier_attr": {
                    "id": "fd350ff9-e8fa-41b3-8801-d79b2ec4e805",
                    "name": "Acme Inc",
                    "vat": "11111222233334444"
                },
                "time": "2025-06-04T10:23:31.86387Z",
                "total_vat_incl": 126.57,
                "warehouse_attr": {
                    "id": "c6c13283-d4f7-488b-af73-2f54cdb29c4d",
                    "name": "Main warehouse"
                },
                "warehouse_id": "c6c13283-d4f7-488b-af73-2f54cdb29c4d"
            },
            {
                "buckets": {
                    "inbound": 100,
                    "inStock": 0,
                    "inUse": 0,
                    "consumed": 0,
                    "discarded": 0
                },
                "default_currency": "EUR",
                "expected_delivery_time": "2025-06-29T22:00:00Z",
                "id": "14982e14-6207-4b2c-ba2b-45199b08fcbb",
                "internal_id": "PO-2025/0051",
                "name": "Acme Inc 2025/06/16",
                "status": "accepted",
                "supplier_attr": {
                    "id": "fd350ff9-e8fa-41b3-8801-d79b2ec4e805",
                    "name": "Acme Inc",
                    "vat": "11111222233334444"
                },
                "time": "2025-06-16T13:52:22.919Z",
                "total_vat_incl": 1.22,
                "warehouse_attr": {
                    "id": "c6c13283-d4f7-488b-af73-2f54cdb29c4d",
                    "name": "Main warehouse"
                },
                "warehouse_id": "c6c13283-d4f7-488b-af73-2f54cdb29c4d"
            },
            {
                "buckets": {
                    "inbound": 1,
                    "inStock": 0,
                    "inUse": 0,
                    "consumed": 0,
                    "discarded": 0
                },
                "default_currency": "EUR",
                "expected_delivery_time": "2025-10-08T22:00:00Z",
                "id": "4303d18a-5703-4ed2-98a5-df64c799e12a",
                "internal_id": "PO-2025/0070",
                "name": "Casa della brugola 2025/10/09",
                "status": "accepted",
                "supplier_attr": {
                    "id": "24d77612-0b04-49eb-8202-65d0d551b42f",
                    "name": "Casa della brugola",
                    "vat": "11111222233334444"
                },
                "time": "2025-10-09T14:26:50.221Z",
                "total_vat_incl": 73.2,
                "warehouse_attr": {
                    "id": "c6c13283-d4f7-488b-af73-2f54cdb29c4d",
                    "name": "Main warehouse"
                },
                "warehouse_id": "c6c13283-d4f7-488b-af73-2f54cdb29c4d"
            },
            {
                "buckets": {
                    "inbound": 1,
                    "inStock": 0,
                    "inUse": 0,
                    "consumed": 0,
                    "discarded": 0
                },
                "default_currency": "EUR",
                "expected_delivery_time": "2025-10-26T14:08:23.757Z",
                "id": "592e2174-221c-4e65-a57d-00c768a021ad",
                "internal_id": "PO-2025/0075",
                "name": "Acme Inc 2025/10/20",
                "status": "accepted",
                "supplier_attr": {
                    "id": "fd350ff9-e8fa-41b3-8801-d79b2ec4e805",
                    "name": "Acme Inc",
                    "vat": "11111222233334444"
                },
                "time": "2025-10-20T13:08:35.269Z",
                "total_vat_incl": 33.6,
                "warehouse_attr": {
                    "id": "c6c13283-d4f7-488b-af73-2f54cdb29c4d",
                    "name": "Main warehouse"
                },
                "warehouse_id": "c6c13283-d4f7-488b-af73-2f54cdb29c4d"
            },
            {
                "buckets": {
                    "inbound": 1,
                    "inStock": 0,
                    "inUse": 0,
                    "consumed": 0,
                    "discarded": 0
                },
                "default_currency": "EUR",
                "expected_delivery_time": "2025-09-26T22:00:00Z",
                "id": "97c4573d-b5a6-4976-b0dc-258353184d6c",
                "internal_id": "PO-2025/0068",
                "name": "Arke 2025/09/23",
                "status": "accepted",
                "supplier_attr": {
                    "id": "bcdb6a1b-3dd4-4204-89d8-0349181a73bc",
                    "name": "Arke",
                    "vat": "1234567890"
                },
                "time": "2025-09-23T13:43:25.689Z",
                "total_vat_incl": 6.1,
                "warehouse_attr": {
                    "id": "c6c13283-d4f7-488b-af73-2f54cdb29c4d",
                    "name": "Main warehouse"
                },
                "warehouse_id": "c6c13283-d4f7-488b-af73-2f54cdb29c4d"
            },
            {
                "buckets": {
                    "inbound": 1,
                    "inStock": 0,
                    "inUse": 0,
                    "consumed": 0,
                    "discarded": 0
                },
                "default_currency": "EUR",
                "expected_delivery_time": "2025-09-27T22:00:00Z",
                "id": "93d86720-6690-42dd-ad74-abff00ede808",
                "internal_id": "PO-2025/0066",
                "name": "Arke 2025/09/23",
                "status": "accepted",
                "supplier_attr": {
                    "id": "bcdb6a1b-3dd4-4204-89d8-0349181a73bc",
                    "name": "Arke",
                    "vat": "1234567890"
                },
                "time": "2025-09-23T13:39:41.185Z",
                "total_vat_incl": 6.1,
                "warehouse_attr": {
                    "id": "c6c13283-d4f7-488b-af73-2f54cdb29c4d",
                    "name": "Main warehouse"
                },
                "warehouse_id": "c6c13283-d4f7-488b-af73-2f54cdb29c4d"
            },
            {
                "buckets": {
                    "inbound": 1,
                    "inStock": 0,
                    "inUse": 0,
                    "consumed": 0,
                    "discarded": 0
                },
                "default_currency": "EUR",
                "expected_delivery_time": "2025-09-25T22:00:00Z",
                "id": "f51a08ce-ed74-4665-9251-d21980e5636b",
                "internal_id": "PO-2025/0065",
                "name": "Arke 2025/09/23",
                "status": "accepted",
                "supplier_attr": {
                    "id": "bcdb6a1b-3dd4-4204-89d8-0349181a73bc",
                    "name": "Arke",
                    "vat": "1234567890"
                },
                "time": "2025-09-23T13:31:13.344Z",
                "total_vat_incl": 6.1,
                "warehouse_attr": {
                    "id": "c6c13283-d4f7-488b-af73-2f54cdb29c4d",
                    "name": "Main warehouse"
                },
                "warehouse_id": "c6c13283-d4f7-488b-af73-2f54cdb29c4d"
            },
            {
                "buckets": {
                    "inbound": 1,
                    "inStock": 0,
                    "inUse": 0,
                    "consumed": 0,
                    "discarded": 0
                },
                "default_currency": "EUR",
                "expected_delivery_time": "2025-09-24T22:00:00Z",
                "id": "327589a5-df38-4188-bc94-f2816933ddec",
                "internal_id": "PO-2025/0067",
                "name": "Arke 2025/09/23",
                "status": "sent",
                "supplier_attr": {
                    "id": "bcdb6a1b-3dd4-4204-89d8-0349181a73bc",
                    "name": "Arke",
                    "vat": "1234567890"
                },
                "time": "2025-09-23T13:40:43.275245Z",
                "total_vat_incl": 6.1,
                "warehouse_attr": {
                    "id": "c6c13283-d4f7-488b-af73-2f54cdb29c4d",
                    "name": "Main warehouse"
                },
                "warehouse_id": "c6c13283-d4f7-488b-af73-2f54cdb29c4d"
            },
            {
                "buckets": {
                    "inbound": 1,
                    "inStock": 0,
                    "inUse": 0,
                    "consumed": 0,
                    "discarded": 0
                },
                "default_currency": "EUR",
                "expected_delivery_time": "2025-10-08T22:00:00Z",
                "id": "1d10da7d-e98f-4299-aa9c-66b3832a5c70",
                "internal_id": "PO-2025/0071",
                "name": "Acme Inc 2025/10/09",
                "status": "accepted",
                "supplier_attr": {
                    "id": "fd350ff9-e8fa-41b3-8801-d79b2ec4e805",
                    "name": "Acme Inc",
                    "vat": "11111222233334444"
                },
                "time": "2025-10-09T15:53:42.238Z",
                "total_vat_incl": 36.6,
                "warehouse_attr": {
                    "id": "c6c13283-d4f7-488b-af73-2f54cdb29c4d",
                    "name": "Main warehouse"
                },
                "warehouse_id": "c6c13283-d4f7-488b-af73-2f54cdb29c4d"
            },
            {
                "buckets": {
                    "inbound": 1,
                    "inStock": 0,
                    "inUse": 0,
                    "consumed": 0,
                    "discarded": 0
                },
                "default_currency": "EUR",
                "expected_delivery_time": "2025-10-09T22:00:00Z",
                "id": "4ee27125-f120-4a1a-9a6b-3f1de7e75f99",
                "internal_id": "PO-2025/0074",
                "name": "Acme Inc 2025/10/10",
                "status": "accepted",
                "supplier_attr": {
                    "id": "fd350ff9-e8fa-41b3-8801-d79b2ec4e805",
                    "name": "Acme Inc",
                    "vat": "11111222233334444"
                },
                "time": "2025-10-10T14:28:45.046Z",
                "total_vat_incl": 36.6,
                "warehouse_attr": {
                    "id": "c6c13283-d4f7-488b-af73-2f54cdb29c4d",
                    "name": "Main warehouse"
                },
                "warehouse_id": "c6c13283-d4f7-488b-af73-2f54cdb29c4d"
            }
        ]
    }

    /**
     * lists the orders
     */
    async listOrdersRaw(requestParameters: ListOrdersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<OrderSummary>>> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['query'] != null) {
            queryParameters['query'] = requestParameters['query'];
        }

        if (requestParameters['from'] != null) {
            queryParameters['from'] = (requestParameters['from'] as any).toISOString();
        }

        if (requestParameters['to'] != null) {
            queryParameters['to'] = (requestParameters['to'] as any).toISOString();
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/order`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(OrderSummaryFromJSON));
    }

    /**
     * lists the orders
     */
    async listOrders(requestParameters: ListOrdersRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<OrderSummary>> {
        const response = await this.listOrdersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * lists the orders for the given supplier
     */
    async listOrdersBySupplierRaw(requestParameters: ListOrdersBySupplierRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<OrderSummary>>> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        if (requestParameters['archived'] != null) {
            queryParameters['archived'] = requestParameters['archived'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['query'] != null) {
            queryParameters['query'] = requestParameters['query'];
        }

        if (requestParameters['from'] != null) {
            queryParameters['from'] = (requestParameters['from'] as any).toISOString();
        }

        if (requestParameters['to'] != null) {
            queryParameters['to'] = (requestParameters['to'] as any).toISOString();
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/supplier/{supplierId}/order`.replace(`{${"supplierId"}}`, encodeURIComponent(String(requestParameters['supplierId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(OrderSummaryFromJSON));
    }

    /**
     * lists the orders for the given supplier
     */
    async listOrdersBySupplier(requestParameters: ListOrdersBySupplierRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<OrderSummary>> {
        const response = await this.listOrdersBySupplierRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Flags an order as rejected by the supplier.
     * flags an order as rejected
     */
    async rejectOrderRaw(requestParameters: RejectOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrderDetails>> {
        if (requestParameters['orderId'] == null) {
            throw new runtime.RequiredError(
                'orderId',
                'Required parameter "orderId" was null or undefined when calling rejectOrder().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/order/{orderId}/_reject`.replace(`{${"orderId"}}`, encodeURIComponent(String(requestParameters['orderId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrderDetailsFromJSON(jsonValue));
    }

    /**
     * Flags an order as rejected by the supplier.
     * flags an order as rejected
     */
    async rejectOrder(requestParameters: RejectOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrderDetails> {
        const response = await this.rejectOrderRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * sends an order
     * sends an order
     */
    async sendOrderRaw(requestParameters: SendOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SendOrderCommand>> {
        if (requestParameters['orderId'] == null) {
            throw new runtime.RequiredError(
                'orderId',
                'Required parameter "orderId" was null or undefined when calling sendOrder().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/order/{orderId}/_send`.replace(`{${"orderId"}}`, encodeURIComponent(String(requestParameters['orderId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SendOrderCommandFromJSON(jsonValue));
    }

    /**
     * sends an order
     * sends an order
     */
    async sendOrder(requestParameters: SendOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SendOrderCommand> {
        const response = await this.sendOrderRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * shows an order
     */
    async showOrderRaw(requestParameters: ShowOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrderDetails>> {
        if (requestParameters['orderId'] == null) {
            throw new runtime.RequiredError(
                'orderId',
                'Required parameter "orderId" was null or undefined when calling showOrder().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/order/{orderId}`.replace(`{${"orderId"}}`, encodeURIComponent(String(requestParameters['orderId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrderDetailsFromJSON(jsonValue));
    }

    /**
     * shows an order
     */
    async showOrder(requestParameters: ShowOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrderDetails> {
        const response = await this.showOrderRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * updates an order
     */
    async updateOrderRaw(requestParameters: UpdateOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrderDetails>> {
        if (requestParameters['orderId'] == null) {
            throw new runtime.RequiredError(
                'orderId',
                'Required parameter "orderId" was null or undefined when calling updateOrder().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/order/{orderId}`.replace(`{${"orderId"}}`, encodeURIComponent(String(requestParameters['orderId']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: OrderDetailsToJSON(requestParameters['orderDetails']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrderDetailsFromJSON(jsonValue));
    }

    /**
     * updates an order
     */
    async updateOrder(requestParameters: UpdateOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrderDetails> {
        const response = await this.updateOrderRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
