/* tslint:disable */
/* eslint-disable */
/**
 * Arke Supply API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddressAttr
 */
export interface AddressAttr {
    /**
     * 
     * @type {string}
     * @memberof AddressAttr
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof AddressAttr
     */
    address: string;
    /**
     * 
     * @type {string}
     * @memberof AddressAttr
     */
    country: string;
}

/**
 * Check if a given object implements the AddressAttr interface.
 */
export function instanceOfAddressAttr(value: object): value is AddressAttr {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('address' in value) || value['address'] === undefined) return false;
    if (!('country' in value) || value['country'] === undefined) return false;
    return true;
}

export function AddressAttrFromJSON(json: any): AddressAttr {
    return AddressAttrFromJSONTyped(json, false);
}

export function AddressAttrFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddressAttr {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'address': json['address'],
        'country': json['country'],
    };
}

export function AddressAttrToJSON(json: any): AddressAttr {
    return AddressAttrToJSONTyped(json, false);
}

export function AddressAttrToJSONTyped(value?: AddressAttr | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'address': value['address'],
        'country': value['country'],
    };
}

