/* tslint:disable */
/* eslint-disable */
/**
 * Arke Supply API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BankAttr
 */
export interface BankAttr {
    /**
     * 
     * @type {string}
     * @memberof BankAttr
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof BankAttr
     */
    iban?: string;
    /**
     * 
     * @type {string}
     * @memberof BankAttr
     */
    swift?: string;
}

/**
 * Check if a given object implements the BankAttr interface.
 */
export function instanceOfBankAttr(value: object): value is BankAttr {
    return true;
}

export function BankAttrFromJSON(json: any): BankAttr {
    return BankAttrFromJSONTyped(json, false);
}

export function BankAttrFromJSONTyped(json: any, ignoreDiscriminator: boolean): BankAttr {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'iban': json['iban'] == null ? undefined : json['iban'],
        'swift': json['swift'] == null ? undefined : json['swift'],
    };
}

export function BankAttrToJSON(json: any): BankAttr {
    return BankAttrToJSONTyped(json, false);
}

export function BankAttrToJSONTyped(value?: BankAttr | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'iban': value['iban'],
        'swift': value['swift'],
    };
}

