/* tslint:disable */
/* eslint-disable */
/**
 * Arke Supply API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CompanyAttr1
 */
export interface CompanyAttr1 {
    /**
     * 
     * @type {string}
     * @memberof CompanyAttr1
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyAttr1
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyAttr1
     */
    address?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyAttr1
     */
    vat: string;
}

/**
 * Check if a given object implements the CompanyAttr1 interface.
 */
export function instanceOfCompanyAttr1(value: object): value is CompanyAttr1 {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('vat' in value) || value['vat'] === undefined) return false;
    return true;
}

export function CompanyAttr1FromJSON(json: any): CompanyAttr1 {
    return CompanyAttr1FromJSONTyped(json, false);
}

export function CompanyAttr1FromJSONTyped(json: any, ignoreDiscriminator: boolean): CompanyAttr1 {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
        'address': json['address'] == null ? undefined : json['address'],
        'vat': json['vat'],
    };
}

export function CompanyAttr1ToJSON(value?: CompanyAttr1 | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'address': value['address'],
        'vat': value['vat'],
    };
}

