/* tslint:disable */
/* eslint-disable */
/**
 * Arke Supply API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { QuantifiedItem } from './QuantifiedItem';
import {
    QuantifiedItemFromJSON,
    QuantifiedItemFromJSONTyped,
    QuantifiedItemToJSON,
    QuantifiedItemToJSONTyped,
} from './QuantifiedItem';

/**
 * 
 * @export
 * @interface ComputeMultiAvailabilityItem
 */
export interface ComputeMultiAvailabilityItem {
    /**
     * 
     * @type {Array<QuantifiedItem>}
     * @memberof ComputeMultiAvailabilityItem
     */
    materials: Array<QuantifiedItem>;
    /**
     * 
     * @type {number}
     * @memberof ComputeMultiAvailabilityItem
     */
    quantity: number;
}

/**
 * Check if a given object implements the ComputeMultiAvailabilityItem interface.
 */
export function instanceOfComputeMultiAvailabilityItem(value: object): value is ComputeMultiAvailabilityItem {
    if (!('materials' in value) || value['materials'] === undefined) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    return true;
}

export function ComputeMultiAvailabilityItemFromJSON(json: any): ComputeMultiAvailabilityItem {
    return ComputeMultiAvailabilityItemFromJSONTyped(json, false);
}

export function ComputeMultiAvailabilityItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): ComputeMultiAvailabilityItem {
    if (json == null) {
        return json;
    }
    return {
        
        'materials': ((json['materials'] as Array<any>).map(QuantifiedItemFromJSON)),
        'quantity': json['quantity'],
    };
}

export function ComputeMultiAvailabilityItemToJSON(json: any): ComputeMultiAvailabilityItem {
    return ComputeMultiAvailabilityItemToJSONTyped(json, false);
}

export function ComputeMultiAvailabilityItemToJSONTyped(value?: ComputeMultiAvailabilityItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'materials': ((value['materials'] as Array<any>).map(QuantifiedItemToJSON)),
        'quantity': value['quantity'],
    };
}

