/* tslint:disable */
/* eslint-disable */
/**
 * Arke Supply API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GroupedRawMaterialInventoryItemSummaryWarehouseAttr
 */
export interface GroupedRawMaterialInventoryItemSummaryWarehouseAttr {
    /**
     * 
     * @type {string}
     * @memberof GroupedRawMaterialInventoryItemSummaryWarehouseAttr
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof GroupedRawMaterialInventoryItemSummaryWarehouseAttr
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof GroupedRawMaterialInventoryItemSummaryWarehouseAttr
     */
    supplierId?: string;
}

/**
 * Check if a given object implements the GroupedRawMaterialInventoryItemSummaryWarehouseAttr interface.
 */
export function instanceOfGroupedRawMaterialInventoryItemSummaryWarehouseAttr(value: object): value is GroupedRawMaterialInventoryItemSummaryWarehouseAttr {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function GroupedRawMaterialInventoryItemSummaryWarehouseAttrFromJSON(json: any): GroupedRawMaterialInventoryItemSummaryWarehouseAttr {
    return GroupedRawMaterialInventoryItemSummaryWarehouseAttrFromJSONTyped(json, false);
}

export function GroupedRawMaterialInventoryItemSummaryWarehouseAttrFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupedRawMaterialInventoryItemSummaryWarehouseAttr {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'supplierId': json['supplier_id'] == null ? undefined : json['supplier_id'],
    };
}

export function GroupedRawMaterialInventoryItemSummaryWarehouseAttrToJSON(json: any): GroupedRawMaterialInventoryItemSummaryWarehouseAttr {
    return GroupedRawMaterialInventoryItemSummaryWarehouseAttrToJSONTyped(json, false);
}

export function GroupedRawMaterialInventoryItemSummaryWarehouseAttrToJSONTyped(value?: GroupedRawMaterialInventoryItemSummaryWarehouseAttr | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'supplier_id': value['supplierId'],
    };
}

