/* tslint:disable */
/* eslint-disable */
/**
 * Arke Supply API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CompanyAttr } from './CompanyAttr';
import {
    CompanyAttrFromJSON,
    CompanyAttrFromJSONTyped,
    CompanyAttrToJSON,
    CompanyAttrToJSONTyped,
} from './CompanyAttr';

/**
 * 
 * @export
 * @interface InvoiceSummary
 */
export interface InvoiceSummary {
    /**
     * 
     * @type {string}
     * @memberof InvoiceSummary
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceSummary
     */
    externalId: string;
    /**
     * 
     * @type {Date}
     * @memberof InvoiceSummary
     */
    time: Date;
    /**
     * 
     * @type {CompanyAttr}
     * @memberof InvoiceSummary
     */
    supplierAttr: CompanyAttr;
    /**
     * 
     * @type {string}
     * @memberof InvoiceSummary
     */
    status: InvoiceSummaryStatusEnum;
}


/**
 * @export
 */
export const InvoiceSummaryStatusEnum = {
    Inbound: 'inbound',
    Verified: 'verified',
    Paid: 'paid'
} as const;
export type InvoiceSummaryStatusEnum = typeof InvoiceSummaryStatusEnum[keyof typeof InvoiceSummaryStatusEnum];


/**
 * Check if a given object implements the InvoiceSummary interface.
 */
export function instanceOfInvoiceSummary(value: object): value is InvoiceSummary {
    if (!('externalId' in value) || value['externalId'] === undefined) return false;
    if (!('time' in value) || value['time'] === undefined) return false;
    if (!('supplierAttr' in value) || value['supplierAttr'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function InvoiceSummaryFromJSON(json: any): InvoiceSummary {
    return InvoiceSummaryFromJSONTyped(json, false);
}

export function InvoiceSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvoiceSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'externalId': json['external_id'],
        'time': (new Date(json['time'])),
        'supplierAttr': CompanyAttrFromJSON(json['supplier_attr']),
        'status': json['status'],
    };
}

export function InvoiceSummaryToJSON(json: any): InvoiceSummary {
    return InvoiceSummaryToJSONTyped(json, false);
}

export function InvoiceSummaryToJSONTyped(value?: InvoiceSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'external_id': value['externalId'],
        'time': ((value['time']).toISOString()),
        'supplier_attr': CompanyAttrToJSON(value['supplierAttr']),
        'status': value['status'],
    };
}

