/* tslint:disable */
/* eslint-disable */
/**
 * Arke Supply API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WarehouseAttr } from './WarehouseAttr';
import {
    WarehouseAttrFromJSON,
    WarehouseAttrFromJSONTyped,
    WarehouseAttrToJSON,
    WarehouseAttrToJSONTyped,
} from './WarehouseAttr';
import type { RawMaterialInventoryBuckets } from './RawMaterialInventoryBuckets';
import {
    RawMaterialInventoryBucketsFromJSON,
    RawMaterialInventoryBucketsFromJSONTyped,
    RawMaterialInventoryBucketsToJSON,
    RawMaterialInventoryBucketsToJSONTyped,
} from './RawMaterialInventoryBuckets';
import type { CompanyAttr } from './CompanyAttr';
import {
    CompanyAttrFromJSON,
    CompanyAttrFromJSONTyped,
    CompanyAttrToJSON,
    CompanyAttrToJSONTyped,
} from './CompanyAttr';

/**
 * 
 * @export
 * @interface OrderSummary
 */
export interface OrderSummary {
    /**
     * 
     * @type {string}
     * @memberof OrderSummary
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderSummary
     */
    internalId?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderSummary
     */
    name: string;
    /**
     * 
     * @type {Date}
     * @memberof OrderSummary
     */
    time?: Date;
    /**
     * 
     * @type {Date}
     * @memberof OrderSummary
     */
    expectedDeliveryTime: Date;
    /**
     * 
     * @type {CompanyAttr}
     * @memberof OrderSummary
     */
    supplierAttr?: CompanyAttr;
    /**
     * 
     * @type {string}
     * @memberof OrderSummary
     */
    status: OrderSummaryStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof OrderSummary
     */
    defaultCurrency?: string;
    /**
     * 
     * @type {number}
     * @memberof OrderSummary
     */
    totalVatIncl: number;
    /**
     * 
     * @type {RawMaterialInventoryBuckets}
     * @memberof OrderSummary
     */
    buckets?: RawMaterialInventoryBuckets;
    /**
     * 
     * @type {WarehouseAttr}
     * @memberof OrderSummary
     */
    warehouseAttr?: WarehouseAttr;
    /**
     * 
     * @type {string}
     * @memberof OrderSummary
     */
    warehouseId?: string;
}


/**
 * @export
 */
export const OrderSummaryStatusEnum = {
    Draft: 'draft',
    Sent: 'sent',
    Accepted: 'accepted',
    Shipped: 'shipped',
    Rejected: 'rejected'
} as const;
export type OrderSummaryStatusEnum = typeof OrderSummaryStatusEnum[keyof typeof OrderSummaryStatusEnum];


/**
 * Check if a given object implements the OrderSummary interface.
 */
export function instanceOfOrderSummary(value: object): value is OrderSummary {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('expectedDeliveryTime' in value) || value['expectedDeliveryTime'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('totalVatIncl' in value) || value['totalVatIncl'] === undefined) return false;
    return true;
}

export function OrderSummaryFromJSON(json: any): OrderSummary {
    return OrderSummaryFromJSONTyped(json, false);
}

export function OrderSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'internalId': json['internal_id'] == null ? undefined : json['internal_id'],
        'name': json['name'],
        'time': json['time'] == null ? undefined : (new Date(json['time'])),
        'expectedDeliveryTime': (new Date(json['expected_delivery_time'])),
        'supplierAttr': json['supplier_attr'] == null ? undefined : CompanyAttrFromJSON(json['supplier_attr']),
        'status': json['status'],
        'defaultCurrency': json['default_currency'] == null ? undefined : json['default_currency'],
        'totalVatIncl': json['total_vat_incl'],
        'buckets': json['buckets'] == null ? undefined : RawMaterialInventoryBucketsFromJSON(json['buckets']),
        'warehouseAttr': json['warehouse_attr'] == null ? undefined : WarehouseAttrFromJSON(json['warehouse_attr']),
        'warehouseId': json['warehouse_id'] == null ? undefined : json['warehouse_id'],
    };
}

export function OrderSummaryToJSON(json: any): OrderSummary {
    return OrderSummaryToJSONTyped(json, false);
}

export function OrderSummaryToJSONTyped(value?: OrderSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'internal_id': value['internalId'],
        'name': value['name'],
        'time': value['time'] == null ? undefined : ((value['time']).toISOString()),
        'expected_delivery_time': ((value['expectedDeliveryTime']).toISOString()),
        'supplier_attr': CompanyAttrToJSON(value['supplierAttr']),
        'status': value['status'],
        'default_currency': value['defaultCurrency'],
        'total_vat_incl': value['totalVatIncl'],
        'buckets': RawMaterialInventoryBucketsToJSON(value['buckets']),
        'warehouse_attr': WarehouseAttrToJSON(value['warehouseAttr']),
        'warehouse_id': value['warehouseId'],
    };
}

