/* tslint:disable */
/* eslint-disable */
/**
 * Arke Supply API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CompanyAttr } from './CompanyAttr';
import {
    CompanyAttrFromJSON,
    CompanyAttrFromJSONTyped,
    CompanyAttrToJSON,
    CompanyAttrToJSONTyped,
} from './CompanyAttr';

/**
 * 
 * @export
 * @interface OrderStats
 */
export interface OrderStats {
    /**
     * 
     * @type {number}
     * @memberof OrderStats
     */
    thirtyDayValue: number;
    /**
     * 
     * @type {number}
     * @memberof OrderStats
     */
    unapprovedOrdersCount: number;
    /**
     * 
     * @type {CompanyAttr}
     * @memberof OrderStats
     */
    mostUtilizedSupplierCurrentMonth: CompanyAttr;
}

/**
 * Check if a given object implements the OrderStats interface.
 */
export function instanceOfOrderStats(value: object): value is OrderStats {
    if (!('thirtyDayValue' in value) || value['thirtyDayValue'] === undefined) return false;
    if (!('unapprovedOrdersCount' in value) || value['unapprovedOrdersCount'] === undefined) return false;
    if (!('mostUtilizedSupplierCurrentMonth' in value) || value['mostUtilizedSupplierCurrentMonth'] === undefined) return false;
    return true;
}

export function OrderStatsFromJSON(json: any): OrderStats {
    return OrderStatsFromJSONTyped(json, false);
}

export function OrderStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderStats {
    if (json == null) {
        return json;
    }
    return {
        
        'thirtyDayValue': json['thirty_day_value'],
        'unapprovedOrdersCount': json['unapproved_orders_count'],
        'mostUtilizedSupplierCurrentMonth': CompanyAttrFromJSON(json['most_utilized_supplier_current_month']),
    };
}

export function OrderStatsToJSON(json: any): OrderStats {
    return OrderStatsToJSONTyped(json, false);
}

export function OrderStatsToJSONTyped(value?: OrderStats | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'thirty_day_value': value['thirtyDayValue'],
        'unapproved_orders_count': value['unapprovedOrdersCount'],
        'most_utilized_supplier_current_month': CompanyAttrToJSON(value['mostUtilizedSupplierCurrentMonth']),
    };
}

