/* tslint:disable */
/* eslint-disable */
/**
 * Arke Supply API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CompanyAttr } from './CompanyAttr';
import {
    CompanyAttrFromJSON,
    CompanyAttrFromJSONTyped,
    CompanyAttrToJSON,
    CompanyAttrToJSONTyped,
} from './CompanyAttr';

/**
 * 
 * @export
 * @interface OutboundTransportDocumentSummary
 */
export interface OutboundTransportDocumentSummary {
    /**
     * 
     * @type {string}
     * @memberof OutboundTransportDocumentSummary
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof OutboundTransportDocumentSummary
     */
    internalId?: string;
    /**
     * 
     * @type {string}
     * @memberof OutboundTransportDocumentSummary
     */
    status: OutboundTransportDocumentSummaryStatusEnum;
    /**
     * 
     * @type {Date}
     * @memberof OutboundTransportDocumentSummary
     */
    time?: Date;
    /**
     * 
     * @type {CompanyAttr}
     * @memberof OutboundTransportDocumentSummary
     */
    supplierAttr?: CompanyAttr;
}


/**
 * @export
 */
export const OutboundTransportDocumentSummaryStatusEnum = {
    Draft: 'draft',
    Accepted: 'accepted'
} as const;
export type OutboundTransportDocumentSummaryStatusEnum = typeof OutboundTransportDocumentSummaryStatusEnum[keyof typeof OutboundTransportDocumentSummaryStatusEnum];


/**
 * Check if a given object implements the OutboundTransportDocumentSummary interface.
 */
export function instanceOfOutboundTransportDocumentSummary(value: object): value is OutboundTransportDocumentSummary {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function OutboundTransportDocumentSummaryFromJSON(json: any): OutboundTransportDocumentSummary {
    return OutboundTransportDocumentSummaryFromJSONTyped(json, false);
}

export function OutboundTransportDocumentSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): OutboundTransportDocumentSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'internalId': json['internal_id'] == null ? undefined : json['internal_id'],
        'status': json['status'],
        'time': json['time'] == null ? undefined : (new Date(json['time'])),
        'supplierAttr': json['supplier_attr'] == null ? undefined : CompanyAttrFromJSON(json['supplier_attr']),
    };
}

export function OutboundTransportDocumentSummaryToJSON(json: any): OutboundTransportDocumentSummary {
    return OutboundTransportDocumentSummaryToJSONTyped(json, false);
}

export function OutboundTransportDocumentSummaryToJSONTyped(value?: OutboundTransportDocumentSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'internal_id': value['internalId'],
        'status': value['status'],
        'time': value['time'] == null ? undefined : ((value['time']).toISOString()),
        'supplier_attr': CompanyAttrToJSON(value['supplierAttr']),
    };
}

