/* tslint:disable */
/* eslint-disable */
/**
 * Arke Supply API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DateAttr } from './DateAttr';
import {
    DateAttrFromJSON,
    DateAttrFromJSONTyped,
    DateAttrToJSON,
    DateAttrToJSONTyped,
} from './DateAttr';
import type { CustomFormValues } from './CustomFormValues';
import {
    CustomFormValuesFromJSON,
    CustomFormValuesFromJSONTyped,
    CustomFormValuesToJSON,
    CustomFormValuesToJSONTyped,
} from './CustomFormValues';
import type { QuantifiedItem } from './QuantifiedItem';
import {
    QuantifiedItemFromJSON,
    QuantifiedItemFromJSONTyped,
    QuantifiedItemToJSON,
    QuantifiedItemToJSONTyped,
} from './QuantifiedItem';
import type { CompanyAttr } from './CompanyAttr';
import {
    CompanyAttrFromJSON,
    CompanyAttrFromJSONTyped,
    CompanyAttrToJSON,
    CompanyAttrToJSONTyped,
} from './CompanyAttr';

/**
 * 
 * @export
 * @interface OutboundTransportDocumentDetails
 */
export interface OutboundTransportDocumentDetails {
    /**
     * 
     * @type {DateAttr}
     * @memberof OutboundTransportDocumentDetails
     */
    created?: DateAttr;
    /**
     * 
     * @type {DateAttr}
     * @memberof OutboundTransportDocumentDetails
     */
    updated?: DateAttr;
    /**
     * 
     * @type {number}
     * @memberof OutboundTransportDocumentDetails
     */
    version: number;
    /**
     * 
     * @type {boolean}
     * @memberof OutboundTransportDocumentDetails
     */
    archived?: boolean;
    /**
     * 
     * @type {string}
     * @memberof OutboundTransportDocumentDetails
     */
    notes?: string;
    /**
     * 
     * @type {CustomFormValues}
     * @memberof OutboundTransportDocumentDetails
     */
    customFormValues?: CustomFormValues;
    /**
     * 
     * @type {object}
     * @memberof OutboundTransportDocumentDetails
     */
    foreignIds?: object;
    /**
     * 
     * @type {string}
     * @memberof OutboundTransportDocumentDetails
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof OutboundTransportDocumentDetails
     */
    internalId?: string;
    /**
     * 
     * @type {string}
     * @memberof OutboundTransportDocumentDetails
     */
    status: OutboundTransportDocumentDetailsStatusEnum;
    /**
     * 
     * @type {Date}
     * @memberof OutboundTransportDocumentDetails
     */
    time?: Date;
    /**
     * 
     * @type {CompanyAttr}
     * @memberof OutboundTransportDocumentDetails
     */
    supplierAttr?: CompanyAttr;
    /**
     * 
     * @type {number}
     * @memberof OutboundTransportDocumentDetails
     */
    weight?: number;
    /**
     * 
     * @type {Array<QuantifiedItem>}
     * @memberof OutboundTransportDocumentDetails
     */
    rawMaterials: Array<QuantifiedItem>;
    /**
     * 
     * @type {string}
     * @memberof OutboundTransportDocumentDetails
     */
    supplierId?: string;
    /**
     * 
     * @type {string}
     * @memberof OutboundTransportDocumentDetails
     */
    shippingAddress: string;
    /**
     * 
     * @type {string}
     * @memberof OutboundTransportDocumentDetails
     */
    carrier?: string;
    /**
     * 
     * @type {string}
     * @memberof OutboundTransportDocumentDetails
     */
    reason?: string;
}


/**
 * @export
 */
export const OutboundTransportDocumentDetailsStatusEnum = {
    Draft: 'draft',
    Accepted: 'accepted'
} as const;
export type OutboundTransportDocumentDetailsStatusEnum = typeof OutboundTransportDocumentDetailsStatusEnum[keyof typeof OutboundTransportDocumentDetailsStatusEnum];


/**
 * Check if a given object implements the OutboundTransportDocumentDetails interface.
 */
export function instanceOfOutboundTransportDocumentDetails(value: object): value is OutboundTransportDocumentDetails {
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('rawMaterials' in value) || value['rawMaterials'] === undefined) return false;
    if (!('shippingAddress' in value) || value['shippingAddress'] === undefined) return false;
    return true;
}

export function OutboundTransportDocumentDetailsFromJSON(json: any): OutboundTransportDocumentDetails {
    return OutboundTransportDocumentDetailsFromJSONTyped(json, false);
}

export function OutboundTransportDocumentDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): OutboundTransportDocumentDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'created': json['created'] == null ? undefined : DateAttrFromJSON(json['created']),
        'updated': json['updated'] == null ? undefined : DateAttrFromJSON(json['updated']),
        'version': json['version'],
        'archived': json['archived'] == null ? undefined : json['archived'],
        'notes': json['notes'] == null ? undefined : json['notes'],
        'customFormValues': json['custom_form_values'] == null ? undefined : CustomFormValuesFromJSON(json['custom_form_values']),
        'foreignIds': json['foreign_ids'] == null ? undefined : json['foreign_ids'],
        'id': json['id'] == null ? undefined : json['id'],
        'internalId': json['internal_id'] == null ? undefined : json['internal_id'],
        'status': json['status'],
        'time': json['time'] == null ? undefined : (new Date(json['time'])),
        'supplierAttr': json['supplier_attr'] == null ? undefined : CompanyAttrFromJSON(json['supplier_attr']),
        'weight': json['weight'] == null ? undefined : json['weight'],
        'rawMaterials': ((json['raw_materials'] as Array<any>).map(QuantifiedItemFromJSON)),
        'supplierId': json['supplier_id'] == null ? undefined : json['supplier_id'],
        'shippingAddress': json['shipping_address'],
        'carrier': json['carrier'] == null ? undefined : json['carrier'],
        'reason': json['reason'] == null ? undefined : json['reason'],
    };
}

export function OutboundTransportDocumentDetailsToJSON(json: any): OutboundTransportDocumentDetails {
    return OutboundTransportDocumentDetailsToJSONTyped(json, false);
}

export function OutboundTransportDocumentDetailsToJSONTyped(value?: OutboundTransportDocumentDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created': DateAttrToJSON(value['created']),
        'updated': DateAttrToJSON(value['updated']),
        'version': value['version'],
        'archived': value['archived'],
        'notes': value['notes'],
        'custom_form_values': CustomFormValuesToJSON(value['customFormValues']),
        'foreign_ids': value['foreignIds'],
        'id': value['id'],
        'internal_id': value['internalId'],
        'status': value['status'],
        'time': value['time'] == null ? undefined : ((value['time']).toISOString()),
        'supplier_attr': CompanyAttrToJSON(value['supplierAttr']),
        'weight': value['weight'],
        'raw_materials': ((value['rawMaterials'] as Array<any>).map(QuantifiedItemToJSON)),
        'supplier_id': value['supplierId'],
        'shipping_address': value['shippingAddress'],
        'carrier': value['carrier'],
        'reason': value['reason'],
    };
}

