/* tslint:disable */
/* eslint-disable */
/**
 * Arke Supply API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PricesDealsInner
 */
export interface PricesDealsInner {
    /**
     * 
     * @type {number}
     * @memberof PricesDealsInner
     */
    minQuantity: number;
    /**
     * 
     * @type {number}
     * @memberof PricesDealsInner
     */
    unit: number;
}

/**
 * Check if a given object implements the PricesDealsInner interface.
 */
export function instanceOfPricesDealsInner(value: object): value is PricesDealsInner {
    if (!('minQuantity' in value) || value['minQuantity'] === undefined) return false;
    if (!('unit' in value) || value['unit'] === undefined) return false;
    return true;
}

export function PricesDealsInnerFromJSON(json: any): PricesDealsInner {
    return PricesDealsInnerFromJSONTyped(json, false);
}

export function PricesDealsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PricesDealsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'minQuantity': json['min_quantity'],
        'unit': json['unit'],
    };
}

export function PricesDealsInnerToJSON(value?: PricesDealsInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'min_quantity': value['minQuantity'],
        'unit': value['unit'],
    };
}

