/* tslint:disable */
/* eslint-disable */
/**
 * Arke Supply API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RawMaterialMatchRequestItem
 */
export interface RawMaterialMatchRequestItem {
    /**
     * 
     * @type {string}
     * @memberof RawMaterialMatchRequestItem
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof RawMaterialMatchRequestItem
     */
    extraId?: string;
    /**
     * 
     * @type {string}
     * @memberof RawMaterialMatchRequestItem
     */
    name?: string;
}

/**
 * Check if a given object implements the RawMaterialMatchRequestItem interface.
 */
export function instanceOfRawMaterialMatchRequestItem(value: object): value is RawMaterialMatchRequestItem {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function RawMaterialMatchRequestItemFromJSON(json: any): RawMaterialMatchRequestItem {
    return RawMaterialMatchRequestItemFromJSONTyped(json, false);
}

export function RawMaterialMatchRequestItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): RawMaterialMatchRequestItem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'extraId': json['extra_id'] == null ? undefined : json['extra_id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function RawMaterialMatchRequestItemToJSON(json: any): RawMaterialMatchRequestItem {
    return RawMaterialMatchRequestItemToJSONTyped(json, false);
}

export function RawMaterialMatchRequestItemToJSONTyped(value?: RawMaterialMatchRequestItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'extra_id': value['extraId'],
        'name': value['name'],
    };
}

