/* tslint:disable */
/* eslint-disable */
/**
 * Arke Supply API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RawMaterialInventory
 */
export interface RawMaterialInventory {
    /**
     * 
     * @type {number}
     * @memberof RawMaterialInventory
     */
    inbound?: number;
    /**
     * 
     * @type {number}
     * @memberof RawMaterialInventory
     */
    inStock?: number;
    /**
     * 
     * @type {number}
     * @memberof RawMaterialInventory
     */
    inUse?: number;
    /**
     * 
     * @type {number}
     * @memberof RawMaterialInventory
     */
    ordered?: number;
    /**
     * 
     * @type {number}
     * @memberof RawMaterialInventory
     */
    needed?: number;
    /**
     * 
     * @type {number}
     * @memberof RawMaterialInventory
     */
    missing?: number;
}

/**
 * Check if a given object implements the RawMaterialInventory interface.
 */
export function instanceOfRawMaterialInventory(value: object): value is RawMaterialInventory {
    return true;
}

export function RawMaterialInventoryFromJSON(json: any): RawMaterialInventory {
    return RawMaterialInventoryFromJSONTyped(json, false);
}

export function RawMaterialInventoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): RawMaterialInventory {
    if (json == null) {
        return json;
    }
    return {
        
        'inbound': json['inbound'] == null ? undefined : json['inbound'],
        'inStock': json['in_stock'] == null ? undefined : json['in_stock'],
        'inUse': json['in_use'] == null ? undefined : json['in_use'],
        'ordered': json['ordered'] == null ? undefined : json['ordered'],
        'needed': json['needed'] == null ? undefined : json['needed'],
        'missing': json['missing'] == null ? undefined : json['missing'],
    };
}

export function RawMaterialInventoryToJSON(json: any): RawMaterialInventory {
    return RawMaterialInventoryToJSONTyped(json, false);
}

export function RawMaterialInventoryToJSONTyped(value?: RawMaterialInventory | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'inbound': value['inbound'],
        'in_stock': value['inStock'],
        'in_use': value['inUse'],
        'ordered': value['ordered'],
        'needed': value['needed'],
        'missing': value['missing'],
    };
}

