/* tslint:disable */
/* eslint-disable */
/**
 * Arke Supply API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WarehouseAttr } from './WarehouseAttr';
import {
    WarehouseAttrFromJSON,
    WarehouseAttrFromJSONTyped,
    WarehouseAttrToJSON,
    WarehouseAttrToJSONTyped,
} from './WarehouseAttr';

/**
 * 
 * @export
 * @interface RawMaterialInventoryAdjustment
 */
export interface RawMaterialInventoryAdjustment {
    /**
     * 
     * @type {string}
     * @memberof RawMaterialInventoryAdjustment
     */
    bucket?: string;
    /**
     * 
     * @type {number}
     * @memberof RawMaterialInventoryAdjustment
     */
    quantity: number;
    /**
     * 
     * @type {string}
     * @memberof RawMaterialInventoryAdjustment
     */
    reason: string;
    /**
     * 
     * @type {WarehouseAttr}
     * @memberof RawMaterialInventoryAdjustment
     */
    warehouseAttr: WarehouseAttr;
    /**
     * 
     * @type {string}
     * @memberof RawMaterialInventoryAdjustment
     */
    warehouseId: string;
}

/**
 * Check if a given object implements the RawMaterialInventoryAdjustment interface.
 */
export function instanceOfRawMaterialInventoryAdjustment(value: object): value is RawMaterialInventoryAdjustment {
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    if (!('reason' in value) || value['reason'] === undefined) return false;
    if (!('warehouseAttr' in value) || value['warehouseAttr'] === undefined) return false;
    if (!('warehouseId' in value) || value['warehouseId'] === undefined) return false;
    return true;
}

export function RawMaterialInventoryAdjustmentFromJSON(json: any): RawMaterialInventoryAdjustment {
    return RawMaterialInventoryAdjustmentFromJSONTyped(json, false);
}

export function RawMaterialInventoryAdjustmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): RawMaterialInventoryAdjustment {
    if (json == null) {
        return json;
    }
    return {
        
        'bucket': json['bucket'] == null ? undefined : json['bucket'],
        'quantity': json['quantity'],
        'reason': json['reason'],
        'warehouseAttr': WarehouseAttrFromJSON(json['warehouse_attr']),
        'warehouseId': json['warehouse_id'],
    };
}

export function RawMaterialInventoryAdjustmentToJSON(json: any): RawMaterialInventoryAdjustment {
    return RawMaterialInventoryAdjustmentToJSONTyped(json, false);
}

export function RawMaterialInventoryAdjustmentToJSONTyped(value?: RawMaterialInventoryAdjustment | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bucket': value['bucket'],
        'quantity': value['quantity'],
        'reason': value['reason'],
        'warehouse_attr': WarehouseAttrToJSON(value['warehouseAttr']),
        'warehouse_id': value['warehouseId'],
    };
}

