/* tslint:disable */
/* eslint-disable */
/**
 * Arke Supply API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RawMaterialsInventoryValueItem
 */
export interface RawMaterialsInventoryValueItem {
    /**
     * 
     * @type {string}
     * @memberof RawMaterialsInventoryValueItem
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof RawMaterialsInventoryValueItem
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof RawMaterialsInventoryValueItem
     */
    extraId: string;
    /**
     * 
     * @type {number}
     * @memberof RawMaterialsInventoryValueItem
     */
    quantity: number;
    /**
     * 
     * @type {string}
     * @memberof RawMaterialsInventoryValueItem
     */
    currency: string;
    /**
     * 
     * @type {number}
     * @memberof RawMaterialsInventoryValueItem
     */
    value: number;
}

/**
 * Check if a given object implements the RawMaterialsInventoryValueItem interface.
 */
export function instanceOfRawMaterialsInventoryValueItem(value: object): value is RawMaterialsInventoryValueItem {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('extraId' in value) || value['extraId'] === undefined) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function RawMaterialsInventoryValueItemFromJSON(json: any): RawMaterialsInventoryValueItem {
    return RawMaterialsInventoryValueItemFromJSONTyped(json, false);
}

export function RawMaterialsInventoryValueItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): RawMaterialsInventoryValueItem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'extraId': json['extra_id'],
        'quantity': json['quantity'],
        'currency': json['currency'],
        'value': json['value'],
    };
}

export function RawMaterialsInventoryValueItemToJSON(json: any): RawMaterialsInventoryValueItem {
    return RawMaterialsInventoryValueItemToJSONTyped(json, false);
}

export function RawMaterialsInventoryValueItemToJSONTyped(value?: RawMaterialsInventoryValueItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'extra_id': value['extraId'],
        'quantity': value['quantity'],
        'currency': value['currency'],
        'value': value['value'],
    };
}

