/* tslint:disable */
/* eslint-disable */
/**
 * Arke Supply API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EmailAttr } from './EmailAttr';
import {
    EmailAttrFromJSON,
    EmailAttrFromJSONTyped,
    EmailAttrToJSON,
    EmailAttrToJSONTyped,
} from './EmailAttr';
import type { PhoneAttr } from './PhoneAttr';
import {
    PhoneAttrFromJSON,
    PhoneAttrFromJSONTyped,
    PhoneAttrToJSON,
    PhoneAttrToJSONTyped,
} from './PhoneAttr';

/**
 * 
 * @export
 * @interface SupplierSummary
 */
export interface SupplierSummary {
    /**
     * 
     * @type {string}
     * @memberof SupplierSummary
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof SupplierSummary
     */
    name: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof SupplierSummary
     */
    categories: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof SupplierSummary
     */
    vatNo: string;
    /**
     * 
     * @type {Array<PhoneAttr>}
     * @memberof SupplierSummary
     */
    phones: Array<PhoneAttr>;
    /**
     * 
     * @type {string}
     * @memberof SupplierSummary
     */
    defaultCurrency: string;
    /**
     * 
     * @type {Array<EmailAttr>}
     * @memberof SupplierSummary
     */
    emails: Array<EmailAttr>;
    /**
     * 
     * @type {string}
     * @memberof SupplierSummary
     */
    mode?: SupplierSummaryModeEnum;
}


/**
 * @export
 */
export const SupplierSummaryModeEnum = {
    Ordinary: 'ordinary',
    Self: 'self'
} as const;
export type SupplierSummaryModeEnum = typeof SupplierSummaryModeEnum[keyof typeof SupplierSummaryModeEnum];


/**
 * Check if a given object implements the SupplierSummary interface.
 */
export function instanceOfSupplierSummary(value: object): value is SupplierSummary {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('categories' in value) || value['categories'] === undefined) return false;
    if (!('vatNo' in value) || value['vatNo'] === undefined) return false;
    if (!('phones' in value) || value['phones'] === undefined) return false;
    if (!('defaultCurrency' in value) || value['defaultCurrency'] === undefined) return false;
    if (!('emails' in value) || value['emails'] === undefined) return false;
    return true;
}

export function SupplierSummaryFromJSON(json: any): SupplierSummary {
    return SupplierSummaryFromJSONTyped(json, false);
}

export function SupplierSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): SupplierSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
        'categories': json['categories'],
        'vatNo': json['vat_no'],
        'phones': ((json['phones'] as Array<any>).map(PhoneAttrFromJSON)),
        'defaultCurrency': json['default_currency'],
        'emails': ((json['emails'] as Array<any>).map(EmailAttrFromJSON)),
        'mode': json['mode'] == null ? undefined : json['mode'],
    };
}

export function SupplierSummaryToJSON(json: any): SupplierSummary {
    return SupplierSummaryToJSONTyped(json, false);
}

export function SupplierSummaryToJSONTyped(value?: SupplierSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'categories': value['categories'],
        'vat_no': value['vatNo'],
        'phones': ((value['phones'] as Array<any>).map(PhoneAttrToJSON)),
        'default_currency': value['defaultCurrency'],
        'emails': ((value['emails'] as Array<any>).map(EmailAttrToJSON)),
        'mode': value['mode'],
    };
}

