/* tslint:disable */
/* eslint-disable */
/**
 * Arke Supply API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SupplyNeedsDetails
 */
export interface SupplyNeedsDetails {
    /**
     * 
     * @type {string}
     * @memberof SupplyNeedsDetails
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof SupplyNeedsDetails
     */
    quantity: number;
}

/**
 * Check if a given object implements the SupplyNeedsDetails interface.
 */
export function instanceOfSupplyNeedsDetails(value: object): value is SupplyNeedsDetails {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    return true;
}

export function SupplyNeedsDetailsFromJSON(json: any): SupplyNeedsDetails {
    return SupplyNeedsDetailsFromJSONTyped(json, false);
}

export function SupplyNeedsDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): SupplyNeedsDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'quantity': json['quantity'],
    };
}

export function SupplyNeedsDetailsToJSON(json: any): SupplyNeedsDetails {
    return SupplyNeedsDetailsToJSONTyped(json, false);
}

export function SupplyNeedsDetailsToJSONTyped(value?: SupplyNeedsDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'quantity': value['quantity'],
    };
}

