/* tslint:disable */
/* eslint-disable */
/**
 * Arke Supply API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransportDocumentVerificationRawMaterialDiscrepanciesInner
 */
export interface TransportDocumentVerificationRawMaterialDiscrepanciesInner {
    /**
     * 
     * @type {string}
     * @memberof TransportDocumentVerificationRawMaterialDiscrepanciesInner
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof TransportDocumentVerificationRawMaterialDiscrepanciesInner
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof TransportDocumentVerificationRawMaterialDiscrepanciesInner
     */
    quantity?: number;
}

/**
 * Check if a given object implements the TransportDocumentVerificationRawMaterialDiscrepanciesInner interface.
 */
export function instanceOfTransportDocumentVerificationRawMaterialDiscrepanciesInner(value: object): value is TransportDocumentVerificationRawMaterialDiscrepanciesInner {
    return true;
}

export function TransportDocumentVerificationRawMaterialDiscrepanciesInnerFromJSON(json: any): TransportDocumentVerificationRawMaterialDiscrepanciesInner {
    return TransportDocumentVerificationRawMaterialDiscrepanciesInnerFromJSONTyped(json, false);
}

export function TransportDocumentVerificationRawMaterialDiscrepanciesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransportDocumentVerificationRawMaterialDiscrepanciesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'quantity': json['quantity'] == null ? undefined : json['quantity'],
    };
}

export function TransportDocumentVerificationRawMaterialDiscrepanciesInnerToJSON(json: any): TransportDocumentVerificationRawMaterialDiscrepanciesInner {
    return TransportDocumentVerificationRawMaterialDiscrepanciesInnerToJSONTyped(json, false);
}

export function TransportDocumentVerificationRawMaterialDiscrepanciesInnerToJSONTyped(value?: TransportDocumentVerificationRawMaterialDiscrepanciesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'quantity': value['quantity'],
    };
}

