/* tslint:disable */
/* eslint-disable */
/**
 * Arke Supply API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { QuantifiedItem } from './QuantifiedItem';
import {
    QuantifiedItemFromJSON,
    QuantifiedItemFromJSONTyped,
    QuantifiedItemToJSON,
    QuantifiedItemToJSONTyped,
} from './QuantifiedItem';

/**
 * 
 * @export
 * @interface TransportDocumentExtract
 */
export interface TransportDocumentExtract {
    /**
     * 
     * @type {string}
     * @memberof TransportDocumentExtract
     */
    externalId?: string;
    /**
     * 
     * @type {string}
     * @memberof TransportDocumentExtract
     */
    orderId?: string;
    /**
     * 
     * @type {string}
     * @memberof TransportDocumentExtract
     */
    orderInternalId?: string;
    /**
     * 
     * @type {Array<QuantifiedItem>}
     * @memberof TransportDocumentExtract
     */
    rawMaterials: Array<QuantifiedItem>;
}

/**
 * Check if a given object implements the TransportDocumentExtract interface.
 */
export function instanceOfTransportDocumentExtract(value: object): value is TransportDocumentExtract {
    if (!('rawMaterials' in value) || value['rawMaterials'] === undefined) return false;
    return true;
}

export function TransportDocumentExtractFromJSON(json: any): TransportDocumentExtract {
    return TransportDocumentExtractFromJSONTyped(json, false);
}

export function TransportDocumentExtractFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransportDocumentExtract {
    if (json == null) {
        return json;
    }
    return {
        
        'externalId': json['external_id'] == null ? undefined : json['external_id'],
        'orderId': json['order_id'] == null ? undefined : json['order_id'],
        'orderInternalId': json['order_internal_id'] == null ? undefined : json['order_internal_id'],
        'rawMaterials': ((json['raw_materials'] as Array<any>).map(QuantifiedItemFromJSON)),
    };
}

export function TransportDocumentExtractToJSON(json: any): TransportDocumentExtract {
    return TransportDocumentExtractToJSONTyped(json, false);
}

export function TransportDocumentExtractToJSONTyped(value?: TransportDocumentExtract | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'external_id': value['externalId'],
        'order_id': value['orderId'],
        'order_internal_id': value['orderInternalId'],
        'raw_materials': ((value['rawMaterials'] as Array<any>).map(QuantifiedItemToJSON)),
    };
}

